/* AUTO-GENERATED by tools/eco-step-133c */

const css = `
.eco-mural {
  background: #070b08 !important;
  color: #eaeaea !important;
  min-height: 100vh !important;
  padding: 18px 0 120px !important;
}
.eco-mural-inner {
  width: min(1700px, calc(100% - 32px)) !important;
  margin: 0 auto !important;
  background: #f6f6f6 !important;
  color: #111 !important;
  border: 1px solid #111 !important;
  border-radius: 18px !important;
  padding: 20px !important;
}
.eco-mural h1 {
  font-size: 28px !important;
  line-height: 1.1 !important;
  font-weight: 900 !important;
  letter-spacing: -0.02em !important;
  margin: 10px 0 8px 0 !important;
}
.eco-mural h2 {
  font-size: 18px !important;
  font-weight: 900 !important;
  margin: 10px 0 8px 0 !important;
}
.eco-mural p { font-size: 14px !important; }
.eco-mural a { color: #0b5 !important; text-decoration: underline !important; }
.eco-mural button {
  font-size: 14px !important;
  font-weight: 900 !important;
  border: 1px solid #111 !important;
  border-radius: 12px !important;
  background: #fff !important;
  padding: 10px 12px !important;
}
.eco-mural button[aria-pressed="true"] { background: #fff7cc !important; }
.eco-mural input, .eco-mural select, .eco-mural textarea {
  background: #fff !important;
  color: #111 !important;
  border: 1px solid #111 !important;
  border-radius: 12px !important;
  padding: 10px !important;
  font-size: 14px !important;
}
@media (max-width: 980px) {
  .eco-mural-inner { width: calc(100% - 16px) !important; padding: 16px !important; }
}
`;

export default function MuralReadableStyles() {
  return <style>{css}</style>;
}