"use client";
// eslint-disable-next-line @typescript-eslint/no-unused-vars
function dt(v: any): number {
  const n = Date.parse(String(v || ""));
  return Number.isFinite(n) ? n : 0;
}
function num(v: any): number {
  const n = Number(v);
  return Number.isFinite(n) ? n : 0;
}
// eslint-disable-next-line @typescript-eslint/no-unused-vars
function score(p: any): number {
  const c = (p && p.counts) ? p.counts : {};
  const conf = num(c.confirm ?? p?.confirmCount ?? p?.confirm ?? 0);
  const sup  = num(c.support ?? p?.supportCount ?? p?.support ?? 0);
  const rep  = num(c.replicar ?? p?.replicarCount ?? p?.replicar ?? 0);
  return conf + sup + rep;
}
// AUTO-GENERATED by tools/eco-step-109-wire-mural-actions-ui-v0_1.ps1
// Robust client actions bar for ECO mural items (works with different prop shapes).
// ===== ECO REF GUARD (auto) =====
// Safety-net for accidental leftover identifiers (p/it/item) that cause ReferenceError during SSR/module eval.
// Remove after we fully clean this file.
const __ECO_REF_GUARD__ = 1;
const p: any = {};
const _it: any = {};
const _item: any = {};
// ===== /ECO REF GUARD =====
import * as React from "react";
import { useRouter } from "next/navigation";
import { postMuralAction, type MuralAction } from "@/lib/eco/muralActions";
import MuralPointActionsClient from "../mural/_components/MuralPointActionsClient";
type Counts = { confirm: number; support: number; replicar: number };
function safeNum(v: any): number {
  const n = Number(v);
  return Number.isFinite(n) ? n : 0;
}
function pickPointId(props: any): string | null {
  if (!props) return null;
  if (typeof props.pointId === "string") return props.pointId;
  if (typeof props.id === "string") return props.id;
  if (props.point && typeof props.point.id === "string") return props.point.id;
  if (props.item && typeof props.item.id === "string") return props.item.id;
  return null;
}
function pickCounts(props: any): Counts {
  const c = (props && (props.counts || (props.point && props.point.counts) || (props.item && props.item.counts))) || null;
  return {
    confirm: safeNum(c && c.confirm),
    support: safeNum(c && c.support),
    replicar: safeNum(c && c.replicar),
  };
}
function labelFor(a: MuralAction) {
  if (a === "confirm") return "✅";
  if (a === "support") return "🤝";
  return "♻️";
}
export function MuralAcoesClient(props: any) {
  const router = useRouter();
  const pointId = pickPointId(props);
  const [counts, setCounts] = React.useState<Counts>(() => pickCounts(props));
  const [busy, setBusy] = React.useState<MuralAction | null>(null);
  const actor = (props && (props.actor || (props.point && props.point.actor) || (props.item && props.item.actor))) || undefined;
  React.useEffect(() => {
    setCounts(pickCounts(props));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [props?.pointId, props?.id, props?.point?.id, props?.item?.id, props?.counts, props?.point?.counts, props?.item?.counts]);
  <MuralPointActionsClient pointId={p.id} initialCounts={p.counts} />
  async function act(a: MuralAction) {
    if (!pointId) return;
    if (busy) return;
    setBusy(a);
    try {
      const res = await postMuralAction(a, pointId, actor);
      const created = !!(res && res.created);
      if (created) {
        setCounts((prev) => ({ ...prev, [a]: safeNum((prev as any)[a]) + 1 } as any));
      }
      // Se já existia (created=false), não incrementa otimista.
    } catch (e) {
      // silencia (UI minimalista); dev olha o console
      console.error(e);
    } finally {
      setBusy(null);
      router.refresh();
    }
  }
  if (!pointId) return null;
  const btn = (a: MuralAction) => (
    <button
      key={a}
      type="button"
      onClick={() => act(a)}
      disabled={!!busy}
      className={
        "px-2 py-1 rounded border border-neutral-700/60 bg-black/20 hover:bg-black/30 " +
        "text-xs flex items-center gap-1 " +
        (busy ? "opacity-60 cursor-not-allowed" : "")
      }
      aria-label={a}
      title={a}
    >
      <span>{labelFor(a)}</span>
      <span className="tabular-nums">{safeNum((counts as any)[a])}</span>
    </button>
  );
  return (
    <div className="flex items-center gap-2">
      {btn("confirm")}
      {btn("support")}
      {btn("replicar")}
    </div>
  );
}
export default MuralAcoesClient;
