// AUTO-GENERATED by tools/eco-step-109-wire-mural-actions-ui-v0_1.ps1
// Client helper to call ECO mural actions endpoints.

export type MuralAction = "confirm" | "support" | "replicar";

export async function postMuralAction(action: MuralAction, pointId: string, actor?: string) {
  const res = await fetch("/api/eco/points/" + action, {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({ pointId, ...(actor ? { actor } : {}) }),
  });

  const json = await res.json().catch(() => null as any);
  if (!res.ok) {
    const msg = (json && (json.message || json.error)) ? String(json.message || json.error) : ("http_" + res.status);
    throw new Error(msg);
  }
  return json;
}
