// AUTO-GENERATED by tools/eco-step-107g-fix-points-list-alias-and-front-safe-v0_1.ps1
// Fix: /api/eco/points/list estava retornando 503 (model_not_ready).
// Agora vira alias do list2 (fonte de verdade).

import { GET as GET_LIST2 } from "../list2/route";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

export async function GET(req: Request) {
  return GET_LIST2(req);
}
