param(
  [string]$Root = (Get-Location).Path
)

$ts = Get-Date -Format "yyyyMMdd-HHmmss"

$boot = Join-Path $Root "tools/_bootstrap.ps1"
if (Test-Path -LiteralPath $boot) { . $boot }

if (-not (Get-Command EnsureDir -ErrorAction SilentlyContinue)) {
  function EnsureDir([string]$p) { if (-not (Test-Path -LiteralPath $p)) { New-Item -ItemType Directory -Force -Path $p | Out-Null } }
}
if (-not (Get-Command WriteUtf8NoBom -ErrorAction SilentlyContinue)) {
  function WriteUtf8NoBom([string]$p, [string]$content) {
    EnsureDir (Split-Path -Parent $p)
    $enc = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($p, $content, $enc)
  }
}
if (-not (Get-Command BackupFile -ErrorAction SilentlyContinue)) {
  function BackupFile([string]$root, [string]$p, [string]$backupDir) {
    if (Test-Path -LiteralPath $p) {
      $rel = $p.Substring($root.Length).TrimStart('\','/')
      $dest = Join-Path $backupDir ($rel -replace '[\\/]', '__')
      Copy-Item -Force -LiteralPath $p -Destination $dest
      Write-Host ('[BK] ' + $rel + ' -> ' + (Split-Path -Leaf $dest))
    }
  }
}

Write-Host ('== eco-step-82-share-point-card-v0_1 == ' + $ts)
Write-Host ('[DIAG] Root: ' + $Root)

$srcApp = Join-Path $Root 'src/app'
if (-not (Test-Path -LiteralPath $srcApp)) { throw "[STOP] Nao achei src/app" }

$backupDir = Join-Path $Root ('tools/_patch_backup/' + $ts + '-eco-step-82-share-point-card-v0_1')
$reportDir = Join-Path $Root 'reports'
EnsureDir $backupDir
EnsureDir $reportDir

# ---------------- API: /api/eco/points/get (create if missing) ----------------
$apiGet = Join-Path $srcApp 'api/eco/points/get/route.ts'
if (Test-Path -LiteralPath $apiGet) {
  Write-Host "[SKIP] api/eco/points/get already exists"
} else {
  $LApiGet = @(
'// ECO — points/get — v0.1 (schema-agnostic)',
'',
'import { NextResponse } from "next/server";',
'import { prisma } from "@/lib/prisma";',
'',
'export const runtime = "nodejs";',
'export const dynamic = "force-dynamic";',
'',
'function asMsg(e: unknown) {',
'  if (e instanceof Error) return e.message;',
'  try { return String(e); } catch { return "unknown"; }',
'}',
'function looksLikeMissingTable(msg: string) {',
'  const m = msg.toLowerCase();',
'  return m.includes("does not exist") || m.includes("no such table") || m.includes("p2021");',
'}',
'function getPointModel() {',
'  const pc: any = prisma as any;',
'  const candidates = [',
'    "ecoCriticalPoint",',
'    "criticalPoint",',
'    "ecoPoint",',
'    "point",',
'    "ecoCriticalPoints",',
'    "ecoPoints",',
'  ];',
'  for (const k of candidates) {',
'    const m = pc?.[k];',
'    if (m && (typeof m.findUnique === "function" || typeof m.findFirst === "function")) return { key: k, model: m as any };',
'  }',
'  return null;',
'}',
'function normStatus(v: any) { return String(v || "").trim().toUpperCase(); }',
'function pickStatus(p: any) {',
'  const m = (p && p.meta && typeof p.meta === "object") ? p.meta : null;',
'  return normStatus(p?.status || p?.state || (m && (m.status || m.state)) || "");',
'}',
'function isResolved(s: string) {',
'  const t = normStatus(s);',
'  return t === "RESOLVED" || t === "RESOLVIDO" || t === "DONE" || t === "CLOSED" || t === "FINALIZADO";',
'}',
'function pickTitle(p: any) { return String(p?.title || p?.name || p?.label || p?.kind || "Ponto critico"); }',
'function pickNeighborhood(p: any) {',
'  const m = (p && p.meta && typeof p.meta === "object") ? p.meta : null;',
'  return String(p?.bairro || p?.neighborhood || (m && (m.bairro || m.neighborhood)) || "").trim();',
'}',
'function pickCity(p: any) {',
'  const m = (p && p.meta && typeof p.meta === "object") ? p.meta : null;',
'  return String(p?.cidade || p?.city || (m && (m.cidade || m.city)) || "Volta Redonda").trim();',
'}',
'function pickLat(p: any) {',
'  const m = (p && p.meta && typeof p.meta === "object") ? p.meta : null;',
'  const v = p?.lat ?? p?.latitude ?? (m && (m.lat ?? m.latitude));',
'  const n = Number(v);',
'  return Number.isFinite(n) ? n : null;',
'}',
'function pickLng(p: any) {',
'  const m = (p && p.meta && typeof p.meta === "object") ? p.meta : null;',
'  const v = p?.lng ?? p?.lon ?? p?.longitude ?? (m && (m.lng ?? m.lon ?? m.longitude));',
'  const n = Number(v);',
'  return Number.isFinite(n) ? n : null;',
'}',
'function pickCreatedAt(p: any) {',
'  const v = p?.createdAt || p?.created_at || null;',
'  try { return v ? new Date(v).toISOString() : null; } catch { return null; }',
'}',
'function pickUpdatedAt(p: any) {',
'  const v = p?.updatedAt || p?.updated_at || null;',
'  try { return v ? new Date(v).toISOString() : null; } catch { return null; }',
'}',
'',
'export async function GET(req: Request) {',
'  const { searchParams } = new URL(req.url);',
'  const id = String(searchParams.get("id") || "").trim();',
'  if (!id) return NextResponse.json({ ok: false, error: "missing_id" }, { status: 400 });',
'',
'  const mm = getPointModel();',
'  if (!mm?.model) return NextResponse.json({ ok: false, error: "model_not_ready" }, { status: 503 });',
'',
'  try {',
'    let row: any = null;',
'    if (typeof mm.model.findUnique === "function") {',
'      try { row = await mm.model.findUnique({ where: { id } }); } catch { row = null; }',
'    }',
'    if (!row && typeof mm.model.findFirst === "function") {',
'      row = await mm.model.findFirst({ where: { id } });',
'    }',
'    if (!row) return NextResponse.json({ ok: false, error: "not_found" }, { status: 404 });',
'',
'    const st = pickStatus(row);',
'    const item = {',
'      id: String(row?.id || ""),',
'      title: pickTitle(row),',
'      status: st || "OPEN",',
'      resolved: isResolved(st),',
'      bairro: pickNeighborhood(row),',
'      cidade: pickCity(row),',
'      lat: pickLat(row),',
'      lng: pickLng(row),',
'      createdAt: pickCreatedAt(row),',
'      updatedAt: pickUpdatedAt(row),',
'      meta: (row && row.meta && typeof row.meta === "object") ? row.meta : null,',
'    };',
'',
'    return NextResponse.json({ ok: true, item, model: mm.key });',
'  } catch (e) {',
'    const msg = asMsg(e);',
'    if (looksLikeMissingTable(msg)) return NextResponse.json({ ok: false, error: "db_not_ready", detail: msg }, { status: 503 });',
'    return NextResponse.json({ ok: false, error: "db_error", detail: msg }, { status: 500 });',
'  }',
'}',
''
) -join "`n"

  WriteUtf8NoBom $apiGet $LApiGet
  Write-Host "[PATCH] wrote src/app/api/eco/points/get/route.ts"
}

# ---------------- API: /api/eco/points/card (new) ----------------
$apiCard = Join-Path $srcApp 'api/eco/points/card/route.tsx'
BackupFile $Root $apiCard $backupDir

$LApiCard = @(
'// ECO — points/card — v0.1 (ImageResponse)',
'',
'import { ImageResponse } from "next/og";',
'',
'export const runtime = "nodejs";',
'export const dynamic = "force-dynamic";',
'',
'function safeFmt(v: string | null) {',
'  const s = String(v || "").toLowerCase().trim();',
'  if (s === "1x1") return "1x1";',
'  return "3x4";',
'}',
'function clampTxt(s: string, max: number) {',
'  const t = String(s || "");',
'  if (t.length <= max) return t;',
'  return t.slice(0, Math.max(0, max - 1)) + "…";',
'}',
'function normStatus(v: any) { return String(v || "").trim().toUpperCase(); }',
'function isResolved(s: string) {',
'  const t = normStatus(s);',
'  return t === "RESOLVED" || t === "RESOLVIDO" || t === "DONE" || t === "CLOSED" || t === "FINALIZADO";',
'}',
'',
'export async function GET(req: Request) {',
'  const { searchParams } = new URL(req.url);',
'  const id = String(searchParams.get("id") || "").trim();',
'  const format = safeFmt(searchParams.get("format"));',
'  if (!id) return new Response("missing id", { status: 400 });',
'',
'  // fetch point data from internal API (node runtime ok)',
'  const base = new URL(req.url);',
'  base.pathname = "/api/eco/points/get";',
'  base.search = "id=" + encodeURIComponent(id);',
'',
'  let item: any = null;',
'  try {',
'    const r = await fetch(base.toString(), { cache: "no-store" });',
'    const j: any = await r.json().catch(() => null);',
'    if (j && j.ok) item = j.item;',
'  } catch {}',
'',
'  const title = clampTxt(String(item?.title || "Ponto critico"), 72);',
'  const status = normStatus(item?.status || "OPEN") || "OPEN";',
'  const resolved = isResolved(status) || Boolean(item?.resolved);',
'  const bairro = clampTxt(String(item?.bairro || ""), 36);',
'  const cidade = clampTxt(String(item?.cidade || "Volta Redonda"), 36);',
'  const place = bairro ? (bairro + " — " + cidade) : cidade;',
'  const idShort = clampTxt(id, 18);',
'',
'  const W = 1080;',
'  const H = (format === "1x1") ? 1080 : 1350;',
'',
'  const bg = "#0b0b0b";',
'  const yellow = "#FFDD00";',
'  const white = "#F5F5F5";',
'  const red = "#FF3B30";',
'  const pill = resolved ? "#B7FFB7" : yellow;',
'  const pillTxt = resolved ? "#082b08" : "#111";',
'',
'  return new ImageResponse(',
'    (',
'      <div style={{ width: W, height: H, display: "flex", flexDirection: "column", background: bg, padding: 48 }}>',
'        <div style={{ display: "flex", flexDirection: "column", gap: 18, padding: 28, borderRadius: 26, border: "2px solid #1b1b1b", background: "#111" }}>',
'          <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", gap: 14 }}>',
'            <div style={{ display: "flex", alignItems: "center", gap: 14 }}>',
'              <div style={{ width: 14, height: 44, display: "flex", background: yellow, borderRadius: 8 }} />',
'              <div style={{ display: "flex", flexDirection: "column", gap: 6 }}>',
'                <div style={{ display: "flex", color: white, fontSize: 34, fontWeight: 900, letterSpacing: 1 }}>',
'                  MURAL DO CUIDADO',
'                </div>',
'                <div style={{ display: "flex", color: "#cfcfcf", fontSize: 18, fontWeight: 800 }}>',
'                  Reacao vira acao — confirmar, apoiar, organizar',
'                </div>',
'              </div>',
'            </div>',
'            <div style={{ display: "flex", padding: "10px 14px", borderRadius: 999, background: pill, color: pillTxt, fontWeight: 950, fontSize: 18, border: "2px solid #111" }}>',
'              {resolved ? "RESOLVIDO" : "ABERTO"}',
'            </div>',
'          </div>',
'',
'          <div style={{ display: "flex", flexDirection: "column", gap: 14, padding: 18, borderRadius: 18, background: "#0e0e0e", border: "1px solid #222" }}>',
'            <div style={{ display: "flex", color: yellow, fontSize: 22, fontWeight: 950, letterSpacing: 0.6 }}>',
'              PONTO CRITICO',
'            </div>',
'            <div style={{ display: "flex", color: white, fontSize: 54, fontWeight: 950, lineHeight: 1.05 }}>',
'              {title}',
'            </div>',
'            <div style={{ display: "flex", color: "#d9d9d9", fontSize: 22, fontWeight: 850 }}>',
'              {place}',
'            </div>',
'            <div style={{ display: "flex", color: "#9f9f9f", fontSize: 18, fontWeight: 800 }}>',
'              ID: {idShort}',
'            </div>',
'          </div>',
'        </div>',
'',
'        <div style={{ flex: 1, display: "flex" }} />',
'',
'        <div style={{ display: "flex", flexDirection: "column", gap: 16 }}>',
'          <div style={{ display: "flex", padding: 18, borderRadius: 18, background: yellow, border: "2px solid #111", justifyContent: "space-between", alignItems: "center", gap: 16 }}>',
'            <div style={{ display: "flex", flexDirection: "column", gap: 6 }}>',
'              <div style={{ display: "flex", fontSize: 24, fontWeight: 950, color: "#111" }}>O que fazer agora:</div>',
'              <div style={{ display: "flex", fontSize: 18, fontWeight: 900, color: "#111" }}>CONFIRME • APOIE • CHAME MUTIRAO</div>',
'            </div>',
'            <div style={{ display: "flex", padding: "10px 14px", borderRadius: 14, background: "#111", color: yellow, fontWeight: 950, fontSize: 18 }}>',
'              #ECO  #ReciboECO',
'            </div>',
'          </div>',
'',
'          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", gap: 14 }}>',
'            <div style={{ display: "flex", color: "#cfcfcf", fontWeight: 850, fontSize: 16 }}>',
'              Trabalho digno no centro • Sem greenwashing',
'            </div>',
'            <div style={{ display: "flex", color: red, fontWeight: 950, fontSize: 16 }}>',
'              Abandono x Cuidado',
'            </div>',
'          </div>',
'        </div>',
'      </div>',
'    ),',
'    { width: W, height: H }',
'  );',
'}',
''
) -join "`n"

WriteUtf8NoBom $apiCard $LApiCard
Write-Host "[PATCH] wrote src/app/api/eco/points/card/route.tsx"

# ---------------- UI: /eco/share/ponto/[id] ----------------
$shareDir = Join-Path $srcApp 'eco/share/ponto/[id]'
$pageFile = Join-Path $shareDir 'page.tsx'
$clientFile = Join-Path $shareDir 'SharePointClient.tsx'

BackupFile $Root $pageFile $backupDir
BackupFile $Root $clientFile $backupDir

$LSharePage = @(
'// ECO — Share Ponto — v0.1',
'',
'import { SharePointClient } from "./SharePointClient";',
'',
'export const runtime = "nodejs";',
'export const dynamic = "force-dynamic";',
'',
'export default async function Page({ params }: any) {',
'  const p = await (params as any);',
'  const id = String(p?.id || "");',
'  return (',
'    <main style={{ padding: 16, maxWidth: 1100, margin: "0 auto" }}>',
'      <h1 style={{ margin: "0 0 8px 0" }}>Compartilhar ponto</h1>',
'      <p style={{ margin: "0 0 14px 0", opacity: 0.85 }}>Card + legenda prontos para postar.</p>',
'      <SharePointClient id={id} />',
'    </main>',
'  );',
'}',
''
) -join "`n"

$LShareClient = @(
'"use client";',
'',
'import React, { useEffect, useMemo, useState } from "react";',
'',
'type Item = {',
'  id: string;',
'  title: string;',
'  status: string;',
'  resolved: boolean;',
'  bairro?: string;',
'  cidade?: string;',
'  lat?: number | null;',
'  lng?: number | null;',
'};',
'',
'async function apiGet(id: string) {',
'  const r = await fetch("/api/eco/points/get?id=" + encodeURIComponent(id), { cache: "no-store" });',
'  return await r.json().catch(() => ({ ok: false, error: "bad_json" }));',
'}',
'',
'function btn(bg: string) {',
'  return { padding: "9px 10px", borderRadius: 12, border: "1px solid #111", background: bg, fontWeight: 900, cursor: "pointer" } as const;',
'}',
'',
'async function copyText(s: string) {',
'  try {',
'    await navigator.clipboard.writeText(s);',
'    return true;',
'  } catch {',
'    try {',
'      const ta = document.createElement("textarea");',
'      ta.value = s;',
'      ta.style.position = "fixed";',
'      ta.style.left = "-9999px";',
'      document.body.appendChild(ta);',
'      ta.select();',
'      document.execCommand("copy");',
'      document.body.removeChild(ta);',
'      return true;',
'    } catch {',
'      return false;',
'    }',
'  }',
'}',
'',
'export function SharePointClient(props: { id: string }) {',
'  const id = String(props.id || "");',
'  const [item, setItem] = useState<Item | null>(null);',
'  const [loading, setLoading] = useState(true);',
'  const [err, setErr] = useState("");',
'  const [toast, setToast] = useState("");',
'  const [mounted, setMounted] = useState(false);',
'  const [origin, setOrigin] = useState("");',
'',
'  useEffect(() => {',
'    setMounted(true);',
'    try { setOrigin(window.location.origin || ""); } catch {}',
'  }, []);',
'',
'  useEffect(() => {',
'    let alive = true;',
'    (async () => {',
'      setLoading(true); setErr("");',
'      try {',
'        const j: any = await apiGet(id);',
'        if (!j?.ok) throw new Error(String(j?.error || "nao_encontrado"));',
'        if (!alive) return;',
'        setItem(j.item as Item);',
'      } catch (e: any) {',
'        if (!alive) return;',
'        setErr(String(e?.message || e));',
'      } finally {',
'        if (!alive) return;',
'        setLoading(false);',
'      }',
'    })();',
'    return () => { alive = false; };',
'  }, [id]);',
'',
'  const shareLink = useMemo(() => {',
'    const path = "/eco/share/ponto/" + encodeURIComponent(id);',
'    return origin ? (origin + path) : path;',
'  }, [origin, id]);',
'',
'  const card3x4 = useMemo(() => "/api/eco/points/card?format=3x4&id=" + encodeURIComponent(id), [id]);',
'  const card1x1 = useMemo(() => "/api/eco/points/card?format=1x1&id=" + encodeURIComponent(id), [id]);',
'',
'  const legenda = useMemo(() => {',
'    const t = item?.title ? item.title : "Ponto critico";',
'    const place = (item?.bairro ? (item.bairro + " — " + (item.cidade || "Volta Redonda")) : (item?.cidade || "Volta Redonda"));',
'    const st = item?.resolved ? "RESOLVIDO" : (item?.status || "ABERTO");',
'    const txt = "ECO — Ponto critico\\n" + t + "\\n" + place + "\\nStatus: " + st + "\\n" + shareLink + "\\n\\nAcoes: confirme, apoie e chame mutirao.\\n#ECO #ReciboECO #Reciclagem #VoltaRedonda #EconomiaSolidaria";',
'    return txt;',
'  }, [item, shareLink]);',
'',
'  const waHref = useMemo(() => {',
'    if (!mounted) return "";',
'    return "https://wa.me/?text=" + encodeURIComponent(legenda);',
'  }, [mounted, legenda]);',
'',
'  const mapsHref = useMemo(() => {',
'    if (!mounted) return "";',
'    const lat = item?.lat;',
'    const lng = item?.lng;',
'    if (typeof lat !== "number" || typeof lng !== "number") return "";',
'    return "https://www.google.com/maps?q=" + String(lat) + "," + String(lng);',
'  }, [mounted, item]);',
'',
'  async function doCopyLink() {',
'    const ok = await copyText(shareLink);',
'    setToast(ok ? "Link copiado" : "Falha ao copiar");',
'    setTimeout(() => setToast(""), 1200);',
'  }',
'  async function doCopyLegenda() {',
'    const ok = await copyText(legenda);',
'    setToast(ok ? "Legenda copiada" : "Falha ao copiar");',
'    setTimeout(() => setToast(""), 1200);',
'  }',
'',
'  return (',
'    <section style={{ display: "grid", gap: 14 }}>',
'      {loading ? <div style={{ opacity: 0.85 }}>Carregando…</div> : null}',
'      {err ? <div style={{ padding: 12, border: "1px solid #111", borderRadius: 14, background: "#fff2f2" }}><b>Erro:</b> {err}</div> : null}',
'',
'      <div style={{ display: "grid", gap: 10, border: "1px solid #111", borderRadius: 16, padding: 12, background: "#fff" }}>',
'        <div style={{ display: "flex", alignItems: "baseline", justifyContent: "space-between", gap: 10, flexWrap: "wrap" }}>',
'          <div style={{ display: "grid", gap: 6 }}>',
'            <div style={{ fontWeight: 950, fontSize: 16 }}>{item?.title || "Ponto critico"}</div>',
'            <div style={{ fontSize: 13, opacity: 0.8, fontWeight: 800 }}>{item?.bairro ? (item.bairro + " — " + (item.cidade || "Volta Redonda")) : (item?.cidade || "Volta Redonda")}</div>',
'            <div style={{ fontSize: 12, opacity: 0.7 }}>ID: {id}</div>',
'          </div>',
'          <div style={{ display: "flex", padding: "8px 12px", borderRadius: 999, border: "1px solid #111", background: item?.resolved ? "#B7FFB7" : "#FFDD00", fontWeight: 950 }}>',
'            {item?.resolved ? "RESOLVIDO" : (item?.status || "ABERTO")}',
'          </div>',
'        </div>',
'',
'        <div style={{ display: "grid", gap: 10 }}>',
'          <div style={{ display: "grid", gap: 8 }}>',
'            <div style={{ fontWeight: 950 }}>Cards</div>',
'            <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10 }}>',
'              <a href={card3x4} target="_blank" rel="noreferrer" style={{ textDecoration: "none", color: "#111" }}>',
'                <div style={{ border: "1px solid #111", borderRadius: 14, padding: 10, display: "grid", gap: 8 }}>',
'                  <div style={{ fontWeight: 900 }}>3:4 (1080×1350)</div>',
'                  <img src={card3x4} alt="card 3x4" style={{ width: "100%", borderRadius: 12, border: "1px solid #111", background: "#111" }} />',
'                </div>',
'              </a>',
'              <a href={card1x1} target="_blank" rel="noreferrer" style={{ textDecoration: "none", color: "#111" }}>',
'                <div style={{ border: "1px solid #111", borderRadius: 14, padding: 10, display: "grid", gap: 8 }}>',
'                  <div style={{ fontWeight: 900 }}>1:1 (1080×1080)</div>',
'                  <img src={card1x1} alt="card 1x1" style={{ width: "100%", borderRadius: 12, border: "1px solid #111", background: "#111" }} />',
'                </div>',
'              </a>',
'            </div>',
'          </div>',
'',
'          <div style={{ display: "grid", gap: 8 }}>',
'            <div style={{ fontWeight: 950 }}>Acoes rapidas</div>',
'            <div style={{ display: "flex", gap: 10, flexWrap: "wrap" }}>',
'              <button onClick={doCopyLink} style={btn("#FFDD00")}>Copiar link</button>',
'              <button onClick={doCopyLegenda} style={btn("#fff")}>Copiar legenda</button>',
'              {mounted ? (',
'                <a href={waHref} target="_blank" rel="noreferrer" style={{ padding: "9px 10px", borderRadius: 12, border: "1px solid #111", textDecoration: "none", color: "#111", fontWeight: 900, background: "#fff" }}>',
'                  WhatsApp',
'                </a>',
'              ) : (',
'                <span style={{ padding: "9px 10px", borderRadius: 12, border: "1px solid #111", opacity: 0.6, fontWeight: 900 }}>WhatsApp</span>',
'              )}',
'              {mapsHref ? (',
'                <a href={mapsHref} target="_blank" rel="noreferrer" style={{ padding: "9px 10px", borderRadius: 12, border: "1px solid #111", textDecoration: "none", color: "#111", fontWeight: 900, background: "#fff" }}>',
'                  Ver no mapa',
'                </a>',
'              ) : null}',
'            </div>',
'          </div>',
'',
'          <div style={{ display: "grid", gap: 8 }}>',
'            <div style={{ fontWeight: 950 }}>Legenda</div>',
'            <textarea readOnly value={legenda} style={{ width: "100%", minHeight: 140, padding: 10, borderRadius: 12, border: "1px solid #111", fontFamily: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace", fontSize: 12 }} />',
'          </div>',
'        </div>',
'      </div>',
'',
'      {toast ? (',
'        <div style={{ position: "sticky", bottom: 10, display: "flex", justifyContent: "center" }}>',
'          <div style={{ padding: "10px 12px", borderRadius: 14, border: "1px solid #111", background: "#FFDD00", fontWeight: 950 }}>',
'            {toast}',
'          </div>',
'        </div>',
'      ) : null}',
'    </section>',
'  );',
'}',
''
) -join "`n"

WriteUtf8NoBom $pageFile $LSharePage
WriteUtf8NoBom $clientFile $LShareClient
Write-Host "[PATCH] wrote src/app/eco/share/ponto/[id] (page + client)"

# ---------------- REPORT ----------------
$rep = Join-Path $reportDir ('eco-step-82-share-point-card-v0_1-' + $ts + '.md')
$repLines = @(
'# eco-step-82-share-point-card-v0_1',
'',
'- Time: ' + $ts,
'- Backup: ' + $backupDir,
'',
'## Added/Updated',
'- src/app/api/eco/points/get/route.ts (if missing)',
'- src/app/api/eco/points/card/route.tsx',
'- src/app/eco/share/ponto/[id]/page.tsx',
'- src/app/eco/share/ponto/[id]/SharePointClient.tsx',
'',
'## Verify',
'1) Ctrl+C -> npm run dev',
'2) Abra /eco/mural e clique "Compartilhar" em um ponto',
'3) Confere os cards 3x4 e 1x1 (abre em nova aba)',
'4) Copiar link / Copiar legenda / WhatsApp sem hydration warning'
)
WriteUtf8NoBom $rep ($repLines -join "`n")
Write-Host ('[REPORT] ' + $rep)

Write-Host ""
Write-Host "[VERIFY] Ctrl+C -> npm run dev"
Write-Host "[VERIFY] Abra /eco/mural e clique Compartilhar em um item"