param(
  [string]$Root = (Get-Location).Path
)

function EnsureDir([string]$p) { if (-not (Test-Path $p)) { New-Item -ItemType Directory -Force -Path $p | Out-Null } }
function BackupFile([string]$p, [string]$backupDir) {
  if (Test-Path $p) {
    $rel = $p.Substring($Root.Length).TrimStart('\','/')
    $dest = Join-Path $backupDir ($rel -replace '[\\/]', '__')
    Copy-Item -Force -LiteralPath $p -Destination $dest
    Write-Host ("[BK] " + $rel + " -> " + (Split-Path -Leaf $dest))
  }
}

$ts = Get-Date -Format "yyyyMMdd-HHmmss"
$backupDir = Join-Path $Root ("tools/_patch_backup/" + $ts + "-eco-step-58-share-pack-v0_1")
$reportDir = Join-Path $Root "reports"
EnsureDir $backupDir
EnsureDir $reportDir

# Targets
$hubPage   = Join-Path $Root "src/app/eco/share/page.tsx"

$dayPage   = Join-Path $Root "src/app/eco/share/dia/[day]/page.tsx"
$dayClient = Join-Path $Root "src/app/eco/share/dia/[day]/ShareDayClient.tsx"

$monPage   = Join-Path $Root "src/app/eco/share/mes/[month]/page.tsx"
$monClient = Join-Path $Root "src/app/eco/share/mes/[month]/ShareMonthClient.tsx"

$fechClient = Join-Path $Root "src/app/eco/fechamento/FechamentoClient.tsx"
$tranClient = Join-Path $Root "src/app/eco/transparencia/TransparenciaClient.tsx"

Write-Host ("[DIAG] Root: " + $Root)
Write-Host ("[DIAG] Will write: " + $hubPage)
Write-Host ("[DIAG] Will write: " + $dayPage)
Write-Host ("[DIAG] Will write: " + $dayClient)
Write-Host ("[DIAG] Will write: " + $monPage)
Write-Host ("[DIAG] Will write: " + $monClient)
Write-Host ("[DIAG] Will patch (rewrite): " + $fechClient)
Write-Host ("[DIAG] Will patch (rewrite): " + $tranClient)

BackupFile $hubPage $backupDir
BackupFile $dayPage $backupDir
BackupFile $dayClient $backupDir
BackupFile $monPage $backupDir
BackupFile $monClient $backupDir
BackupFile $fechClient $backupDir
BackupFile $tranClient $backupDir

$enc = New-Object System.Text.UTF8Encoding($false)

# ---------------- /eco/share hub ----------------
$LHub = @(
'// ECO — Share Pack Hub — step 58',
'',
'export const dynamic = "force-dynamic";',
'',
'export default function Page() {',
'  return (',
'    <main style={{ padding: 16, fontFamily: "system-ui, -apple-system, Segoe UI, Roboto, Arial" }}>',
'      <h1 style={{ margin: "0 0 8px 0" }}>ECO — Share Pack</h1>',
'      <p style={{ margin: "0 0 16px 0", opacity: 0.85 }}>',
'        Cards + legenda prontos para compartilhar (WhatsApp/Instagram).',
'      </p>',
'      <ul style={{ margin: 0, paddingLeft: 18, display: "grid", gap: 8 }}>',
'        <li><a href="/eco/share/dia/2025-12-27">Share do Dia (exemplo)</a></li>',
'        <li><a href="/eco/share/mes/2025-12">Share do Mês (exemplo)</a></li>',
'      </ul>',
'      <div style={{ height: 12 }} />',
'      <p style={{ margin: 0, opacity: 0.75 }}>',
'        Dica: use os botões “Abrir Share” nas telas de Fechamento e Transparência.',
'      </p>',
'    </main>',
'  );',
'}',
''
)
EnsureDir (Split-Path -Parent $hubPage)
[System.IO.File]::WriteAllLines($hubPage, $LHub, $enc)
Write-Host "[PATCH] wrote src/app/eco/share/page.tsx"

# ---------------- /eco/share/dia/[day] ----------------
$LDayPage = @(
'// ECO — Share Day Page — step 58',
'',
'import ShareDayClient from "./ShareDayClient";',
'',
'export const dynamic = "force-dynamic";',
'',
'export default async function Page(props: { params: Promise<{ day: string }> }) {',
'  const params = await props.params;',
'  return (',
'    <main style={{ padding: 16, fontFamily: "system-ui, -apple-system, Segoe UI, Roboto, Arial" }}>',
'      <h1 style={{ margin: "0 0 8px 0" }}>ECO — Share do Dia</h1>',
'      <p style={{ margin: "0 0 16px 0", opacity: 0.85 }}>',
'        Card + legenda prontos para postar.',
'      </p>',
'      <ShareDayClient day={params.day} />',
'    </main>',
'  );',
'}',
''
)
EnsureDir (Split-Path -Parent $dayPage)
[System.IO.File]::WriteAllLines($dayPage, $LDayPage, $enc)
Write-Host "[PATCH] wrote src/app/eco/share/dia/[day]/page.tsx"

$LDayClient = @(
'"use client";',
'',
'import { useEffect, useMemo, useState } from "react";',
'',
'type AnyObj = Record<string, any>;',
'',
'function fmtKg(n: any): string {',
'  const v = Number(n || 0) || 0;',
'  const s = Math.round(v * 10) / 10;',
'  return String(s).replace(".", ",") + " kg";',
'}',
'',
'function topMaterials(by: any): Array<{ k: string; v: number }> {',
'  const out: Array<{ k: string; v: number }> = [];',
'  if (by && typeof by === "object") {',
'    for (const k of Object.keys(by)) out.push({ k, v: Number(by[k] || 0) || 0 });',
'  }',
'  out.sort((a, b) => b.v - a.v);',
'  return out.slice(0, 5);',
'}',
'',
'async function jget(url: string): Promise<AnyObj> {',
'  const res = await fetch(url, { headers: { Accept: "application/json" }, cache: "no-store" });',
'  const data = await res.json().catch(() => ({}));',
'  if (!res.ok) return { ok: false, status: res.status, ...data };',
'  return data;',
'}',
'',
'async function copyText(txt: string) {',
'  try {',
'    await navigator.clipboard.writeText(txt);',
'    return true;',
'  } catch {',
'    try {',
'      const ta = document.createElement("textarea");',
'      ta.value = txt;',
'      document.body.appendChild(ta);',
'      ta.select();',
'      document.execCommand("copy");',
'      document.body.removeChild(ta);',
'      return true;',
'    } catch {',
'      return false;',
'    }',
'  }',
'}',
'',
'export default function ShareDayClient(props: { day: string }) {',
'  const day = String(props.day || "").trim();',
'  const [data, setData] = useState<AnyObj | null>(null);',
'  const [status, setStatus] = useState<string>("carregando");',
'  const [copied, setCopied] = useState<string>("");',
'',
'  const apiUrl = useMemo(() => "/api/eco/day-close?day=" + encodeURIComponent(day), [day]);',
'  const card34 = useMemo(() => "/api/eco/day-close/card?format=3x4&day=" + encodeURIComponent(day), [day]);',
'  const card11 = useMemo(() => "/api/eco/day-close/card?format=1x1&day=" + encodeURIComponent(day), [day]);',
'',
'  const linkHere = useMemo(() => {',
'    if (typeof window === "undefined") return "";',
'    return window.location.href;',
'  }, [day]);',
'',
'  useEffect(() => {',
'    let alive = true;',
'    (async () => {',
'      setStatus("carregando");',
'      const d = await jget(apiUrl);',
'      if (!alive) return;',
'      setData(d);',
'      setStatus(d && d.ok ? "ok" : "erro");',
'    })();',
'    return () => { alive = false; };',
'  }, [apiUrl]);',
'',
'  const caption = useMemo(() => {',
'    if (!data || !data.ok) {',
'      return "ECO — Fechamento do dia " + day + "\\n" +',
'        "Sem dados (ainda).\\n" +',
'        "\\n#ECO — Escutar • Cuidar • Organizar";',
'    }',
'    const summary = (data.item && data.item.summary) ? data.item.summary : {};',
'    const totals = summary.totals || {};',
'    const totalKg = fmtKg(totals.totalKg || 0);',
'    const mats = topMaterials(totals.byMaterialKg || {});',
'    const lines: string[] = [];',
'    lines.push("ECO — Fechamento do dia " + day);',
'    lines.push("Total: " + totalKg);',
'    if (mats.length) {',
'      lines.push("");',
'      lines.push("Por material:");',
'      for (const m of mats) lines.push("- " + String(m.k).toUpperCase() + ": " + fmtKg(m.v));',
'    }',
'    lines.push("");',
'    lines.push("Recibo é lei. Cuidado é coletivo. Trabalho digno é o centro.");',
'    lines.push("#ECO — Escutar • Cuidar • Organizar");',
'    return lines.join("\\n");',
'  }, [data, day]);',
'',
'  const waLink = useMemo(() => {',
'    const base = "https://wa.me/?text=";',
'    const text = caption + (linkHere ? ("\\n\\n" + linkHere) : "");',
'    return base + encodeURIComponent(text);',
'  }, [caption, linkHere]);',
'',
'  async function doCopyCaption() {',
'    const ok = await copyText(caption);',
'    setCopied(ok ? "Legenda copiada!" : "Falhou ao copiar");',
'    setTimeout(() => setCopied(""), 1600);',
'  }',
'',
'  async function doCopyLink() {',
'    const ok = await copyText(linkHere || "");',
'    setCopied(ok ? "Link copiado!" : "Falhou ao copiar");',
'    setTimeout(() => setCopied(""), 1600);',
'  }',
'',
'  return (',
'    <section style={{ display: "grid", gap: 12, maxWidth: 1100 }}>',
'      <div style={{ display: "flex", gap: 10, alignItems: "center", flexWrap: "wrap" }}>',
'        <a href="/eco/fechamento" style={{ textDecoration: "none" }}>← voltar</a>',
'        <div style={{ opacity: 0.8 }}>status: {status}</div>',
'        {copied ? <div style={{ padding: "6px 10px", border: "1px solid #ddd", borderRadius: 10 }}>{copied}</div> : null}',
'      </div>',
'',
'      <div style={{ display: "flex", gap: 10, flexWrap: "wrap" }}>',
'        <a href={card34} target="_blank" rel="noreferrer" style={{ padding: "8px 10px", borderRadius: 10, border: "1px solid #111", background: "#F7D500", color: "#111", fontWeight: 800, textDecoration: "none" }}>Abrir Card 3:4</a>',
'        <a href={card11} target="_blank" rel="noreferrer" style={{ padding: "8px 10px", borderRadius: 10, border: "1px solid #111", background: "#F7D500", color: "#111", fontWeight: 800, textDecoration: "none" }}>Abrir Card 1:1</a>',
'        <button onClick={doCopyCaption} style={{ padding: "8px 10px", borderRadius: 10, border: "1px solid #111" }}>Copiar legenda</button>',
'        <button onClick={doCopyLink} style={{ padding: "8px 10px", borderRadius: 10, border: "1px solid #111" }}>Copiar link</button>',
'        <a href={waLink} target="_blank" rel="noreferrer" style={{ padding: "8px 10px", borderRadius: 10, border: "1px solid #111", textDecoration: "none", color: "#111" }}>WhatsApp</a>',
'      </div>',
'',
'      <div style={{ display: "grid", gap: 12, gridTemplateColumns: "1fr 1fr" }}>',
'        <div>',
'          <h2 style={{ margin: "0 0 8px 0" }}>Preview 3:4</h2>',
'          <div style={{ border: "1px solid #ddd", borderRadius: 12, padding: 10, overflow: "hidden" }}>',
'            <img src={card34} alt="Card 3:4" style={{ width: "100%", height: "auto", display: "block" }} />',
'          </div>',
'        </div>',
'        <div>',
'          <h2 style={{ margin: "0 0 8px 0" }}>Preview 1:1</h2>',
'          <div style={{ border: "1px solid #ddd", borderRadius: 12, padding: 10, overflow: "hidden" }}>',
'            <img src={card11} alt="Card 1:1" style={{ width: "100%", height: "auto", display: "block" }} />',
'          </div>',
'        </div>',
'      </div>',
'',
'      <div>',
'        <h2 style={{ margin: "0 0 8px 0" }}>Legenda</h2>',
'        <textarea readOnly value={caption} style={{ width: "100%", minHeight: 220, padding: 12, border: "1px solid #ddd", borderRadius: 12, fontFamily: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace" }} />',
'      </div>',
'',
'      <div>',
'        <h2 style={{ margin: "0 0 8px 0" }}>Debug</h2>',
'        <pre style={{ whiteSpace: "pre-wrap", wordBreak: "break-word", padding: 12, border: "1px solid #ddd", borderRadius: 12 }}>',
'          {data ? JSON.stringify(data, null, 2) : "—"}',
'        </pre>',
'      </div>',
'    </section>',
'  );',
'}',
''
)
EnsureDir (Split-Path -Parent $dayClient)
[System.IO.File]::WriteAllLines($dayClient, $LDayClient, $enc)
Write-Host "[PATCH] wrote src/app/eco/share/dia/[day]/ShareDayClient.tsx"

# ---------------- /eco/share/mes/[month] ----------------
$LMonPage = @(
'// ECO — Share Month Page — step 58',
'',
'import ShareMonthClient from "./ShareMonthClient";',
'',
'export const dynamic = "force-dynamic";',
'',
'export default async function Page(props: { params: Promise<{ month: string }> }) {',
'  const params = await props.params;',
'  return (',
'    <main style={{ padding: 16, fontFamily: "system-ui, -apple-system, Segoe UI, Roboto, Arial" }}>',
'      <h1 style={{ margin: "0 0 8px 0" }}>ECO — Share do Mês</h1>',
'      <p style={{ margin: "0 0 16px 0", opacity: 0.85 }}>',
'        Transparência mensal em formato de post.',
'      </p>',
'      <ShareMonthClient month={params.month} />',
'    </main>',
'  );',
'}',
''
)
EnsureDir (Split-Path -Parent $monPage)
[System.IO.File]::WriteAllLines($monPage, $LMonPage, $enc)
Write-Host "[PATCH] wrote src/app/eco/share/mes/[month]/page.tsx"

$LMonClient = @(
'"use client";',
'',
'import { useEffect, useMemo, useState } from "react";',
'',
'type AnyObj = Record<string, any>;',
'',
'function fmtKg(n: any): string {',
'  const v = Number(n || 0) || 0;',
'  const s = Math.round(v * 10) / 10;',
'  return String(s).replace(".", ",") + " kg";',
'}',
'',
'function topMaterials(by: any): Array<{ k: string; v: number }> {',
'  const out: Array<{ k: string; v: number }> = [];',
'  if (by && typeof by === "object") {',
'    for (const k of Object.keys(by)) out.push({ k, v: Number(by[k] || 0) || 0 });',
'  }',
'  out.sort((a, b) => b.v - a.v);',
'  return out.slice(0, 6);',
'}',
'',
'async function jget(url: string): Promise<AnyObj> {',
'  const res = await fetch(url, { headers: { Accept: "application/json" }, cache: "no-store" });',
'  const data = await res.json().catch(() => ({}));',
'  if (!res.ok) return { ok: false, status: res.status, ...data };',
'  return data;',
'}',
'',
'async function copyText(txt: string) {',
'  try {',
'    await navigator.clipboard.writeText(txt);',
'    return true;',
'  } catch {',
'    try {',
'      const ta = document.createElement("textarea");',
'      ta.value = txt;',
'      document.body.appendChild(ta);',
'      ta.select();',
'      document.execCommand("copy");',
'      document.body.removeChild(ta);',
'      return true;',
'    } catch {',
'      return false;',
'    }',
'  }',
'}',
'',
'export default function ShareMonthClient(props: { month: string }) {',
'  const month = String(props.month || "").trim();',
'  const [data, setData] = useState<AnyObj | null>(null);',
'  const [status, setStatus] = useState<string>("carregando");',
'  const [copied, setCopied] = useState<string>("");',
'',
'  const apiUrl = useMemo(() => "/api/eco/month-close?month=" + encodeURIComponent(month), [month]);',
'  const card34 = useMemo(() => "/api/eco/month-close/card?format=3x4&month=" + encodeURIComponent(month), [month]);',
'  const card11 = useMemo(() => "/api/eco/month-close/card?format=1x1&month=" + encodeURIComponent(month), [month]);',
'',
'  const linkHere = useMemo(() => {',
'    if (typeof window === "undefined") return "";',
'    return window.location.href;',
'  }, [month]);',
'',
'  useEffect(() => {',
'    let alive = true;',
'    (async () => {',
'      setStatus("carregando");',
'      const d = await jget(apiUrl);',
'      if (!alive) return;',
'      setData(d);',
'      setStatus(d && d.ok ? "ok" : "erro");',
'    })();',
'    return () => { alive = false; };',
'  }, [apiUrl]);',
'',
'  const caption = useMemo(() => {',
'    if (!data || !data.ok) {',
'      return "ECO — Transparência do mês " + month + "\\n" +',
'        "Sem dados (ainda).\\n" +',
'        "\\n#ECO — Escutar • Cuidar • Organizar";',
'    }',
'    const summary = (data.item && data.item.summary) ? data.item.summary : {};',
'    const totals = summary.totals || {};',
'    const totalKg = fmtKg(totals.totalKg || 0);',
'    const days = Number(totals.days || 0) || 0;',
'    const mats = topMaterials(totals.byMaterialKg || {});',
'    const lines: string[] = [];',
'    lines.push("ECO — Transparência do mês " + month);',
'    lines.push("Total do mês: " + totalKg + " (" + String(days) + " dias fechados)");',
'    if (mats.length) {',
'      lines.push("");',
'      lines.push("Por material (soma do mês):");',
'      for (const m of mats) lines.push("- " + String(m.k).toUpperCase() + ": " + fmtKg(m.v));',
'    }',
'    lines.push("");',
'    lines.push("Recibo é lei. Cuidado é coletivo. Trabalho digno é o centro.");',
'    lines.push("#ECO — Escutar • Cuidar • Organizar");',
'    return lines.join("\\n");',
'  }, [data, month]);',
'',
'  const waLink = useMemo(() => {',
'    const base = "https://wa.me/?text=";',
'    const text = caption + (linkHere ? ("\\n\\n" + linkHere) : "");',
'    return base + encodeURIComponent(text);',
'  }, [caption, linkHere]);',
'',
'  async function doCopyCaption() {',
'    const ok = await copyText(caption);',
'    setCopied(ok ? "Legenda copiada!" : "Falhou ao copiar");',
'    setTimeout(() => setCopied(""), 1600);',
'  }',
'',
'  async function doCopyLink() {',
'    const ok = await copyText(linkHere || "");',
'    setCopied(ok ? "Link copiado!" : "Falhou ao copiar");',
'    setTimeout(() => setCopied(""), 1600);',
'  }',
'',
'  return (',
'    <section style={{ display: "grid", gap: 12, maxWidth: 1100 }}>',
'      <div style={{ display: "flex", gap: 10, alignItems: "center", flexWrap: "wrap" }}>',
'        <a href="/eco/transparencia" style={{ textDecoration: "none" }}>← voltar</a>',
'        <div style={{ opacity: 0.8 }}>status: {status}</div>',
'        {copied ? <div style={{ padding: "6px 10px", border: "1px solid #ddd", borderRadius: 10 }}>{copied}</div> : null}',
'      </div>',
'',
'      <div style={{ display: "flex", gap: 10, flexWrap: "wrap" }}>',
'        <a href={card34} target="_blank" rel="noreferrer" style={{ padding: "8px 10px", borderRadius: 10, border: "1px solid #111", background: "#F7D500", color: "#111", fontWeight: 800, textDecoration: "none" }}>Abrir Card 3:4</a>',
'        <a href={card11} target="_blank" rel="noreferrer" style={{ padding: "8px 10px", borderRadius: 10, border: "1px solid #111", background: "#F7D500", color: "#111", fontWeight: 800, textDecoration: "none" }}>Abrir Card 1:1</a>',
'        <button onClick={doCopyCaption} style={{ padding: "8px 10px", borderRadius: 10, border: "1px solid #111" }}>Copiar legenda</button>',
'        <button onClick={doCopyLink} style={{ padding: "8px 10px", borderRadius: 10, border: "1px solid #111" }}>Copiar link</button>',
'        <a href={waLink} target="_blank" rel="noreferrer" style={{ padding: "8px 10px", borderRadius: 10, border: "1px solid #111", textDecoration: "none", color: "#111" }}>WhatsApp</a>',
'      </div>',
'',
'      <div style={{ display: "grid", gap: 12, gridTemplateColumns: "1fr 1fr" }}>',
'        <div>',
'          <h2 style={{ margin: "0 0 8px 0" }}>Preview 3:4</h2>',
'          <div style={{ border: "1px solid #ddd", borderRadius: 12, padding: 10, overflow: "hidden" }}>',
'            <img src={card34} alt="Card 3:4" style={{ width: "100%", height: "auto", display: "block" }} />',
'          </div>',
'        </div>',
'        <div>',
'          <h2 style={{ margin: "0 0 8px 0" }}>Preview 1:1</h2>',
'          <div style={{ border: "1px solid #ddd", borderRadius: 12, padding: 10, overflow: "hidden" }}>',
'            <img src={card11} alt="Card 1:1" style={{ width: "100%", height: "auto", display: "block" }} />',
'          </div>',
'        </div>',
'      </div>',
'',
'      <div>',
'        <h2 style={{ margin: "0 0 8px 0" }}>Legenda</h2>',
'        <textarea readOnly value={caption} style={{ width: "100%", minHeight: 220, padding: 12, border: "1px solid #ddd", borderRadius: 12, fontFamily: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace" }} />',
'      </div>',
'',
'      <div>',
'        <h2 style={{ margin: "0 0 8px 0" }}>Debug</h2>',
'        <pre style={{ whiteSpace: "pre-wrap", wordBreak: "break-word", padding: 12, border: "1px solid #ddd", borderRadius: 12 }}>',
'          {data ? JSON.stringify(data, null, 2) : "—"}',
'        </pre>',
'      </div>',
'    </section>',
'  );',
'}',
''
)
EnsureDir (Split-Path -Parent $monClient)
[System.IO.File]::WriteAllLines($monClient, $LMonClient, $enc)
Write-Host "[PATCH] wrote src/app/eco/share/mes/[month]/ShareMonthClient.tsx"

# ---------------- rewrite FechamentoClient: add "Abrir Share" ----------------
$LFech = @(
'"use client";',
'',
'import { useEffect, useMemo, useState } from "react";',
'',
'type AnyObj = Record<string, any>;',
'',
'function brDayToday(): string {',
'  try {',
'    const parts = new Intl.DateTimeFormat("en-CA", { timeZone: "America/Sao_Paulo", year: "numeric", month: "2-digit", day: "2-digit" }).formatToParts(new Date());',
'    const y = parts.find(p => p.type === "year")?.value || "";',
'    const m = parts.find(p => p.type === "month")?.value || "";',
'    const d = parts.find(p => p.type === "day")?.value || "";',
'    if (y && m && d) return y + "-" + m + "-" + d;',
'  } catch {}',
'  const dt = new Date();',
'  const y = String(dt.getFullYear());',
'  const m = String(dt.getMonth() + 1).padStart(2, "0");',
'  const d = String(dt.getDate()).padStart(2, "0");',
'  return y + "-" + m + "-" + d;',
'}',
'',
'async function jget(url: string): Promise<AnyObj> {',
'  const res = await fetch(url, { headers: { Accept: "application/json" }, cache: "no-store" });',
'  const data = await res.json().catch(() => ({}));',
'  if (!res.ok) return { ok: false, status: res.status, ...data };',
'  return data;',
'}',
'',
'export default function FechamentoClient() {',
'  const [day, setDay] = useState<string>(brDayToday());',
'  const [busy, setBusy] = useState(false);',
'  const [result, setResult] = useState<AnyObj | null>(null);',
'  const [history, setHistory] = useState<AnyObj | null>(null);',
'',
'  const dayCloseUrl = useMemo(() => "/api/eco/day-close?day=" + encodeURIComponent(day), [day]);',
'  const card34 = useMemo(() => "/api/eco/day-close/card?format=3x4&day=" + encodeURIComponent(day), [day]);',
'  const card11 = useMemo(() => "/api/eco/day-close/card?format=1x1&day=" + encodeURIComponent(day), [day]);',
'  const shareDay = useMemo(() => "/eco/share/dia/" + encodeURIComponent(day), [day]);',
'',
'  async function loadHistory() {',
'    const data = await jget("/api/eco/day-close/list?limit=30");',
'    setHistory(data);',
'  }',
'',
'  async function doClose(fresh: boolean) {',
'    setBusy(true);',
'    try {',
'      const url = dayCloseUrl + (fresh ? "&fresh=1" : "");',
'      const data = await jget(url);',
'      setResult(data);',
'      await loadHistory();',
'    } finally {',
'      setBusy(false);',
'    }',
'  }',
'',
'  useEffect(() => {',
'    loadHistory();',
'    // eslint-disable-next-line react-hooks/exhaustive-deps',
'  }, []);',
'',
'  return (',
'    <section style={{ display: "grid", gap: 12, maxWidth: 980 }}>',
'      <div style={{ display: "flex", gap: 10, alignItems: "center", flexWrap: "wrap" }}>',
'        <label style={{ display: "flex", gap: 8, alignItems: "center" }}>',
'          <span>Dia:</span>',
'          <input',
'            value={day}',
'            onChange={(e) => setDay(e.target.value)}',
'            placeholder="YYYY-MM-DD"',
'            style={{ padding: "6px 8px", border: "1px solid #ccc", borderRadius: 6, minWidth: 150 }}',
'          />',
'        </label>',
'',
'        <button onClick={() => doClose(false)} disabled={busy} style={{ padding: "8px 10px", borderRadius: 8, border: "1px solid #111", cursor: busy ? "not-allowed" : "pointer" }}>',
'          Fechar / Buscar cache',
'        </button>',
'',
'        <button onClick={() => doClose(true)} disabled={busy} style={{ padding: "8px 10px", borderRadius: 8, border: "1px solid #111", cursor: busy ? "not-allowed" : "pointer" }}>',
'          Recalcular (fresh=1)',
'        </button>',
'',
'        <button onClick={() => loadHistory()} disabled={busy} style={{ padding: "8px 10px", borderRadius: 8, border: "1px solid #111", cursor: busy ? "not-allowed" : "pointer" }}>',
'          Atualizar histórico',
'        </button>',
'',
'        <a href={shareDay} style={{ padding: "8px 10px", borderRadius: 8, border: "1px solid #111", textDecoration: "none", color: "#111", background: "#E0E0E0", fontWeight: 800 }}>',
'          Abrir Share',
'        </a>',
'',
'        <a href={card34} target="_blank" rel="noreferrer" style={{ padding: "8px 10px", borderRadius: 8, border: "1px solid #111", textDecoration: "none", color: "#111", background: "#F7D500", fontWeight: 800 }}>',
'          Abrir Card 3:4',
'        </a>',
'',
'        <a href={card11} target="_blank" rel="noreferrer" style={{ padding: "8px 10px", borderRadius: 8, border: "1px solid #111", textDecoration: "none", color: "#111", background: "#F7D500", fontWeight: 800 }}>',
'          Abrir Card 1:1',
'        </a>',
'      </div>',
'',
'      <div style={{ display: "grid", gap: 12, gridTemplateColumns: "1fr 1fr" }}>',
'        <div>',
'          <h2 style={{ margin: "0 0 8px 0" }}>Resultado</h2>',
'          <pre style={{ whiteSpace: "pre-wrap", wordBreak: "break-word", padding: 12, border: "1px solid #ddd", borderRadius: 10, minHeight: 160 }}>',
'            {result ? JSON.stringify(result, null, 2) : "—"}',
'          </pre>',
'        </div>',
'        <div>',
'          <h2 style={{ margin: "0 0 8px 0" }}>Histórico (últimos 30)</h2>',
'          <pre style={{ whiteSpace: "pre-wrap", wordBreak: "break-word", padding: 12, border: "1px solid #ddd", borderRadius: 10, minHeight: 160 }}>',
'            {history ? JSON.stringify(history, null, 2) : "—"}',
'          </pre>',
'        </div>',
'      </div>',
'    </section>',
'  );',
'}',
''
)
EnsureDir (Split-Path -Parent $fechClient)
[System.IO.File]::WriteAllLines($fechClient, $LFech, $enc)
Write-Host "[PATCH] rewrote src/app/eco/fechamento/FechamentoClient.tsx"

# ---------------- rewrite TransparenciaClient: add "Abrir Share" ----------------
$LTran = @(
'"use client";',
'',
'import { useEffect, useMemo, useState } from "react";',
'',
'type AnyObj = Record<string, any>;',
'',
'function brMonthNow(): string {',
'  try {',
'    const parts = new Intl.DateTimeFormat("en-CA", { timeZone: "America/Sao_Paulo", year: "numeric", month: "2-digit" }).formatToParts(new Date());',
'    const y = parts.find(p => p.type === "year")?.value || "";',
'    const m = parts.find(p => p.type === "month")?.value || "";',
'    if (y && m) return y + "-" + m;',
'  } catch {}',
'  const dt = new Date();',
'  const y = String(dt.getFullYear());',
'  const m = String(dt.getMonth() + 1).padStart(2, "0");',
'  return y + "-" + m;',
'}',
'',
'async function jget(url: string): Promise<AnyObj> {',
'  const res = await fetch(url, { headers: { Accept: "application/json" }, cache: "no-store" });',
'  const data = await res.json().catch(() => ({}));',
'  if (!res.ok) return { ok: false, status: res.status, ...data };',
'  return data;',
'}',
'',
'export default function TransparenciaClient() {',
'  const [month, setMonth] = useState<string>(brMonthNow());',
'  const [busy, setBusy] = useState(false);',
'  const [result, setResult] = useState<AnyObj | null>(null);',
'  const [history, setHistory] = useState<AnyObj | null>(null);',
'',
'  const closeUrl = useMemo(() => "/api/eco/month-close?month=" + encodeURIComponent(month), [month]);',
'  const card34 = useMemo(() => "/api/eco/month-close/card?format=3x4&month=" + encodeURIComponent(month), [month]);',
'  const card11 = useMemo(() => "/api/eco/month-close/card?format=1x1&month=" + encodeURIComponent(month), [month]);',
'  const shareMonth = useMemo(() => "/eco/share/mes/" + encodeURIComponent(month), [month]);',
'',
'  async function loadHistory() {',
'    const data = await jget("/api/eco/month-close/list?limit=24");',
'    setHistory(data);',
'  }',
'',
'  async function doClose(fresh: boolean) {',
'    setBusy(true);',
'    try {',
'      const url = closeUrl + (fresh ? "&fresh=1" : "");',
'      const data = await jget(url);',
'      setResult(data);',
'      await loadHistory();',
'    } finally {',
'      setBusy(false);',
'    }',
'  }',
'',
'  useEffect(() => {',
'    loadHistory();',
'    // eslint-disable-next-line react-hooks/exhaustive-deps',
'  }, []);',
'',
'  return (',
'    <section style={{ display: "grid", gap: 12, maxWidth: 980 }}>',
'      <div style={{ display: "flex", gap: 10, alignItems: "center", flexWrap: "wrap" }}>',
'        <label style={{ display: "flex", gap: 8, alignItems: "center" }}>',
'          <span>Mês:</span>',
'          <input',
'            value={month}',
'            onChange={(e) => setMonth(e.target.value)}',
'            placeholder="YYYY-MM"',
'            style={{ padding: "6px 8px", border: "1px solid #ccc", borderRadius: 6, minWidth: 140 }}',
'          />',
'        </label>',
'',
'        <button onClick={() => doClose(false)} disabled={busy} style={{ padding: "8px 10px", borderRadius: 8, border: "1px solid #111", cursor: busy ? "not-allowed" : "pointer" }}>',
'          Fechar / Buscar cache',
'        </button>',
'',
'        <button onClick={() => doClose(true)} disabled={busy} style={{ padding: "8px 10px", borderRadius: 8, border: "1px solid #111", cursor: busy ? "not-allowed" : "pointer" }}>',
'          Recalcular (fresh=1)',
'        </button>',
'',
'        <button onClick={() => loadHistory()} disabled={busy} style={{ padding: "8px 10px", borderRadius: 8, border: "1px solid #111", cursor: busy ? "not-allowed" : "pointer" }}>',
'          Atualizar histórico',
'        </button>',
'',
'        <a href={shareMonth} style={{ padding: "8px 10px", borderRadius: 8, border: "1px solid #111", textDecoration: "none", color: "#111", background: "#E0E0E0", fontWeight: 800 }}>',
'          Abrir Share',
'        </a>',
'',
'        <a href={card34} target="_blank" rel="noreferrer" style={{ padding: "8px 10px", borderRadius: 8, border: "1px solid #111", textDecoration: "none", color: "#111", background: "#F7D500", fontWeight: 800 }}>',
'          Abrir Card 3:4',
'        </a>',
'',
'        <a href={card11} target="_blank" rel="noreferrer" style={{ padding: "8px 10px", borderRadius: 8, border: "1px solid #111", textDecoration: "none", color: "#111", background: "#F7D500", fontWeight: 800 }}>',
'          Abrir Card 1:1',
'        </a>',
'      </div>',
'',
'      <div style={{ display: "grid", gap: 12, gridTemplateColumns: "1fr 1fr" }}>',
'        <div>',
'          <h2 style={{ margin: "0 0 8px 0" }}>Resultado</h2>',
'          <pre style={{ whiteSpace: "pre-wrap", wordBreak: "break-word", padding: 12, border: "1px solid #ddd", borderRadius: 10, minHeight: 160 }}>',
'            {result ? JSON.stringify(result, null, 2) : "—"}',
'          </pre>',
'        </div>',
'        <div>',
'          <h2 style={{ margin: "0 0 8px 0" }}>Histórico (últimos 24)</h2>',
'          <pre style={{ whiteSpace: "pre-wrap", wordBreak: "break-word", padding: 12, border: "1px solid #ddd", borderRadius: 10, minHeight: 160 }}>',
'            {history ? JSON.stringify(history, null, 2) : "—"}',
'          </pre>',
'        </div>',
'      </div>',
'    </section>',
'  );',
'}',
''
)
EnsureDir (Split-Path -Parent $tranClient)
[System.IO.File]::WriteAllLines($tranClient, $LTran, $enc)
Write-Host "[PATCH] rewrote src/app/eco/transparencia/TransparenciaClient.tsx"

# ---------------- report ----------------
$rep = Join-Path $reportDir ("eco-step-58-share-pack-v0_1-" + $ts + ".md")
$repLines = @(
"# eco-step-58-share-pack-v0_1",
"",
"- Time: " + $ts,
"- Backup: " + $backupDir,
"",
"## Added",
"- /eco/share (hub)",
"- /eco/share/dia/[day] (preview + legenda + copiar + WhatsApp)",
"- /eco/share/mes/[month] (preview + legenda + copiar + WhatsApp)",
"",
"## Updated",
"- /eco/fechamento: botão Abrir Share",
"- /eco/transparencia: botão Abrir Share",
"",
"## Verify",
"- http://localhost:3000/eco/share",
"- http://localhost:3000/eco/share/dia/2025-12-27",
"- http://localhost:3000/eco/share/mes/2025-12",
""
)
[System.IO.File]::WriteAllLines($rep, $repLines, $enc)
Write-Host ("[REPORT] " + $rep)

Write-Host ""
Write-Host "[VERIFY] Reinicie o dev server (Ctrl+C, npm run dev) e abra /eco/fechamento e /eco/transparencia → 'Abrir Share'."