param(
  [string]$Root = (Get-Location).Path
)

$ErrorActionPreference = "Stop"

# --- bootstrap (best effort)
$bootstrap = Join-Path $Root "tools\_bootstrap.ps1"
if (Test-Path $bootstrap) { . $bootstrap }

# --- fallbacks (se bootstrap não carregou)
if (-not (Get-Command EnsureDir -ErrorAction SilentlyContinue)) {
  function EnsureDir([string]$p) { New-Item -ItemType Directory -Force -Path $p | Out-Null }
}
if (-not (Get-Command WriteUtf8NoBom -ErrorAction SilentlyContinue)) {
  function WriteUtf8NoBom([string]$path, [string]$content) {
    $enc = New-Object System.Text.UTF8Encoding($false)
    EnsureDir (Split-Path -Parent $path)
    [System.IO.File]::WriteAllText($path, $content, $enc)
  }
}
if (-not (Get-Command BackupFile -ErrorAction SilentlyContinue)) {
  function BackupFile([string]$path, [string]$backupDir) {
    EnsureDir $backupDir
    if (Test-Path $path) {
      $rel = $path.Replace((Join-Path $Root ""), "")
      $rel = $rel.TrimStart("\","/")
      $dest = Join-Path $backupDir $rel
      EnsureDir (Split-Path -Parent $dest)
      Copy-Item -Force $path $dest
    }
  }
}

function MustExist($p, $label) { if (-not (Test-Path $p)) { throw ("[STOP] não achei " + $label + ": " + $p) } }

$stamp = Get-Date -Format "yyyyMMdd-HHmmss"
$me = "eco-step-113h-add-point-actions-optimistic-safe-v0_1"
Write-Host ("== " + $me + " == " + $stamp)
Write-Host ("[DIAG] Root: " + $Root)

$backupDir = Join-Path $Root ("tools\_patch_backup\" + $stamp + "-" + $me)
EnsureDir $backupDir

# -------------------------
# PATHS
# -------------------------
$apiAction = Join-Path $Root "src\app\api\eco\points\action\route.ts"
$compActions = Join-Path $Root "src\app\eco\mural\_components\MuralPointActionsClient.tsx"
$muralClient = Join-Path $Root "src\app\eco\mural\MuralClient.tsx"
$muralAcoesClient = Join-Path $Root "src\app\eco\mural-acoes\MuralAcoesClient.tsx"
$muralPage = Join-Path $Root "src\app\eco\mural\page.tsx"

MustExist (Join-Path $Root "src") "src/"

# -------------------------
# PATCH A: API /api/eco/points/action (POST)
# -------------------------
EnsureDir (Split-Path -Parent $apiAction)
BackupFile $apiAction $backupDir

$api = @()
$api += '// AUTO-GENERATED by tools/eco-step-113h-add-point-actions-optimistic-safe-v0_1.ps1'
$api += '// POST /api/eco/points/action { pointId, action: confirm|support|replicar, actor?, note? }'
$api += '// Robust: descobre delegates/campos obrigatórios via Prisma.dmmf e preenche required sem quebrar'
$api += ''
$api += 'import { NextResponse } from "next/server";'
$api += 'import { prisma } from "@/lib/prisma";'
$api += 'import { Prisma } from "@prisma/client";'
$api += ''
$api += 'export const runtime = "nodejs";'
$api += 'export const dynamic = "force-dynamic";'
$api += ''
$api += 'function toDelegate(name: string) { return name && name.length ? name.slice(0, 1).toLowerCase() + name.slice(1) : name; }'
$api += 'function getDmmf(): any { return (Prisma as any).dmmf as any; }'
$api += 'function getModels(): any[] { const d = getDmmf(); return d && d.datamodel && Array.isArray(d.datamodel.models) ? d.datamodel.models : []; }'
$api += 'function getEnums(): any[] { const d = getDmmf(); return d && d.datamodel && Array.isArray(d.datamodel.enums) ? d.datamodel.enums : []; }'
$api += 'function enumFirst(enumName: string): string | null { const e = getEnums().find((x: any) => x && x.name === enumName); const v = e && Array.isArray(e.values) && e.values.length ? e.values[0].name : null; return v || null; }'
$api += 'function findModelByDelegate(delegateKey: string): any | null { return getModels().find((m: any) => m && toDelegate(m.name) === delegateKey) || null; }'
$api += 'function findModelByName(modelName: string): any | null { return getModels().find((m: any) => m && m.name === modelName) || null; }'
$api += 'function hasField(modelName: string, fieldName: string): boolean { const m = findModelByName(modelName); return !!(m && Array.isArray(m.fields) && m.fields.some((f: any) => f && f.name === fieldName)); }'
$api += 'function pickDelegate(pc: any, candidates: string[]): string | null { for (const c of candidates) { if (pc && pc[c]) return c; } return null; }'
$api += 'function randId(prefix: string) { return prefix + "-" + Math.random().toString(36).slice(2, 8) + "-" + Date.now().toString(36); }'
$api += ''
$api += 'function findFkField(modelName: string, targetModelName: string): string | null {'
$api += '  const m = findModelByName(modelName);'
$api += '  if (!m || !Array.isArray(m.fields)) return null;'
$api += '  for (const f of m.fields) {'
$api += '    if (f && f.kind === "object" && f.type === targetModelName) {'
$api += '      const rff = (f as any).relationFromFields;'
$api += '      if (Array.isArray(rff) && rff.length) return rff[0];'
$api += '    }'
$api += '  }'
$api += '  const scalar = m.fields.find((f: any) => f && (f.kind === "scalar" || f.kind === "enum") && /pointId/i.test(f.name));'
$api += '  return scalar ? scalar.name : null;'
$api += '}'
$api += ''
$api += 'function buildRequiredData(modelName: string, base: Record<string, any>, ctx: any): any {'
$api += '  const m = findModelByName(modelName);'
$api += '  const out: any = {};'
$api += '  const now = new Date();'
$api += '  const fields = m && Array.isArray(m.fields) ? m.fields : [];'
$api += '  for (const f of fields) {'
$api += '    if (!f) continue;'
$api += '    if (f.isList) continue;'
$api += '    if (f.kind !== "scalar" && f.kind !== "enum") continue;'
$api += '    if (!f.isRequired) continue;'
$api += '    if (f.hasDefaultValue) continue;'
$api += '    if (base && base[f.name] !== undefined) continue;'
$api += ''
$api += '    if (f.name === "id") { out[f.name] = randId("id"); continue; }'
$api += '    if (f.name === "createdAt" || f.name === "updatedAt") { out[f.name] = now; continue; }'
$api += '    if (f.name === "actor") { out[f.name] = ctx.actor; continue; }'
$api += '    if (f.name === "note") { out[f.name] = ctx.note; continue; }'
$api += '    if (f.name === "fingerprint") { out[f.name] = ctx.fingerprint; continue; }'
$api += ''
$api += '    if (f.kind === "enum") { out[f.name] = enumFirst(f.type) || ""; continue; }'
$api += '    if (f.type === "String") { out[f.name] = ctx.actor; continue; }'
$api += '    if (f.type === "Int" || f.type === "Float") { out[f.name] = 0; continue; }'
$api += '    if (f.type === "Boolean") { out[f.name] = false; continue; }'
$api += '    if (f.type === "DateTime") { out[f.name] = now; continue; }'
$api += '    out[f.name] = ctx.actor;'
$api += '  }'
$api += '  for (const k of Object.keys(base || {})) out[k] = (base as any)[k];'
$api += '  if (hasField(modelName, "actor") && out["actor"] === undefined) out["actor"] = ctx.actor;'
$api += '  if (hasField(modelName, "note") && out["note"] === undefined) out["note"] = ctx.note;'
$api += '  if (hasField(modelName, "createdAt") && out["createdAt"] === undefined) out["createdAt"] = now;'
$api += '  return out;'
$api += '}'
$api += ''
$api += 'async function countByFk(pc: any, delegateKey: string | null, actionModelName: string | null, pointModelName: string, pointId: string): Promise<number> {'
$api += '  if (!delegateKey || !actionModelName) return 0;'
$api += '  const fk = findFkField(actionModelName, pointModelName);'
$api += '  if (!fk) return 0;'
$api += '  const where: any = {};'
$api += '  where[fk] = pointId;'
$api += '  try { return await pc[delegateKey].count({ where }); } catch { return 0; }'
$api += '}'
$api += ''
$api += 'export async function POST(req: Request) {'
$api += '  try {'
$api += '    const body: any = await req.json().catch(() => ({}));'
$api += '    const pointId = typeof body.pointId === "string" ? body.pointId : "";'
$api += '    const action = typeof body.action === "string" ? body.action : "";'
$api += '    if (!pointId || !action) return NextResponse.json({ ok: false, error: "bad_request" }, { status: 400 });'
$api += '    if (!["confirm","support","replicar"].includes(action)) return NextResponse.json({ ok: false, error: "bad_action" }, { status: 400 });'
$api += ''
$api += '    const ctx = {'
$api += '      actor: (typeof body.actor === "string" && body.actor.trim().length) ? body.actor.trim().slice(0, 80) : "anon",'
$api += '      note: (typeof body.note === "string" && body.note.trim().length) ? body.note.trim().slice(0, 500) : (action === "support" ? "apoio" : ""),'
$api += '      fingerprint: "act-" + Date.now().toString(36) + "-" + Math.random().toString(36).slice(2, 8),'
$api += '    };'
$api += ''
$api += '    const pc: any = prisma as any;'
$api += '    const keys = Object.keys(pc);'
$api += ''
$api += '    const pointKey = pickDelegate(pc, ["ecoCriticalPoint","ecoPoint","ecoCriticalPointV2"]) || (keys.find((k) => /point/i.test(k) && /eco/i.test(k)) || null);'
$api += '    if (!pointKey) return NextResponse.json({ ok: false, error: "point_model_not_found" }, { status: 500 });'
$api += '    const pointModel = findModelByDelegate(pointKey);'
$api += '    if (!pointModel) return NextResponse.json({ ok: false, error: "dmmf_point_model_not_found", pointKey }, { status: 500 });'
$api += ''
$api += '    const confirmKey = pickDelegate(pc, ["ecoCriticalPointConfirm","ecoPointConfirm","ecoCriticalConfirm"]) || (keys.find((k) => /confirm/i.test(k) && /eco/i.test(k)) || null);'
$api += '    const supportKey = pickDelegate(pc, ["ecoPointSupport","ecoCriticalPointSupport"]) || (keys.find((k) => /support/i.test(k) && /eco/i.test(k)) || null);'
$api += '    const replicarKey = pickDelegate(pc, ["ecoPointReplicate","ecoPointReplicar","ecoCriticalPointReplicate"]) || (keys.find((k) => ((/replic/i.test(k)) || (/replicar/i.test(k))) && /eco/i.test(k)) || null);'
$api += ''
$api += '    const chosenKey = action === "confirm" ? confirmKey : (action === "support" ? supportKey : replicarKey);'
$api += '    if (!chosenKey) return NextResponse.json({ ok: false, error: "action_model_not_found", action }, { status: 500 });'
$api += '    const chosenModel = findModelByDelegate(chosenKey);'
$api += '    if (!chosenModel) return NextResponse.json({ ok: false, error: "dmmf_action_model_not_found", chosenKey }, { status: 500 });'
$api += ''
$api += '    // best-effort: checa ponto'
$api += '    try {'
$api += '      const p = await pc[pointKey].findUnique({ where: { id: pointId } });'
$api += '      if (!p) return NextResponse.json({ ok: false, error: "point_not_found" }, { status: 404 });'
$api += '    } catch { }'
$api += ''
$api += '    const fk = findFkField(chosenModel.name, pointModel.name);'
$api += '    if (!fk) return NextResponse.json({ ok: false, error: "fk_not_found", model: chosenModel.name }, { status: 500 });'
$api += ''
$api += '    const base: any = {};'
$api += '    base[fk] = pointId;'
$api += '    if (hasField(chosenModel.name, "id")) base.id = randId(action.slice(0, 1));'
$api += '    if (hasField(chosenModel.name, "actor")) base.actor = ctx.actor;'
$api += '    if (hasField(chosenModel.name, "note")) base.note = ctx.note;'
$api += '    if (hasField(chosenModel.name, "fingerprint")) base.fingerprint = ctx.fingerprint;'
$api += '    if (hasField(chosenModel.name, "createdAt")) base.createdAt = new Date();'
$api += ''
$api += '    const data = buildRequiredData(chosenModel.name, base, ctx);'
$api += '    await pc[chosenKey].create({ data });'
$api += ''
$api += '    const confirmName = confirmKey ? (findModelByDelegate(confirmKey)?.name || null) : null;'
$api += '    const supportName = supportKey ? (findModelByDelegate(supportKey)?.name || null) : null;'
$api += '    const replicarName = replicarKey ? (findModelByDelegate(replicarKey)?.name || null) : null;'
$api += ''
$api += '    const counts = {'
$api += '      confirm: await countByFk(pc, confirmKey, confirmName, pointModel.name, pointId),'
$api += '      support: await countByFk(pc, supportKey, supportName, pointModel.name, pointId),'
$api += '      replicar: await countByFk(pc, replicarKey, replicarName, pointModel.name, pointId),'
$api += '    };'
$api += ''
$api += '    return NextResponse.json({ ok: true, error: null, action, pointId, counts, models: { pointKey, confirmKey, supportKey, replicarKey, chosenKey } });'
$api += '  } catch (e: any) {'
$api += '    const msg = e && e.message ? String(e.message) : String(e);'
$api += '    return NextResponse.json({ ok: false, error: "action_failed", message: msg }, { status: 500 });'
$api += '  }'
$api += '}'
$api += ''

WriteUtf8NoBom $apiAction ($api -join "`n")
Write-Host ("[PATCH] wrote -> " + $apiAction)

# -------------------------
# PATCH B: Client component (UI otimista)
# -------------------------
EnsureDir (Split-Path -Parent $compActions)
BackupFile $compActions $backupDir

$cc = @()
$cc += '"use client";'
$cc += ''
$cc += 'import * as React from "react";'
$cc += ''
$cc += 'type Counts = { confirm?: number; support?: number; replicar?: number };'
$cc += ''
$cc += 'export default function MuralPointActionsClient(props: { pointId: string; initialCounts?: Counts }) {'
$cc += '  const [counts, setCounts] = React.useState<Required<Counts>>({'
$cc += '    confirm: props.initialCounts?.confirm ?? 0,'
$cc += '    support: props.initialCounts?.support ?? 0,'
$cc += '    replicar: props.initialCounts?.replicar ?? 0,'
$cc += '  });'
$cc += '  const [busy, setBusy] = React.useState<string | null>(null);'
$cc += '  const pointId = props.pointId;'
$cc += ''
$cc += '  async function act(action: "confirm" | "support" | "replicar") {'
$cc += '    if (!pointId) return;'
$cc += '    if (busy) return;'
$cc += '    setBusy(action);'
$cc += ''
$cc += '    // optimistic'
$cc += '    setCounts((c) => ({ ...c, [action]: (c as any)[action] + 1 }));'
$cc += ''
$cc += '    try {'
$cc += '      const res = await fetch("/api/eco/points/action", {'
$cc += '        method: "POST",'
$cc += '        headers: { "content-type": "application/json" },'
$cc += '        body: JSON.stringify({ pointId, action }),'
$cc += '      });'
$cc += '      const j = await res.json().catch(() => null);'
$cc += '      if (!res.ok || !j || !j.ok) throw new Error((j && j.error) ? String(j.error) : "request_failed");'
$cc += '      if (j.counts) {'
$cc += '        setCounts({'
$cc += '          confirm: Number(j.counts.confirm || 0),'
$cc += '          support: Number(j.counts.support || 0),'
$cc += '          replicar: Number(j.counts.replicar || 0),'
$cc += '        });'
$cc += '      }'
$cc += '    } catch (e) {'
$cc += '      // rollback best-effort'
$cc += '      setCounts((c) => ({ ...c, [action]: Math.max(0, (c as any)[action] - 1) }));'
$cc += '      console.error(e);'
$cc += '    } finally {'
$cc += '      setBusy(null);'
$cc += '    }'
$cc += '  }'
$cc += ''
$cc += '  const btnStyle: React.CSSProperties = {'
$cc += '    padding: "8px 10px",'
$cc += '    borderRadius: 12,'
$cc += '    border: "1px solid #111",'
$cc += '    background: "#fff",'
$cc += '    fontWeight: 900,'
$cc += '    cursor: "pointer",'
$cc += '    opacity: busy ? 0.7 : 1,'
$cc += '  };'
$cc += ''
$cc += '  return ('
$cc += '    <div style={{ display: "flex", gap: 8, flexWrap: "wrap", marginTop: 10 }}>'
$cc += '      <button type="button" onClick={() => act("confirm")} disabled={!!busy} style={btnStyle}>'
$cc += '        ✅ Confirmar ({counts.confirm})'
$cc += '      </button>'
$cc += '      <button type="button" onClick={() => act("support")} disabled={!!busy} style={btnStyle}>'
$cc += '        🤝 Apoiar ({counts.support})'
$cc += '      </button>'
$cc += '      <button type="button" onClick={() => act("replicar")} disabled={!!busy} style={btnStyle}>'
$cc += '        ♻️ Replicar ({counts.replicar})'
$cc += '      </button>'
$cc += '    </div>'
$cc += '  );'
$cc += '}'
$cc += ''

WriteUtf8NoBom $compActions ($cc -join "`n")
Write-Host ("[PATCH] wrote -> " + $compActions)

# -------------------------
# PATCH C: injetar componente no MuralClient / MuralAcoesClient (best effort)
# -------------------------
function InsertImport([string]$raw, [string]$importLine) {
  if ($raw -match [regex]::Escape($importLine)) { return $raw }
  $lines = $raw -split "`r?`n"
  $lastImport = -1
  for ($i=0; $i -lt $lines.Length; $i++) {
    if ($lines[$i] -match '^\s*import\s') { $lastImport = $i }
  }
  if ($lastImport -ge 0) {
    $out = @()
    for ($i=0; $i -lt $lines.Length; $i++) {
      $out += $lines[$i]
      if ($i -eq $lastImport) { $out += $importLine }
    }
    return ($out -join "`n")
  }
  return ($importLine + "`n" + $raw)
}

function InjectActions([string]$raw) {
  if ($raw -match 'MuralPointActionsClient') { return @{ ok=$false; raw=$raw } }

  $m = [regex]::Match($raw, '\.map\(\(\s*(\w+)')
  $var = "p"
  if ($m.Success) { $var = $m.Groups[1].Value }

  $jsx = "      <MuralPointActionsClient pointId={" + $var + ".id} initialCounts={" + $var + ".counts} />"

  $lines = $raw -split "`r?`n"
  $out = New-Object System.Collections.Generic.List[string]
  $inserted = $false

  foreach ($ln in $lines) {
    $out.Add($ln) | Out-Null

    if (-not $inserted) {
      if ($ln -match '\.counts' -or $ln -match 'counts\.') {
        $out.Add($jsx) | Out-Null
        $inserted = $true
      }
    }
  }

  if (-not $inserted) {
    # fallback: antes do primeiro </article>
    $out2 = New-Object System.Collections.Generic.List[string]
    foreach ($ln in $out) {
      if (-not $inserted -and $ln -match '</article>') {
        $out2.Add($jsx) | Out-Null
        $inserted = $true
      }
      $out2.Add($ln) | Out-Null
    }
    return @{ ok=$inserted; raw=($out2 -join "`n") }
  }

  return @{ ok=$true; raw=($out -join "`n") }
}

$frontPatched = @()

foreach ($f in @($muralClient, $muralAcoesClient)) {
  if (Test-Path $f) {
    $raw = Get-Content -Raw -ErrorAction SilentlyContinue $f
    if ($raw) {
      BackupFile $f $backupDir
      $raw2 = InsertImport $raw 'import MuralPointActionsClient from "./_components/MuralPointActionsClient";'
      $inj = InjectActions $raw2
      if ($inj.ok) {
        WriteUtf8NoBom $f $inj.raw
        $frontPatched += $f
        Write-Host ("[PATCH] injected actions -> " + $f)
      } else {
        Write-Host ("[WARN] não consegui achar ponto seguro pra injetar em: " + $f)
      }
    }
  }
}

# -------------------------
# PATCH D (extra): corrigir <a> dentro de <a> em /eco/mural/page.tsx (se ainda existir)
# -------------------------
if (Test-Path $muralPage) {
  $raw = Get-Content -Raw -ErrorAction SilentlyContinue $muralPage
  if ($raw -and ($raw -match '<a[^>]+href="/eco/mural/chamados"' ) -and ($raw -match '<a[^>]+href="/eco/mural/confirmados"')) {
    if ($raw -match '<a[^>]+href="/eco/mural/chamados"[^>]*>\s*<a[^>]+href="/eco/mural/confirmados"') {
      BackupFile $muralPage $backupDir

      # Best-effort rewrite do bloco (simples e seguro)
      $raw2 = $raw
      $raw2 = $raw2 -replace '<a\s+href="/eco/mural/chamados"([^>]*)>\s*<a\s+href="/eco/mural/confirmados"([^>]*)>([\s\S]*?)</a>\s*([^<]*?)</a>',
        '<div style={{ padding: "9px 10px", borderRadius: 12, border: "1px solid #111", background: "#fff", display: "flex", gap: 8, flexWrap: "wrap" }}>' +
        '<a href="/eco/mural/chamados" style={{ textDecoration: "none", color: "#111", fontWeight: 900 }}>📣 Chamados</a>' +
        '<a href="/eco/mural/confirmados" style={{ textDecoration: "none", color: "#111", fontWeight: 900 }}>✅ Confirmados</a>' +
        '</div>'

      WriteUtf8NoBom $muralPage $raw2
      Write-Host ("[PATCH] fixed nested <a> -> " + $muralPage)
    }
  }
}

# -------------------------
# REPORT
# -------------------------
$report = @()
$report += "# $me"
$report += ""
$report += "- Time: $stamp"
$report += "- Backup: $backupDir"
$report += ""
$report += "## What/Why"
$report += "- Criado POST /api/eco/points/action (confirm/support/replicar) robusto com Prisma.dmmf."
$report += "- Criado componente client com UI otimista + rollback."
$report += "- Tentativa de injetar o componente no MuralClient/MuralAcoesClient."
$report += ""
$report += "## Patched"
$report += "- src/app/api/eco/points/action/route.ts"
$report += "- src/app/eco/mural/_components/MuralPointActionsClient.tsx"
if ($frontPatched.Count -gt 0) {
  $report += "- Front injected:"
  foreach ($x in $frontPatched) { $report += "  - $x" }
} else {
  $report += "- Front injected: (nenhum) — se aparecer WARN, a gente injeta manualmente no arquivo certo."
}
$report += ""
$report += "## Verify"
$report += "1) Ctrl+C -> npm run dev"
$report += "2) abrir /eco/mural e clicar ✅ 🤝 ♻️ (contadores devem subir)"
$report += "3) teste API:"
$report += '   $b = @{ pointId = "PONHA_UM_ID"; action = "confirm" } | ConvertTo-Json -Compress'
$report += '   irm "http://localhost:3000/api/eco/points/action" -Method Post -ContentType "application/json" -Body $b | ConvertTo-Json -Depth 60'
$report += ""

$reportPath = Join-Path $Root ("reports\" + $me + "-" + $stamp + ".md")
EnsureDir (Split-Path -Parent $reportPath)
WriteUtf8NoBom $reportPath ($report -join "`n")
Write-Host ("[REPORT] " + $reportPath)

Write-Host ""
Write-Host "[VERIFY] rode:"
Write-Host "  Ctrl+C -> npm run dev"
Write-Host "  abrir /eco/mural e clicar ✅ 🤝 ♻️"
Write-Host '  $b = @{ pointId = "PONHA_UM_ID"; action = "confirm" } | ConvertTo-Json -Compress'
Write-Host '  irm "http://localhost:3000/api/eco/points/action" -Method Post -ContentType "application/json" -Body $b | ConvertTo-Json -Depth 60'