param(
  [string]$Root = (Get-Location).Path
)

function EnsureDir([string]$p) { if (-not (Test-Path $p)) { New-Item -ItemType Directory -Force -Path $p | Out-Null } }
function WriteAllLinesUtf8NoBom([string]$p, [string[]]$lines) {
  EnsureDir (Split-Path -Parent $p)
  $enc = New-Object System.Text.UTF8Encoding($false)
  [System.IO.File]::WriteAllLines($p, $lines, $enc)
}
function BackupFile([string]$p, [string]$backupDir) {
  if (Test-Path $p) {
    $rel = $p.Substring($Root.Length).TrimStart('\','/')
    $dest = Join-Path $backupDir ($rel -replace '[\\/]', '__')
    Copy-Item -Force -LiteralPath $p -Destination $dest
    Write-Host ('[BK] ' + $rel + ' -> ' + (Split-Path -Leaf $dest))
  }
}

$ts = Get-Date -Format 'yyyyMMdd-HHmmss'
$backupDir = Join-Path $Root ('tools/_patch_backup/' + $ts + '-eco-step-63-mutirao-finish-share-card-v0_1')
$reportDir = Join-Path $Root 'reports'
EnsureDir $backupDir
EnsureDir $reportDir

Write-Host ('== eco-step-63-mutirao-finish-share-card-v0_1 == ' + $ts)
Write-Host ('[DIAG] Root: ' + $Root)

$mutListClient = Join-Path $Root 'src/app/eco/mutiroes/MutiroesClient.tsx'

$apiGet    = Join-Path $Root 'src/app/api/eco/mutirao/get/route.ts'
$apiUpdate = Join-Path $Root 'src/app/api/eco/mutirao/update/route.ts'
$apiFinish = Join-Path $Root 'src/app/api/eco/mutirao/finish/route.ts'
$apiCard   = Join-Path $Root 'src/app/api/eco/mutirao/card/route.tsx'

$pageDetail  = Join-Path $Root 'src/app/eco/mutiroes/[id]/page.tsx'
$clientDetail= Join-Path $Root 'src/app/eco/mutiroes/[id]/MutiraoDetailClient.tsx'

$pageShare   = Join-Path $Root 'src/app/eco/share/mutirao/[id]/page.tsx'
$clientShare = Join-Path $Root 'src/app/eco/share/mutirao/[id]/ShareMutiraoClient.tsx'

Write-Host ('[DIAG] Will patch: ' + $mutListClient)
Write-Host ('[DIAG] Will write: ' + $apiGet)
Write-Host ('[DIAG] Will write: ' + $apiUpdate)
Write-Host ('[DIAG] Will write: ' + $apiFinish)
Write-Host ('[DIAG] Will write: ' + $apiCard)
Write-Host ('[DIAG] Will write: ' + $pageDetail)
Write-Host ('[DIAG] Will write: ' + $clientDetail)
Write-Host ('[DIAG] Will write: ' + $pageShare)
Write-Host ('[DIAG] Will write: ' + $clientShare)

BackupFile $mutListClient $backupDir
BackupFile $apiGet $backupDir
BackupFile $apiUpdate $backupDir
BackupFile $apiFinish $backupDir
BackupFile $apiCard $backupDir
BackupFile $pageDetail $backupDir
BackupFile $clientDetail $backupDir
BackupFile $pageShare $backupDir
BackupFile $clientShare $backupDir

# --- API: get
$LGet = @(
'import { NextResponse } from "next/server";',
'import { prisma } from "@/lib/prisma";',
'',
'export const runtime = "nodejs";',
'export const dynamic = "force-dynamic";',
'',
'function asMsg(e: unknown) {',
'  if (e instanceof Error) return e.message;',
'  try { return String(e); } catch { return "unknown"; }',
'}',
'function looksLikeMissingTable(msg: string) {',
'  const m = msg.toLowerCase();',
'  return m.includes("does not exist") || m.includes("no such table") || m.includes("p2021");',
'}',
'function getMutiraoModel() { const pc: any = prisma as any; return pc?.ecoMutirao; }',
'',
'export async function GET(req: Request) {',
'  const { searchParams } = new URL(req.url);',
'  const id = String(searchParams.get("id") || "").trim();',
'  if (!id) return NextResponse.json({ ok: false, error: "bad_id" }, { status: 400 });',
'',
'  const m = getMutiraoModel();',
'  if (!m?.findUnique) return NextResponse.json({ ok: false, error: "model_not_ready" }, { status: 503 });',
'',
'  try {',
'    const item = await m.findUnique({ where: { id }, include: { point: true } });',
'    if (!item) return NextResponse.json({ ok: false, error: "not_found" }, { status: 404 });',
'    return NextResponse.json({ ok: true, item });',
'  } catch (e) {',
'    const msg = asMsg(e);',
'    if (looksLikeMissingTable(msg)) return NextResponse.json({ ok: false, error: "db_not_ready", detail: msg }, { status: 503 });',
'    return NextResponse.json({ ok: false, error: "db_error", detail: msg }, { status: 500 });',
'  }',
'}',
''
)
WriteAllLinesUtf8NoBom $apiGet $LGet
Write-Host '[PATCH] wrote src/app/api/eco/mutirao/get/route.ts'

# --- API: update (rascunho)
$LUpdate = @(
'import { NextResponse } from "next/server";',
'import { prisma } from "@/lib/prisma";',
'',
'export const runtime = "nodejs";',
'export const dynamic = "force-dynamic";',
'',
'function asMsg(e: unknown) {',
'  if (e instanceof Error) return e.message;',
'  try { return String(e); } catch { return "unknown"; }',
'}',
'function looksLikeMissingTable(msg: string) {',
'  const m = msg.toLowerCase();',
'  return m.includes("does not exist") || m.includes("no such table") || m.includes("p2021");',
'}',
'function getMutiraoModel() { const pc: any = prisma as any; return pc?.ecoMutirao; }',
'',
'function cleanUrl(v: any) {',
'  const s = String(v || "").trim();',
'  if (!s) return null;',
'  // aceita http(s) e data: (pra casos especiais)',
'  if (s.startsWith("http://") || s.startsWith("https://") || s.startsWith("data:")) return s.slice(0, 2000);',
'  return null;',
'}',
'',
'export async function POST(req: Request) {',
'  const body = (await req.json().catch(() => null)) as any;',
'  const id = String(body?.id || "").trim();',
'  if (!id) return NextResponse.json({ ok: false, error: "bad_id" }, { status: 400 });',
'',
'  const beforeUrl = cleanUrl(body?.beforeUrl);',
'  const afterUrl = cleanUrl(body?.afterUrl);',
'  const checklist = body?.checklist ?? null;',
'  const title = body?.title != null ? String(body.title).slice(0, 120) : undefined;',
'  const note = body?.note != null ? String(body.note).slice(0, 600) : undefined;',
'',
'  const m = getMutiraoModel();',
'  if (!m?.update) return NextResponse.json({ ok: false, error: "model_not_ready" }, { status: 503 });',
'',
'  try {',
'    const data: any = { checklist };',
'    if (beforeUrl !== null) data.beforeUrl = beforeUrl;',
'    if (afterUrl !== null) data.afterUrl = afterUrl;',
'    if (title !== undefined) data.title = title;',
'    if (note !== undefined) data.note = note;',
'',
'    const item = await m.update({ where: { id }, data });',
'    return NextResponse.json({ ok: true, item });',
'  } catch (e) {',
'    const msg = asMsg(e);',
'    if (looksLikeMissingTable(msg)) return NextResponse.json({ ok: false, error: "db_not_ready", detail: msg }, { status: 503 });',
'    return NextResponse.json({ ok: false, error: "db_error", detail: msg }, { status: 500 });',
'  }',
'}',
''
)
WriteAllLinesUtf8NoBom $apiUpdate $LUpdate
Write-Host '[PATCH] wrote src/app/api/eco/mutirao/update/route.ts'

# --- API: finish (DONE)
$LFinish = @(
'import { NextResponse } from "next/server";',
'import { prisma } from "@/lib/prisma";',
'',
'export const runtime = "nodejs";',
'export const dynamic = "force-dynamic";',
'',
'function asMsg(e: unknown) {',
'  if (e instanceof Error) return e.message;',
'  try { return String(e); } catch { return "unknown"; }',
'}',
'function looksLikeMissingTable(msg: string) {',
'  const m = msg.toLowerCase();',
'  return m.includes("does not exist") || m.includes("no such table") || m.includes("p2021");',
'}',
'function getMutiraoModel() { const pc: any = prisma as any; return pc?.ecoMutirao; }',
'',
'function cleanUrl(v: any) {',
'  const s = String(v || "").trim();',
'  if (!s) return null;',
'  if (s.startsWith("http://") || s.startsWith("https://") || s.startsWith("data:")) return s.slice(0, 2000);',
'  return null;',
'}',
'',
'export async function POST(req: Request) {',
'  const body = (await req.json().catch(() => null)) as any;',
'  const id = String(body?.id || "").trim();',
'  if (!id) return NextResponse.json({ ok: false, error: "bad_id" }, { status: 400 });',
'',
'  const beforeUrl = cleanUrl(body?.beforeUrl);',
'  const afterUrl = cleanUrl(body?.afterUrl);',
'  const checklist = body?.checklist ?? null;',
'',
'  const m = getMutiraoModel();',
'  if (!m?.update) return NextResponse.json({ ok: false, error: "model_not_ready" }, { status: 503 });',
'',
'  try {',
'    const data: any = { status: "DONE", checklist };',
'    if (beforeUrl !== null) data.beforeUrl = beforeUrl;',
'    if (afterUrl !== null) data.afterUrl = afterUrl;',
'    const item = await m.update({ where: { id }, data });',
'    return NextResponse.json({ ok: true, item });',
'  } catch (e) {',
'    const msg = asMsg(e);',
'    if (looksLikeMissingTable(msg)) return NextResponse.json({ ok: false, error: "db_not_ready", detail: msg }, { status: 503 });',
'    return NextResponse.json({ ok: false, error: "db_error", detail: msg }, { status: 500 });',
'  }',
'}',
''
)
WriteAllLinesUtf8NoBom $apiFinish $LFinish
Write-Host '[PATCH] wrote src/app/api/eco/mutirao/finish/route.ts'

# --- API: card (next/og)
$LCard = @(
'/* eslint-disable @next/next/no-img-element */',
'import { ImageResponse } from "next/og";',
'import { NextResponse } from "next/server";',
'import { prisma } from "@/lib/prisma";',
'',
'export const runtime = "nodejs";',
'export const dynamic = "force-dynamic";',
'',
'function getMutiraoModel() { const pc: any = prisma as any; return pc?.ecoMutirao; }',
'function clampFormat(f: string) { return f === "1x1" ? "1x1" : "3x4"; }',
'function fmtDay(iso: string) {',
'  try {',
'    const d = new Date(iso);',
'    const pad = (n: number) => String(n).padStart(2, "0");',
'    return pad(d.getDate()) + "/" + pad(d.getMonth() + 1) + "/" + d.getFullYear();',
'  } catch { return ""; }',
'}',
'function fmtTime(iso: string) {',
'  try {',
'    const d = new Date(iso);',
'    const pad = (n: number) => String(n).padStart(2, "0");',
'    return pad(d.getHours()) + ":" + pad(d.getMinutes());',
'  } catch { return ""; }',
'}',
'function safe(s: any, max: number) { return String(s || "").slice(0, max); }',
'',
'export async function GET(req: Request) {',
'  const { searchParams } = new URL(req.url);',
'  const id = String(searchParams.get("id") || "").trim();',
'  const format = clampFormat(String(searchParams.get("format") || "3x4"));',
'  if (!id) return NextResponse.json({ ok: false, error: "bad_id" }, { status: 400 });',
'',
'  const m = getMutiraoModel();',
'  if (!m?.findUnique) return NextResponse.json({ ok: false, error: "model_not_ready" }, { status: 503 });',
'',
'  const item = await m.findUnique({ where: { id }, include: { point: true } });',
'  if (!item) return NextResponse.json({ ok: false, error: "not_found" }, { status: 404 });',
'',
'  const W = format === "1x1" ? 1080 : 1080;',
'  const H = format === "1x1" ? 1080 : 1350;',
'',
'  const startIso = item.startAt ? String(item.startAt) : "";',
'  const day = startIso ? fmtDay(startIso) : "";',
'  const time = startIso ? fmtTime(startIso) : "";',
'  const dur = String(item.durationMin || 90);',
'  const st = String(item.status || "SCHEDULED");',
'',
'  const kind = safe(item.point?.kind, 24);',
'  const note = safe(item.point?.note, 140);',
'  const confirm = String(item.point?.confirmCount || 0);',
'',
'  const beforeOk = !!item.beforeUrl;',
'  const afterOk = !!item.afterUrl;',
'',
'  return new ImageResponse(',
'    (',
'      <div style={{ width: W, height: H, background: "#0b0b0b", color: "#F7D500", padding: 56, display: "flex", flexDirection: "column", justifyContent: "space-between" }}>',
'        <div style={{ display: "flex", flexDirection: "column", gap: 14 }}>',
'          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>',
'            <div style={{ fontSize: 34, fontWeight: 900, letterSpacing: 1 }}>ECO — MUTIRÃO</div>',
'            <div style={{ fontSize: 22, fontWeight: 800, padding: "8px 12px", borderRadius: 999, background: st === "DONE" ? "#F7D500" : "#222", color: st === "DONE" ? "#111" : "#F7D500" }}>{st}</div>',
'          </div>',
'          <div style={{ display: "flex", gap: 10, flexWrap: "wrap", alignItems: "center", color: "#fff" }}>',
'            <div style={{ fontSize: 24, fontWeight: 900 }}>{day} {time ? ("• " + time) : ""}</div>',
'            <div style={{ opacity: 0.9, fontSize: 20 }}>⏱ {dur} min</div>',
'            <div style={{ opacity: 0.9, fontSize: 20 }}>✅ conf.: {confirm}</div>',
'          </div>',
'',
'          <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>',
'            <div style={{ fontSize: 22, fontWeight: 900, color: "#F7D500" }}>{kind || "PONTO"}</div>',
'            <div style={{ fontSize: 18, color: "#ddd" }}>{note || "—"}</div>',
'          </div>',
'        </div>',
'',
'        <div style={{ display: "flex", gap: 16 }}>',
'          <div style={{ width: (format === "1x1" ? 470 : 420), height: (format === "1x1" ? 330 : 420), borderRadius: 18, border: "2px dashed #555", background: "#111", display: "flex", alignItems: "center", justifyContent: "center" }}>',
'            <div style={{ display: "flex", flexDirection: "column", gap: 6, alignItems: "center" }}>',
'              <div style={{ fontSize: 20, fontWeight: 900, color: "#F7D500" }}>ANTES</div>',
'              <div style={{ fontSize: 14, color: "#bbb" }}>{beforeOk ? "foto ok" : "sem foto"}</div>',
'            </div>',
'          </div>',
'          <div style={{ width: (format === "1x1" ? 470 : 420), height: (format === "1x1" ? 330 : 420), borderRadius: 18, border: "2px dashed #555", background: "#111", display: "flex", alignItems: "center", justifyContent: "center" }}>',
'            <div style={{ display: "flex", flexDirection: "column", gap: 6, alignItems: "center" }}>',
'              <div style={{ fontSize: 20, fontWeight: 900, color: "#F7D500" }}>DEPOIS</div>',
'              <div style={{ fontSize: 14, color: "#bbb" }}>{afterOk ? "foto ok" : "sem foto"}</div>',
'            </div>',
'          </div>',
'        </div>',
'',
'        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>',
'          <div style={{ fontSize: 16, color: "#bbb" }}>Recibo é lei. Cuidado é coletivo. Trabalho digno é o centro.</div>',
'          <div style={{ fontSize: 16, color: "#bbb" }}>#ECO — Escutar • Cuidar • Organizar</div>',
'        </div>',
'      </div>',
'    ),',
'    { width: W, height: H }',
'  );',
'}',
''
)
WriteAllLinesUtf8NoBom $apiCard $LCard
Write-Host '[PATCH] wrote src/app/api/eco/mutirao/card/route.tsx'

# --- UI: detalhe
$LPageDetail = @(
'import MutiraoDetailClient from "./MutiraoDetailClient";',
'',
'export const dynamic = "force-dynamic";',
'',
'export default async function Page({ params }: { params: Promise<{ id: string }> }) {',
'  const p = await params;',
'  return (',
'    <main style={{ padding: 16, maxWidth: 1100, margin: "0 auto" }}>',
'      <h1 style={{ margin: "0 0 8px 0" }}>Mutirão</h1>',
'      <p style={{ margin: "0 0 14px 0", opacity: 0.85 }}>',
'        Antes/depois + checklist + finalizar. Depois, card pronto para postar.',
'      </p>',
'      <MutiraoDetailClient id={p.id} />',
'    </main>',
'  );',
'}',
''
)
WriteAllLinesUtf8NoBom $pageDetail $LPageDetail
Write-Host '[PATCH] wrote src/app/eco/mutiroes/[id]/page.tsx'

$LDetailClient = @(
'"use client";',
'',
'import { useEffect, useMemo, useState } from "react";',
'',
'type AnyObj = Record<string, any>;',
'',
'async function jget(url: string): Promise<AnyObj> {',
'  const res = await fetch(url, { headers: { Accept: "application/json" }, cache: "no-store" });',
'  const data = await res.json().catch(() => ({}));',
'  if (!res.ok) return { ok: false, status: res.status, ...data };',
'  return data;',
'}',
'async function jpost(url: string, body: AnyObj): Promise<AnyObj> {',
'  const res = await fetch(url, { method: "POST", headers: { "Content-Type": "application/json", Accept: "application/json" }, body: JSON.stringify(body), cache: "no-store" });',
'  const data = await res.json().catch(() => ({}));',
'  if (!res.ok) return { ok: false, status: res.status, ...data };',
'  return data;',
'}',
'',
'function chkDefault() {',
'  return {',
'    luvas: false,',
'    sacos: false,',
'    agua: false,',
'    separacao: false,',
'    destino: false,',
'    aviso_vizinhos: false,',
'  };',
'}',
'',
'export default function MutiraoDetailClient({ id }: { id: string }) {',
'  const [status, setStatus] = useState<string>("carregando");',
'  const [item, setItem] = useState<AnyObj | null>(null);',
'  const [msg, setMsg] = useState<string>("");',
'',
'  const [beforeUrl, setBeforeUrl] = useState<string>("");',
'  const [afterUrl, setAfterUrl] = useState<string>("");',
'  const [check, setCheck] = useState<AnyObj>(chkDefault());',
'',
'  const card3x4 = useMemo(() => "/api/eco/mutirao/card?format=3x4&id=" + encodeURIComponent(id), [id]);',
'  const shareUrl = useMemo(() => "/eco/share/mutirao/" + encodeURIComponent(id), [id]);',
'',
'  async function refresh() {',
'    setStatus("carregando");',
'    setMsg("");',
'    const d = await jget("/api/eco/mutirao/get?id=" + encodeURIComponent(id));',
'    if (d && d.ok && d.item) {',
'      setItem(d.item);',
'      setBeforeUrl(String(d.item.beforeUrl || ""));',
'      setAfterUrl(String(d.item.afterUrl || ""));',
'      setCheck(d.item.checklist && typeof d.item.checklist === "object" ? d.item.checklist : chkDefault());',
'      setStatus("ok");',
'    } else {',
'      setItem(null);',
'      setStatus("erro");',
'      setMsg("Erro: " + String(d?.error || d?.detail || "unknown"));',
'    }',
'  }',
'',
'  useEffect(() => { refresh(); }, [id]);',
'',
'  function toggle(k: string) {',
'    setCheck((prev: AnyObj) => ({ ...prev, [k]: !prev?.[k] }));',
'  }',
'',
'  async function saveDraft() {',
'    setMsg("");',
'    const d = await jpost("/api/eco/mutirao/update", { id, beforeUrl, afterUrl, checklist: check });',
'    if (d && d.ok) { setMsg("Rascunho salvo."); await refresh(); }',
'    else setMsg("Erro: " + String(d?.error || d?.detail || "unknown"));',
'  }',
'',
'  async function finish() {',
'    setMsg("");',
'    const d = await jpost("/api/eco/mutirao/finish", { id, beforeUrl, afterUrl, checklist: check });',
'    if (d && d.ok) { setMsg("Mutirão finalizado (DONE)."); await refresh(); }',
'    else setMsg("Erro: " + String(d?.error || d?.detail || "unknown"));',
'  }',
'',
'  const p = item?.point || {};',
'',
'  return (',
'    <section style={{ display: "grid", gap: 12 }}>',
'      <div style={{ display: "flex", gap: 10, flexWrap: "wrap", alignItems: "center" }}>',
'        <a href="/eco/mutiroes" style={{ textDecoration: "none", padding: "8px 10px", borderRadius: 10, border: "1px solid #111" }}>Voltar</a>',
'        <a href={shareUrl} style={{ textDecoration: "none", padding: "8px 10px", borderRadius: 10, border: "1px solid #111" }}>Página de share</a>',
'        <a href={card3x4} target="_blank" rel="noreferrer" style={{ textDecoration: "none", padding: "8px 10px", borderRadius: 10, border: "1px solid #111" }}>Ver card (3:4)</a>',
'        <div style={{ opacity: 0.7 }}>status: {status}</div>',
'      </div>',
'',
'      <div style={{ display: "grid", gap: 8, padding: 12, border: "1px solid #ddd", borderRadius: 12 }}>',
'        <div style={{ fontWeight: 900 }}>Ponto</div>',
'        <div style={{ opacity: 0.9 }}>{String(p.kind || "—")}</div>',
'        <div style={{ opacity: 0.85 }}>{p.note ? String(p.note) : "—"}</div>',
'        <div style={{ opacity: 0.7, fontSize: 12 }}>confirmações: {String(p.confirmCount || 0)}</div>',
'      </div>',
'',
'      <div style={{ display: "grid", gap: 10, padding: 12, border: "1px solid #ddd", borderRadius: 12 }}>',
'        <div style={{ fontWeight: 900 }}>Antes / Depois (URL por enquanto)</div>',
'        <label style={{ display: "grid", gap: 4 }}>',
'          <span>Antes (URL)</span>',
'          <input value={beforeUrl} onChange={(e) => setBeforeUrl(e.target.value)} placeholder="https://..." style={{ padding: 10, borderRadius: 10, border: "1px solid #ccc" }} />',
'        </label>',
'        <label style={{ display: "grid", gap: 4 }}>',
'          <span>Depois (URL)</span>',
'          <input value={afterUrl} onChange={(e) => setAfterUrl(e.target.value)} placeholder="https://..." style={{ padding: 10, borderRadius: 10, border: "1px solid #ccc" }} />',
'        </label>',
'        <div style={{ opacity: 0.7, fontSize: 12 }}>Dica: pode subir as fotos em qualquer lugar (Drive/Imgur/servidor) e colar aqui.</div>',
'      </div>',
'',
'      <div style={{ display: "grid", gap: 10, padding: 12, border: "1px solid #ddd", borderRadius: 12 }}>',
'        <div style={{ fontWeight: 900 }}>Checklist do mutirão</div>',
'        <div style={{ display: "grid", gap: 8 }}>',
'          {[',
'            ' + '"luvas",' ,
'            ' + '"sacos",' ,
'            ' + '"agua",' ,
'            ' + '"separacao",' ,
'            ' + '"destino",' ,
'            ' + '"aviso_vizinhos"' ,
'          ].map((k) => (',
'            <label key={k} style={{ display: "flex", gap: 10, alignItems: "center" }}>',
'              <input type="checkbox" checked={!!check?.[k]} onChange={() => toggle(k)} />',
'              <span style={{ opacity: 0.9 }}>{k}</span>',
'            </label>',
'          ))}',
'        </div>',
'      </div>',
'',
'      <div style={{ display: "flex", gap: 10, flexWrap: "wrap", alignItems: "center" }}>',
'        <button onClick={saveDraft} style={{ padding: "10px 12px", borderRadius: 12, border: "1px solid #111", background: "#fff", cursor: "pointer" }}>',
'          Salvar rascunho',
'        </button>',
'        <button onClick={finish} style={{ padding: "10px 12px", borderRadius: 12, border: "1px solid #111", background: "#111", color: "#F7D500", fontWeight: 900, cursor: "pointer" }}>',
'          Finalizar (DONE)',
'        </button>',
'      </div>',
'',
'      {msg ? <div style={{ padding: 10, borderRadius: 10, background: "#fff7cc", border: "1px solid #f0d000" }}>{msg}</div> : null}',
'    </section>',
'  );',
'}',
''
)
WriteAllLinesUtf8NoBom $clientDetail $LDetailClient
Write-Host '[PATCH] wrote src/app/eco/mutiroes/[id]/MutiraoDetailClient.tsx'

# --- UI: share
$LSharePage = @(
'import ShareMutiraoClient from "./ShareMutiraoClient";',
'',
'export const dynamic = "force-dynamic";',
'',
'export default async function Page({ params }: { params: Promise<{ id: string }> }) {',
'  const p = await params;',
'  return (',
'    <main style={{ padding: 16, maxWidth: 1100, margin: "0 auto" }}>',
'      <h1 style={{ margin: "0 0 8px 0" }}>Compartilhar mutirão</h1>',
'      <p style={{ margin: "0 0 14px 0", opacity: 0.85 }}>Card + legenda prontos para postar.</p>',
'      <ShareMutiraoClient id={p.id} />',
'    </main>',
'  );',
'}',
''
)
WriteAllLinesUtf8NoBom $pageShare $LSharePage
Write-Host '[PATCH] wrote src/app/eco/share/mutirao/[id]/page.tsx'

$LShareClient = @(
'"use client";',
'',
'import { useEffect, useMemo, useState } from "react";',
'',
'type AnyObj = Record<string, any>;',
'',
'async function jget(url: string): Promise<AnyObj> {',
'  const res = await fetch(url, { headers: { Accept: "application/json" }, cache: "no-store" });',
'  const data = await res.json().catch(() => ({}));',
'  if (!res.ok) return { ok: false, status: res.status, ...data };',
'  return data;',
'}',
'',
'export default function ShareMutiraoClient({ id }: { id: string }) {',
'  const [item, setItem] = useState<AnyObj | null>(null);',
'  const [status, setStatus] = useState<string>("carregando");',
'  const [waHref, setWaHref] = useState<string>("#");',
'',
'  const card3x4 = useMemo(() => "/api/eco/mutirao/card?format=3x4&id=" + encodeURIComponent(id), [id]);',
'  const card1x1 = useMemo(() => "/api/eco/mutirao/card?format=1x1&id=" + encodeURIComponent(id), [id]);',
'  const pageUrl = useMemo(() => (typeof window !== "undefined" ? window.location.href : ""), []);',
'',
'  useEffect(() => {',
'    (async () => {',
'      setStatus("carregando");',
'      const d = await jget("/api/eco/mutirao/get?id=" + encodeURIComponent(id));',
'      if (d && d.ok && d.item) { setItem(d.item); setStatus("ok"); }',
'      else { setItem(null); setStatus("erro"); }',
'    })();',
'  }, [id]);',
'',
'  const caption = useMemo(() => {',
'    const p = item?.point || {};',
'    const kind = String(p.kind || "PONTO");',
'    const note = p.note ? String(p.note) : "";',
'    const st = String(item?.status || "");',
'    const base = [',
'      "ECO — mutirão (" + (st || "SCHEDULED") + ")",',
'      kind + (note ? (": " + note) : ""),',
'      "",',
'      "Recibo é lei. Cuidado é coletivo. Trabalho digno é o centro.",',
'      "#ECO — Escutar • Cuidar • Organizar",',
'    ].join("\\n");',
'    return base;',
'  }, [item]);',
'',
'  useEffect(() => {',
'    // gera href do WhatsApp só no client (evita hydration warning)',
'    const text = caption + (pageUrl ? ("\\n\\n" + pageUrl) : "");',
'    setWaHref("https://wa.me/?text=" + encodeURIComponent(text));',
'  }, [caption, pageUrl]);',
'',
'  async function copy(txt: string) {',
'    try { await navigator.clipboard.writeText(txt); } catch {}',
'  }',
'',
'  return (',
'    <section style={{ display: "grid", gap: 12 }}>',
'      <div style={{ display: "flex", gap: 10, flexWrap: "wrap", alignItems: "center" }}>',
'        <a href={"/eco/mutiroes/" + encodeURIComponent(id)} style={{ textDecoration: "none", padding: "8px 10px", borderRadius: 10, border: "1px solid #111" }}>Editar mutirão</a>',
'        <div style={{ opacity: 0.7 }}>status: {status}</div>',
'      </div>',
'',
'      <div style={{ display: "flex", gap: 10, flexWrap: "wrap" }}>',
'        <a href={card3x4} target="_blank" rel="noreferrer" style={{ padding: "10px 12px", borderRadius: 12, border: "1px solid #111", background: "#111", color: "#F7D500", textDecoration: "none", fontWeight: 900 }}>',
'          Abrir card 3:4',
'        </a>',
'        <a href={card1x1} target="_blank" rel="noreferrer" style={{ padding: "10px 12px", borderRadius: 12, border: "1px solid #111", textDecoration: "none" }}>',
'          Abrir card 1:1',
'        </a>',
'        <a href={waHref} target="_blank" rel="noreferrer" style={{ padding: "10px 12px", borderRadius: 12, border: "1px solid #111", textDecoration: "none" }}>',
'          WhatsApp',
'        </a>',
'      </div>',
'',
'      <div style={{ display: "grid", gap: 8, padding: 12, border: "1px solid #ddd", borderRadius: 12 }}>',
'        <div style={{ display: "flex", justifyContent: "space-between", gap: 10, alignItems: "center" }}>',
'          <div style={{ fontWeight: 900 }}>Legenda</div>',
'          <button onClick={() => copy(caption)} style={{ padding: "8px 10px", borderRadius: 10, border: "1px solid #111", background: "#F7D500", color: "#111", fontWeight: 900, cursor: "pointer" }}>',
'            Copiar',
'          </button>',
'        </div>',
'        <pre style={{ margin: 0, whiteSpace: "pre-wrap", fontFamily: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace", fontSize: 13, background: "#fafafa", padding: 10, borderRadius: 10, border: "1px solid #eee" }}>',
'          {caption}',
'        </pre>',
'      </div>',
'    </section>',
'  );',
'}',
''
)
WriteAllLinesUtf8NoBom $clientShare $LShareClient
Write-Host '[PATCH] wrote src/app/eco/share/mutirao/[id]/ShareMutiraoClient.tsx'

# --- Patch Mutiroes list client (add links)
if (Test-Path $mutListClient) {
  $LM = @(
'"use client";',
'',
'import { useEffect, useMemo, useState } from "react";',
'',
'type AnyObj = Record<string, any>;',
'',
'async function jget(url: string): Promise<AnyObj> {',
'  const res = await fetch(url, { headers: { Accept: "application/json" }, cache: "no-store" });',
'  const data = await res.json().catch(() => ({}));',
'  if (!res.ok) return { ok: false, status: res.status, ...data };',
'  return data;',
'}',
'',
'function fmt(dt: string) {',
'  try {',
'    const d = new Date(dt);',
'    return d.toLocaleString();',
'  } catch {',
'    return dt;',
'  }',
'}',
'function gmaps(lat: number, lng: number) {',
'  return "https://www.google.com/maps?q=" + encodeURIComponent(String(lat) + "," + String(lng));',
'}',
'',
'export default function MutiroesClient() {',
'  const [items, setItems] = useState<AnyObj[]>([]);',
'  const [status, setStatus] = useState<string>("carregando");',
'  const url = useMemo(() => "/api/eco/mutirao/list?limit=120", []);',
'',
'  async function refresh() {',
'    setStatus("carregando");',
'    const d = await jget(url);',
'    if (d && d.ok && Array.isArray(d.items)) { setItems(d.items); setStatus("ok"); }',
'    else { setItems([]); setStatus("erro"); }',
'  }',
'  useEffect(() => { refresh(); }, []);',
'',
'  return (',
'    <section style={{ display: "grid", gap: 10 }}>',
'      <div style={{ display: "flex", gap: 10, alignItems: "center", flexWrap: "wrap" }}>',
'        <button onClick={refresh} style={{ padding: "8px 10px", borderRadius: 10, border: "1px solid #111", background: "#F7D500", color: "#111", fontWeight: 900, cursor: "pointer" }}>',
'          Atualizar',
'        </button>',
'        <a href="/eco/pontos" style={{ textDecoration: "none", padding: "8px 10px", borderRadius: 10, border: "1px solid #111" }}>',
'          Voltar aos pontos',
'        </a>',
'        <div style={{ opacity: 0.7 }}>status: {status} • itens: {items.length}</div>',
'      </div>',
'',
'      {items.length ? items.map((it) => {',
'        const p = it.point || {};',
'        const lat = Number(p.lat);',
'        const lng = Number(p.lng);',
'        const maps = Number.isFinite(lat) && Number.isFinite(lng) ? gmaps(lat, lng) : "#";',
'        const id = String(it.id);',
'        return (',
'          <div key={id} style={{ display: "flex", justifyContent: "space-between", gap: 10, padding: 12, border: "1px solid #ddd", borderRadius: 12, alignItems: "center" }}>',
'            <div style={{ display: "grid", gap: 4 }}>',
'              <div style={{ fontWeight: 900 }}>{it.title ? String(it.title) : "Mutirão"}</div>',
'              <div style={{ opacity: 0.85 }}>🗓 {it.startAt ? fmt(String(it.startAt)) : ""} • ⏱ {String(it.durationMin || 90)} min • {String(it.status || "SCHEDULED")}</div>',
'              <div style={{ opacity: 0.8 }}>Ponto: {String(p.kind || "")} • confirmações: {String(p.confirmCount || 0)}</div>',
'              <div style={{ opacity: 0.75, fontSize: 12 }}>{p.note ? String(p.note) : "—"}</div>',
'            </div>',
'            <div style={{ display: "flex", gap: 8, flexWrap: "wrap", justifyContent: "flex-end" }}>',
'              <a href={maps} target="_blank" rel="noreferrer" style={{ textDecoration: "none", padding: "8px 10px", borderRadius: 10, border: "1px solid #111" }}>',
'                Ver no mapa',
'              </a>',
'              <a href={"/eco/mutiroes/" + encodeURIComponent(id)} style={{ textDecoration: "none", padding: "8px 10px", borderRadius: 10, border: "1px solid #111" }}>',
'                Abrir',
'              </a>',
'              <a href={"/eco/share/mutirao/" + encodeURIComponent(id)} style={{ textDecoration: "none", padding: "8px 10px", borderRadius: 10, border: "1px solid #111" }}>',
'                Compartilhar',
'              </a>',
'            </div>',
'          </div>',
'        );',
'      }) : (',
'        <div style={{ padding: 12, border: "1px solid #ddd", borderRadius: 12, opacity: 0.8 }}>',
'          Nenhum mutirão ainda. Vá em /eco/pontos e clique em “Virar mutirão”.',
'        </div>',
'      )}',
'    </section>',
'  );',
'}',
''
  )
  WriteAllLinesUtf8NoBom $mutListClient $LM
  Write-Host '[PATCH] wrote src/app/eco/mutiroes/MutiroesClient.tsx'
} else {
  Write-Host '[WARN] MutiroesClient.tsx not found; skipped list patch.'
}

# Report
$rep = Join-Path $reportDir ('eco-step-63-mutirao-finish-share-card-v0_1-' + $ts + '.md')
$repLines = @(
'# eco-step-63-mutirao-finish-share-card-v0_1',
'',
'- Time: ' + $ts,
'- Backup: ' + $backupDir,
'',
'## Added',
'- API: GET  /api/eco/mutirao/get?id=...',
'- API: POST /api/eco/mutirao/update (rascunho: beforeUrl/afterUrl/checklist)',
'- API: POST /api/eco/mutirao/finish  (DONE)',
'- API: GET  /api/eco/mutirao/card?format=3x4&id=... (+ 1x1)',
'- UI: /eco/mutiroes/[id] (detalhe)',
'- UI: /eco/share/mutirao/[id] (share)',
'- UI: /eco/mutiroes (botões Abrir/Compartilhar)',
'',
'## Verify',
'1) Restart dev server',
'2) Abra /eco/mutiroes, clique em Abrir',
'3) Preencha before/after URLs, marque checklist, salve rascunho',
'4) Finalize (DONE)',
'5) Abra /eco/share/mutirao/[id] e clique em Abrir card 3:4',
'6) Teste APIs: /api/eco/mutirao/get?id=... e /api/eco/mutirao/card?format=3x4&id=...',
''
)
WriteAllLinesUtf8NoBom $rep $repLines
Write-Host ('[REPORT] ' + $rep)

Write-Host ''
Write-Host '[VERIFY] Ctrl+C -> npm run dev'
Write-Host '[VERIFY] /eco/mutiroes -> Abrir -> salvar -> finalizar -> /eco/share/mutirao/[id]'