param(
  [string]$Root = (Get-Location).Path
)

function EnsureDir([string]$p) { if (-not (Test-Path $p)) { New-Item -ItemType Directory -Force -Path $p | Out-Null } }
function BackupFile([string]$p, [string]$backupDir) {
  if (Test-Path $p) {
    $rel = $p.Substring($Root.Length).TrimStart('\','/')
    $dest = Join-Path $backupDir ($rel -replace '[\\/]', '__')
    Copy-Item -Force -LiteralPath $p -Destination $dest
    Write-Host ("[BK] " + $rel + " -> " + (Split-Path -Leaf $dest))
  }
}

$ts = Get-Date -Format "yyyyMMdd-HHmmss"
$backupDir = Join-Path $Root ("tools/_patch_backup/" + $ts + "-eco-step-58b-fix-hydration-share-links-v0_1")
$reportDir = Join-Path $Root "reports"
EnsureDir $backupDir
EnsureDir $reportDir

$dayClient = Join-Path $Root "src/app/eco/share/dia/[day]/ShareDayClient.tsx"
$monClient = Join-Path $Root "src/app/eco/share/mes/[month]/ShareMonthClient.tsx"

Write-Host ("[DIAG] Root: " + $Root)
Write-Host ("[DIAG] Will rewrite: " + $dayClient)
Write-Host ("[DIAG] Will rewrite: " + $monClient)

BackupFile $dayClient $backupDir
BackupFile $monClient $backupDir

$enc = New-Object System.Text.UTF8Encoding($false)

# --- ShareDayClient.tsx (fix hydration: move window.location.href to useEffect) ---
$LDay = @(
'"use client";',
'',
'import { useEffect, useMemo, useState } from "react";',
'',
'type AnyObj = Record<string, any>;',
'',
'function fmtKg(n: any): string {',
'  const v = Number(n || 0) || 0;',
'  const s = Math.round(v * 10) / 10;',
'  return String(s).replace(".", ",") + " kg";',
'}',
'',
'function topMaterials(by: any): Array<{ k: string; v: number }> {',
'  const out: Array<{ k: string; v: number }> = [];',
'  if (by && typeof by === "object") {',
'    for (const k of Object.keys(by)) out.push({ k, v: Number(by[k] || 0) || 0 });',
'  }',
'  out.sort((a, b) => b.v - a.v);',
'  return out.slice(0, 5);',
'}',
'',
'async function jget(url: string): Promise<AnyObj> {',
'  const res = await fetch(url, { headers: { Accept: "application/json" }, cache: "no-store" });',
'  const data = await res.json().catch(() => ({}));',
'  if (!res.ok) return { ok: false, status: res.status, ...data };',
'  return data;',
'}',
'',
'async function copyText(txt: string) {',
'  try {',
'    await navigator.clipboard.writeText(txt);',
'    return true;',
'  } catch {',
'    try {',
'      const ta = document.createElement("textarea");',
'      ta.value = txt;',
'      document.body.appendChild(ta);',
'      ta.select();',
'      document.execCommand("copy");',
'      document.body.removeChild(ta);',
'      return true;',
'    } catch {',
'      return false;',
'    }',
'  }',
'}',
'',
'export default function ShareDayClient(props: { day: string }) {',
'  const day = String(props.day || "").trim();',
'  const [data, setData] = useState<AnyObj | null>(null);',
'  const [status, setStatus] = useState<string>("carregando");',
'  const [copied, setCopied] = useState<string>("");',
'  // IMPORTANT: avoid hydration mismatch by not reading window during render',
'  const [linkHere, setLinkHere] = useState<string>("");',
'',
'  const apiUrl = useMemo(() => "/api/eco/day-close?day=" + encodeURIComponent(day), [day]);',
'  const card34 = useMemo(() => "/api/eco/day-close/card?format=3x4&day=" + encodeURIComponent(day), [day]);',
'  const card11 = useMemo(() => "/api/eco/day-close/card?format=1x1&day=" + encodeURIComponent(day), [day]);',
'',
'  useEffect(() => {',
'    try { setLinkHere(window.location.href); } catch {}',
'  }, [day]);',
'',
'  useEffect(() => {',
'    let alive = true;',
'    (async () => {',
'      setStatus("carregando");',
'      const d = await jget(apiUrl);',
'      if (!alive) return;',
'      setData(d);',
'      setStatus(d && d.ok ? "ok" : "erro");',
'    })();',
'    return () => { alive = false; };',
'  }, [apiUrl]);',
'',
'  const caption = useMemo(() => {',
'    if (!data || !data.ok) {',
'      return "ECO — Fechamento do dia " + day + "\\n" +',
'        "Sem dados (ainda).\\n" +',
'        "\\n#ECO — Escutar • Cuidar • Organizar";',
'    }',
'    const summary = (data.item && data.item.summary) ? data.item.summary : {};',
'    const totals = summary.totals || {};',
'    const totalKg = fmtKg(totals.totalKg || 0);',
'    const mats = topMaterials(totals.byMaterialKg || {});',
'    const lines: string[] = [];',
'    lines.push("ECO — Fechamento do dia " + day);',
'    lines.push("Total: " + totalKg);',
'    if (mats.length) {',
'      lines.push("");',
'      lines.push("Por material:");',
'      for (const m of mats) lines.push("- " + String(m.k).toUpperCase() + ": " + fmtKg(m.v));',
'    }',
'    lines.push("");',
'    lines.push("Recibo é lei. Cuidado é coletivo. Trabalho digno é o centro.");',
'    lines.push("#ECO — Escutar • Cuidar • Organizar");',
'    return lines.join("\\n");',
'  }, [data, day]);',
'',
'  const waLink = useMemo(() => {',
'    const base = "https://wa.me/?text=";',
'    const text = caption + (linkHere ? ("\\n\\n" + linkHere) : "");',
'    return base + encodeURIComponent(text);',
'  }, [caption, linkHere]);',
'',
'  async function doCopyCaption() {',
'    const ok = await copyText(caption);',
'    setCopied(ok ? "Legenda copiada!" : "Falhou ao copiar");',
'    setTimeout(() => setCopied(""), 1600);',
'  }',
'',
'  async function doCopyLink() {',
'    const ok = await copyText(linkHere || "");',
'    setCopied(ok ? "Link copiado!" : "Falhou ao copiar");',
'    setTimeout(() => setCopied(""), 1600);',
'  }',
'',
'  return (',
'    <section style={{ display: "grid", gap: 12, maxWidth: 1100 }}>',
'      <div style={{ display: "flex", gap: 10, alignItems: "center", flexWrap: "wrap" }}>',
'        <a href="/eco/fechamento" style={{ textDecoration: "none" }}>← voltar</a>',
'        <div style={{ opacity: 0.8 }}>status: {status}</div>',
'        {copied ? <div style={{ padding: "6px 10px", border: "1px solid #ddd", borderRadius: 10 }}>{copied}</div> : null}',
'      </div>',
'',
'      <div style={{ display: "flex", gap: 10, flexWrap: "wrap" }}>',
'        <a href={card34} target="_blank" rel="noreferrer" style={{ padding: "8px 10px", borderRadius: 10, border: "1px solid #111", background: "#F7D500", color: "#111", fontWeight: 800, textDecoration: "none" }}>Abrir Card 3:4</a>',
'        <a href={card11} target="_blank" rel="noreferrer" style={{ padding: "8px 10px", borderRadius: 10, border: "1px solid #111", background: "#F7D500", color: "#111", fontWeight: 800, textDecoration: "none" }}>Abrir Card 1:1</a>',
'        <button onClick={doCopyCaption} style={{ padding: "8px 10px", borderRadius: 10, border: "1px solid #111" }}>Copiar legenda</button>',
'        <button onClick={doCopyLink} style={{ padding: "8px 10px", borderRadius: 10, border: "1px solid #111" }}>Copiar link</button>',
'        <a href={waLink} target="_blank" rel="noreferrer" style={{ padding: "8px 10px", borderRadius: 10, border: "1px solid #111", textDecoration: "none", color: "#111" }}>WhatsApp</a>',
'      </div>',
'',
'      <div style={{ display: "grid", gap: 12, gridTemplateColumns: "1fr 1fr" }}>',
'        <div>',
'          <h2 style={{ margin: "0 0 8px 0" }}>Preview 3:4</h2>',
'          <div style={{ border: "1px solid #ddd", borderRadius: 12, padding: 10, overflow: "hidden" }}>',
'            <img src={card34} alt="Card 3:4" style={{ width: "100%", height: "auto", display: "block" }} />',
'          </div>',
'        </div>',
'        <div>',
'          <h2 style={{ margin: "0 0 8px 0" }}>Preview 1:1</h2>',
'          <div style={{ border: "1px solid #ddd", borderRadius: 12, padding: 10, overflow: "hidden" }}>',
'            <img src={card11} alt="Card 1:1" style={{ width: "100%", height: "auto", display: "block" }} />',
'          </div>',
'        </div>',
'      </div>',
'',
'      <div>',
'        <h2 style={{ margin: "0 0 8px 0" }}>Legenda</h2>',
'        <textarea readOnly value={caption} style={{ width: "100%", minHeight: 220, padding: 12, border: "1px solid #ddd", borderRadius: 12, fontFamily: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace" }} />',
'      </div>',
'',
'      <div>',
'        <h2 style={{ margin: "0 0 8px 0" }}>Debug</h2>',
'        <pre style={{ whiteSpace: "pre-wrap", wordBreak: "break-word", padding: 12, border: "1px solid #ddd", borderRadius: 12 }}>',
'          {data ? JSON.stringify(data, null, 2) : "—"}',
'        </pre>',
'      </div>',
'    </section>',
'  );',
'}',
''
)

EnsureDir (Split-Path -Parent $dayClient)
[System.IO.File]::WriteAllLines($dayClient, $LDay, $enc)
Write-Host "[PATCH] rewrote src/app/eco/share/dia/[day]/ShareDayClient.tsx"

# --- ShareMonthClient.tsx (same hydration fix) ---
$LMon = @(
'"use client";',
'',
'import { useEffect, useMemo, useState } from "react";',
'',
'type AnyObj = Record<string, any>;',
'',
'function fmtKg(n: any): string {',
'  const v = Number(n || 0) || 0;',
'  const s = Math.round(v * 10) / 10;',
'  return String(s).replace(".", ",") + " kg";',
'}',
'',
'function topMaterials(by: any): Array<{ k: string; v: number }> {',
'  const out: Array<{ k: string; v: number }> = [];',
'  if (by && typeof by === "object") {',
'    for (const k of Object.keys(by)) out.push({ k, v: Number(by[k] || 0) || 0 });',
'  }',
'  out.sort((a, b) => b.v - a.v);',
'  return out.slice(0, 6);',
'}',
'',
'async function jget(url: string): Promise<AnyObj> {',
'  const res = await fetch(url, { headers: { Accept: "application/json" }, cache: "no-store" });',
'  const data = await res.json().catch(() => ({}));',
'  if (!res.ok) return { ok: false, status: res.status, ...data };',
'  return data;',
'}',
'',
'async function copyText(txt: string) {',
'  try {',
'    await navigator.clipboard.writeText(txt);',
'    return true;',
'  } catch {',
'    try {',
'      const ta = document.createElement("textarea");',
'      ta.value = txt;',
'      document.body.appendChild(ta);',
'      ta.select();',
'      document.execCommand("copy");',
'      document.body.removeChild(ta);',
'      return true;',
'    } catch {',
'      return false;',
'    }',
'  }',
'}',
'',
'export default function ShareMonthClient(props: { month: string }) {',
'  const month = String(props.month || "").trim();',
'  const [data, setData] = useState<AnyObj | null>(null);',
'  const [status, setStatus] = useState<string>("carregando");',
'  const [copied, setCopied] = useState<string>("");',
'  // IMPORTANT: avoid hydration mismatch by not reading window during render',
'  const [linkHere, setLinkHere] = useState<string>("");',
'',
'  const apiUrl = useMemo(() => "/api/eco/month-close?month=" + encodeURIComponent(month), [month]);',
'  const card34 = useMemo(() => "/api/eco/month-close/card?format=3x4&month=" + encodeURIComponent(month), [month]);',
'  const card11 = useMemo(() => "/api/eco/month-close/card?format=1x1&month=" + encodeURIComponent(month), [month]);',
'',
'  useEffect(() => {',
'    try { setLinkHere(window.location.href); } catch {}',
'  }, [month]);',
'',
'  useEffect(() => {',
'    let alive = true;',
'    (async () => {',
'      setStatus("carregando");',
'      const d = await jget(apiUrl);',
'      if (!alive) return;',
'      setData(d);',
'      setStatus(d && d.ok ? "ok" : "erro");',
'    })();',
'    return () => { alive = false; };',
'  }, [apiUrl]);',
'',
'  const caption = useMemo(() => {',
'    if (!data || !data.ok) {',
'      return "ECO — Transparência do mês " + month + "\\n" +',
'        "Sem dados (ainda).\\n" +',
'        "\\n#ECO — Escutar • Cuidar • Organizar";',
'    }',
'    const summary = (data.item && data.item.summary) ? data.item.summary : {};',
'    const totals = summary.totals || {};',
'    const totalKg = fmtKg(totals.totalKg || 0);',
'    const days = Number(totals.days || 0) || 0;',
'    const mats = topMaterials(totals.byMaterialKg || {});',
'    const lines: string[] = [];',
'    lines.push("ECO — Transparência do mês " + month);',
'    lines.push("Total do mês: " + totalKg + " (" + String(days) + " dias fechados)");',
'    if (mats.length) {',
'      lines.push("");',
'      lines.push("Por material (soma do mês):");',
'      for (const m of mats) lines.push("- " + String(m.k).toUpperCase() + ": " + fmtKg(m.v));',
'    }',
'    lines.push("");',
'    lines.push("Recibo é lei. Cuidado é coletivo. Trabalho digno é o centro.");',
'    lines.push("#ECO — Escutar • Cuidar • Organizar");',
'    return lines.join("\\n");',
'  }, [data, month]);',
'',
'  const waLink = useMemo(() => {',
'    const base = "https://wa.me/?text=";',
'    const text = caption + (linkHere ? ("\\n\\n" + linkHere) : "");',
'    return base + encodeURIComponent(text);',
'  }, [caption, linkHere]);',
'',
'  async function doCopyCaption() {',
'    const ok = await copyText(caption);',
'    setCopied(ok ? "Legenda copiada!" : "Falhou ao copiar");',
'    setTimeout(() => setCopied(""), 1600);',
'  }',
'',
'  async function doCopyLink() {',
'    const ok = await copyText(linkHere || "");',
'    setCopied(ok ? "Link copiado!" : "Falhou ao copiar");',
'    setTimeout(() => setCopied(""), 1600);',
'  }',
'',
'  return (',
'    <section style={{ display: "grid", gap: 12, maxWidth: 1100 }}>',
'      <div style={{ display: "flex", gap: 10, alignItems: "center", flexWrap: "wrap" }}>',
'        <a href="/eco/transparencia" style={{ textDecoration: "none" }}>← voltar</a>',
'        <div style={{ opacity: 0.8 }}>status: {status}</div>',
'        {copied ? <div style={{ padding: "6px 10px", border: "1px solid #ddd", borderRadius: 10 }}>{copied}</div> : null}',
'      </div>',
'',
'      <div style={{ display: "flex", gap: 10, flexWrap: "wrap" }}>',
'        <a href={card34} target="_blank" rel="noreferrer" style={{ padding: "8px 10px", borderRadius: 10, border: "1px solid #111", background: "#F7D500", color: "#111", fontWeight: 800, textDecoration: "none" }}>Abrir Card 3:4</a>',
'        <a href={card11} target="_blank" rel="noreferrer" style={{ padding: "8px 10px", borderRadius: 10, border: "1px solid #111", background: "#F7D500", color: "#111", fontWeight: 800, textDecoration: "none" }}>Abrir Card 1:1</a>',
'        <button onClick={doCopyCaption} style={{ padding: "8px 10px", borderRadius: 10, border: "1px solid #111" }}>Copiar legenda</button>',
'        <button onClick={doCopyLink} style={{ padding: "8px 10px", borderRadius: 10, border: "1px solid #111" }}>Copiar link</button>',
'        <a href={waLink} target="_blank" rel="noreferrer" style={{ padding: "8px 10px", borderRadius: 10, border: "1px solid #111", textDecoration: "none", color: "#111" }}>WhatsApp</a>',
'      </div>',
'',
'      <div style={{ display: "grid", gap: 12, gridTemplateColumns: "1fr 1fr" }}>',
'        <div>',
'          <h2 style={{ margin: "0 0 8px 0" }}>Preview 3:4</h2>',
'          <div style={{ border: "1px solid #ddd", borderRadius: 12, padding: 10, overflow: "hidden" }}>',
'            <img src={card34} alt="Card 3:4" style={{ width: "100%", height: "auto", display: "block" }} />',
'          </div>',
'        </div>',
'        <div>',
'          <h2 style={{ margin: "0 0 8px 0" }}>Preview 1:1</h2>',
'          <div style={{ border: "1px solid #ddd", borderRadius: 12, padding: 10, overflow: "hidden" }}>',
'            <img src={card11} alt="Card 1:1" style={{ width: "100%", height: "auto", display: "block" }} />',
'          </div>',
'        </div>',
'      </div>',
'',
'      <div>',
'        <h2 style={{ margin: "0 0 8px 0" }}>Legenda</h2>',
'        <textarea readOnly value={caption} style={{ width: "100%", minHeight: 220, padding: 12, border: "1px solid #ddd", borderRadius: 12, fontFamily: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace" }} />',
'      </div>',
'',
'      <div>',
'        <h2 style={{ margin: "0 0 8px 0" }}>Debug</h2>',
'        <pre style={{ whiteSpace: "pre-wrap", wordBreak: "break-word", padding: 12, border: "1px solid #ddd", borderRadius: 12 }}>',
'          {data ? JSON.stringify(data, null, 2) : "—"}',
'        </pre>',
'      </div>',
'    </section>',
'  );',
'}',
''
)

EnsureDir (Split-Path -Parent $monClient)
[System.IO.File]::WriteAllLines($monClient, $LMon, $enc)
Write-Host "[PATCH] rewrote src/app/eco/share/mes/[month]/ShareMonthClient.tsx"

$rep = Join-Path $reportDir ("eco-step-58b-fix-hydration-share-links-v0_1-" + $ts + ".md")
$repLines = @(
"# eco-step-58b-fix-hydration-share-links-v0_1",
"",
"- Time: " + $ts,
"- Backup: " + $backupDir,
"",
"## Fix",
"- Move window.location.href to useEffect in ShareDayClient/ShareMonthClient to avoid hydration mismatch.",
"",
"## Verify",
"- Restart dev server",
"- Open /eco/share/dia/2025-12-27 and /eco/share/mes/2025-12",
"- Confirm no hydration warning and WhatsApp button works",
""
)
[System.IO.File]::WriteAllLines($rep, $repLines, $enc)
Write-Host ("[REPORT] " + $rep)

Write-Host ""
Write-Host "[VERIFY] Ctrl+C -> npm run dev, abrir /eco/share/dia/2025-12-27 e checar console (sem hydration error)."