param(
  [string]$Root = (Get-Location).Path
)

$ErrorActionPreference = "Stop"

function TryDotSourceBootstrap($rootPath) {
  $b1 = Join-Path $rootPath "tools\_bootstrap.ps1"
  if (Test-Path $b1) { . $b1; return $true }
  return $false
}

# Fallbacks (caso _bootstrap não carregue por algum motivo)
if (-not (Get-Command EnsureDir -ErrorAction SilentlyContinue)) {
  function EnsureDir([string]$p) { if ($p -and -not (Test-Path $p)) { New-Item -ItemType Directory -Force -Path $p | Out-Null } }
}
if (-not (Get-Command BackupFile -ErrorAction SilentlyContinue)) {
  function BackupFile([string]$src, [string]$dir) {
    if (-not (Test-Path $src)) { return }
    EnsureDir $dir
    $name = ($src -replace '[:\\\/]', '_')
    Copy-Item -Force $src (Join-Path $dir $name)
  }
}
if (-not (Get-Command WriteUtf8NoBom -ErrorAction SilentlyContinue)) {
  function WriteUtf8NoBom([string]$path, [string]$content) {
    EnsureDir (Split-Path -Parent $path)
    [IO.File]::WriteAllText($path, $content, [System.Text.UTF8Encoding]::new($false))
  }
}

[void](TryDotSourceBootstrap $Root)

$stamp = Get-Date -Format "yyyyMMdd-HHmmss"
$me = "eco-step-116-add-points2-alias-and-scan-v0_1"
Write-Host ("== " + $me + " == " + $stamp)
Write-Host ("[DIAG] Root: " + $Root)

$backupDir = Join-Path $Root ("tools\_patch_backup\" + $stamp + "-" + $me)
EnsureDir $backupDir

# --- PATCH 1: criar alias /api/eco/points2 -> /api/eco/points (GET)
$aliasFile = Join-Path $Root "src\app\api\eco\points2\route.ts"
EnsureDir (Split-Path -Parent $aliasFile)
if (Test-Path $aliasFile) { BackupFile $aliasFile $backupDir }

$ts = @(
'// AUTO-GENERATED by tools/eco-step-116-add-points2-alias-and-scan-v0_1.ps1',
'// Compat: alguns clients antigos chamam /api/eco/points2. Mantemos alias para /api/eco/points.',
'',
'import { GET as GET_POINTS } from "../points/route";',
'',
'export const runtime = "nodejs";',
'export const dynamic = "force-dynamic";',
'',
'export async function GET(req: Request) {',
'  return GET_POINTS(req);',
'}',
''
)

WriteUtf8NoBom $aliasFile ($ts -join "`n")
Write-Host ("[PATCH] alias created -> " + $aliasFile)

# --- PATCH 2: scan no src substituindo /api/eco/points2 -> /api/eco/points (só por limpeza)
$srcRoot = Join-Path $Root "src"
$hits = @()
if (Test-Path $srcRoot) {
  $files = Get-ChildItem -Recurse -File $srcRoot -ErrorAction SilentlyContinue
  foreach ($f in $files) {
    $raw = Get-Content -Raw -ErrorAction SilentlyContinue $f.FullName
    if ($raw -and $raw.Contains("/api/eco/points2")) { $hits += $f.FullName }
  }
}
Write-Host ("[DIAG] hits '/api/eco/points2' = " + $hits.Count)

$changed = @()
foreach ($p in $hits) {
  try {
    $raw = Get-Content -Raw -ErrorAction Stop $p
    if (-not $raw) { continue }
    $new = $raw.Replace("/api/eco/points2", "/api/eco/points")
    if ($new -ne $raw) {
      BackupFile $p $backupDir
      WriteUtf8NoBom $p $new
      $changed += $p
      Write-Host ("[PATCH] updated -> " + $p)
    }
  } catch {
    Write-Host ("[WARN] failed to patch " + $p + " :: " + $_.Exception.Message)
  }
}

# --- REPORT
$report = @()
$report += "# $me"
$report += ""
$report += "- Time: $stamp"
$report += "- Backup: $backupDir"
$report += ""
$report += "## Patched"
$report += "- src/app/api/eco/points2/route.ts (alias GET -> points)"
if ($changed.Count -gt 0) {
  $report += "- src replacements:"
  foreach ($c in $changed) { $report += "  - $c" }
} else {
  $report += "- src replacements: (none)"
}
$report += ""
$report += "## Verify"
$report += "1) Ctrl+C -> npm run dev"
$report += '2) irm "http://localhost:3000/api/eco/points2?limit=1" | ConvertTo-Json -Depth 40'
$report += "3) abrir /eco/mural (não pode aparecer 404 de /points2 no console)"
$report += ""

$reportPath = Join-Path $Root ("reports\" + $me + "-" + $stamp + ".md")
EnsureDir (Split-Path -Parent $reportPath)
WriteUtf8NoBom $reportPath ($report -join "`n")
Write-Host ("[REPORT] " + $reportPath)

Write-Host ""
Write-Host "[VERIFY] rode:"
Write-Host "  Ctrl+C -> npm run dev"
Write-Host '  irm "http://localhost:3000/api/eco/points2?limit=1" | ConvertTo-Json -Depth 40'
Write-Host "  abrir /eco/mural"