param(
  [string]$Root = (Get-Location).Path
)

function EnsureDir([string]$p) { if (-not (Test-Path $p)) { New-Item -ItemType Directory -Force -Path $p | Out-Null } }
function BackupFile([string]$p, [string]$backupDir) {
  if (Test-Path $p) {
    $name = Split-Path -Leaf $p
    Copy-Item -Force -LiteralPath $p -Destination (Join-Path $backupDir $name)
    Write-Host ("[BK] " + $name)
  }
}

$ts = Get-Date -Format "yyyyMMdd-HHmmss"
$backupDir = Join-Path $Root ("tools/_patch_backup/" + $ts + "-eco-step-54b-day-close-debug-v0_1")
$reportDir = Join-Path $Root "reports"
EnsureDir $backupDir
EnsureDir $reportDir

$rt1 = Join-Path $Root "src/app/api/eco/day-close/route.ts"
$rt2 = Join-Path $Root "src/app/api/eco/day-close/compute/route.ts"

Write-Host ("[DIAG] Root: " + $Root)
Write-Host ("[DIAG] Patch: " + $rt1)
Write-Host ("[DIAG] Patch: " + $rt2)

BackupFile $rt1 $backupDir
BackupFile $rt2 $backupDir

$enc = New-Object System.Text.UTF8Encoding($false)

# ---------- route.ts ----------
$lines1 = @(
'// ECO — day-close (cache + upsert) — step 54b: debug bad_day + safeDay robust',
'',
'import { NextResponse } from "next/server";',
'import { prisma } from "@/lib/prisma";',
'',
'export const runtime = "nodejs";',
'export const dynamic = "force-dynamic";',
'',
'function safeDay(input: string | null): string | null {',
'  const raw = String(input ?? "").trim();',
'  if (!raw) return null;',
'  // normaliza hífens unicode e "/"',
'  const norm = raw.replace(/[‐-‒–—―]/g, "-").replace(/\//g, "-");',
'  // aceita YYYY-MM-DD e também prefixo YYYY-MM-DDT... (pega só o começo)',
'  const m = norm.match(/^(\d{4})-(\d{2})-(\d{2})(?:$|[T\s])/);',
'  if (!m) return null;',
'  const mo = Number(m[2]);',
'  const d = Number(m[3]);',
'  if (mo < 1 || mo > 12) return null;',
'  if (d < 1 || d > 31) return null;',
'  return m[1] + "-" + m[2] + "-" + m[3];',
'}',
'',
'function asMsg(e: unknown) {',
'  if (e instanceof Error) return e.message;',
'  try { return String(e); } catch { return "unknown"; }',
'}',
'',
'function looksLikeMissingTable(msg: string) {',
'  const m = msg.toLowerCase();',
'  return m.includes("does not exist") || m.includes("no such table") || m.includes("p2021");',
'}',
'',
'function getDayCloseModel() {',
'  const pc: any = prisma as any;',
'  return pc?.ecoDayClose;',
'}',
'',
'function getTriagemModel() {',
'  const pc: any = prisma as any;',
'  const candidates = ["ecoTriagem", "triagem", "ecoSorting", "sorting"];',
'  for (const k of candidates) {',
'    const m = pc?.[k];',
'    if (m && typeof m.findMany === "function") return { key: k, model: m as any };',
'  }',
'  return null;',
'}',
'',
'function dayRange(day: string) {',
'  const start = new Date(day + "T00:00:00-03:00");',
'  const end = new Date(day + "T23:59:59.999-03:00");',
'  return { start, end };',
'}',
'',
'function bump(obj: any, key: string, inc: number) {',
'  if (!obj[key]) obj[key] = 0;',
'  obj[key] += inc;',
'}',
'',
'function normalizeMaterial(s: string) {',
'  const t = String(s || "").toLowerCase();',
'  if (t.includes("papel")) return "papel";',
'  if (t.includes("plasti")) return "plastico";',
'  if (t.includes("metal")) return "metal";',
'  if (t.includes("vidro")) return "vidro";',
'  if (t.includes("org")) return "organico";',
'  if (t.includes("reje")) return "rejeito";',
'  return "outros";',
'}',
'',
'async function computeSummary(day: string) {',
'  const { start, end } = dayRange(day);',
'  const tri = getTriagemModel();',
'',
'  const totals: any = { totalKg: 0, byMaterialKg: {}, count: 0 };',
'  const meta: any = { computedAt: new Date().toISOString(), source: [] as string[] };',
'',
'  if (tri) {',
'    meta.source.push("triagem:" + tri.key);',
'    const rows = await tri.model.findMany({ where: { createdAt: { gte: start, lte: end } } });',
'    totals.count = rows.length;',
'    for (const r of rows) {',
'      const kg = Number((r && (r.weightKg ?? r.kg ?? r.weight ?? 0)) || 0) || 0;',
'      const mat = normalizeMaterial(String((r && (r.material ?? r.kind ?? r.type ?? "")) || ""));',
'      totals.totalKg += kg;',
'      bump(totals.byMaterialKg, mat, kg);',
'    }',
'  } else {',
'    meta.source.push("triagem:missing");',
'  }',
'',
'  return { day, totals, meta, notes: [], version: "v0" };',
'}',
'',
'export async function GET(req: Request) {',
'  const { searchParams } = new URL(req.url);',
'  const qDay = searchParams.get("day");',
'  const qD = searchParams.get("d");',
'  const qDate = searchParams.get("date");',
'  const day = safeDay(qDay ?? qD ?? qDate);',
'  const fresh = String(searchParams.get("fresh") || "").trim() === "1";',
'',
'  if (!day) {',
'    return NextResponse.json(',
'      { ok: false, error: "bad_day", got: { day: qDay, d: qD, date: qDate }, hint: "use ?day=YYYY-MM-DD" },',
'      { status: 400 }',
'    );',
'  }',
'',
'  const model = getDayCloseModel();',
'  if (!model?.findUnique) {',
'    return NextResponse.json({ ok: false, error: "model_not_ready" }, { status: 503 });',
'  }',
'',
'  try {',
'    if (!fresh) {',
'      const row = await model.findUnique({ where: { day } });',
'      if (row) return NextResponse.json({ ok: true, item: row, cached: true });',
'    }',
'',
'    const summary = await computeSummary(day);',
'    const item = await model.upsert({',
'      where: { day },',
'      update: { summary },',
'      create: { day, summary },',
'    });',
'',
'    return NextResponse.json({ ok: true, item, cached: false });',
'  } catch (e) {',
'    const msg = asMsg(e);',
'    if (looksLikeMissingTable(msg)) {',
'      return NextResponse.json({ ok: false, error: "db_not_ready", detail: msg }, { status: 503 });',
'    }',
'    return NextResponse.json({ ok: false, error: "db_error", detail: msg }, { status: 500 });',
'  }',
'}',
'',
'export async function POST(req: Request) {',
'  const body = (await req.json().catch(() => null)) as any;',
'  const rawDay = body?.day ?? null;',
'  const day = safeDay(rawDay);',
'',
'  if (!day) {',
'    return NextResponse.json(',
'      { ok: false, error: "bad_day", got: { day: rawDay }, hint: "body.day must be YYYY-MM-DD" },',
'      { status: 400 }',
'    );',
'  }',
'',
'  const model = getDayCloseModel();',
'  if (!model?.upsert) {',
'    return NextResponse.json({ ok: false, error: "model_not_ready" }, { status: 503 });',
'  }',
'',
'  try {',
'    const summary = body?.summary ?? (await computeSummary(day));',
'    const item = await model.upsert({',
'      where: { day },',
'      update: { summary },',
'      create: { day, summary },',
'    });',
'    return NextResponse.json({ ok: true, item });',
'  } catch (e) {',
'    const msg = asMsg(e);',
'    if (looksLikeMissingTable(msg)) {',
'      return NextResponse.json({ ok: false, error: "db_not_ready", detail: msg }, { status: 503 });',
'    }',
'    return NextResponse.json({ ok: false, error: "db_error", detail: msg }, { status: 500 });',
'  }',
'}',
''
)

EnsureDir (Split-Path -Parent $rt1)
[System.IO.File]::WriteAllLines($rt1, $lines1, $enc)
Write-Host "[PATCH] wrote src/app/api/eco/day-close/route.ts"

# ---------- compute/route.ts ----------
$lines2 = @(
'// ECO — day-close/compute — step 54b: safeDay robust',
'',
'import { NextResponse } from "next/server";',
'import { prisma } from "@/lib/prisma";',
'',
'export const runtime = "nodejs";',
'export const dynamic = "force-dynamic";',
'',
'function safeDay(input: string | null): string | null {',
'  const raw = String(input ?? "").trim();',
'  if (!raw) return null;',
'  const norm = raw.replace(/[‐-‒–—―]/g, "-").replace(/\//g, "-");',
'  const m = norm.match(/^(\d{4})-(\d{2})-(\d{2})(?:$|[T\s])/);',
'  if (!m) return null;',
'  const mo = Number(m[2]);',
'  const d = Number(m[3]);',
'  if (mo < 1 || mo > 12) return null;',
'  if (d < 1 || d > 31) return null;',
'  return m[1] + "-" + m[2] + "-" + m[3];',
'}',
'',
'function asMsg(e: unknown) {',
'  if (e instanceof Error) return e.message;',
'  try { return String(e); } catch { return "unknown"; }',
'}',
'',
'function looksLikeMissingTable(msg: string) {',
'  const m = msg.toLowerCase();',
'  return m.includes("does not exist") || m.includes("no such table") || m.includes("p2021");',
'}',
'',
'function getTriagemModel() {',
'  const pc: any = prisma as any;',
'  const candidates = ["ecoTriagem", "triagem", "ecoSorting", "sorting"];',
'  for (const k of candidates) {',
'    const m = pc?.[k];',
'    if (m && typeof m.findMany === "function") return { key: k, model: m as any };',
'  }',
'  return null;',
'}',
'',
'function dayRange(day: string) {',
'  const start = new Date(day + "T00:00:00-03:00");',
'  const end = new Date(day + "T23:59:59.999-03:00");',
'  return { start, end };',
'}',
'',
'function bump(obj: any, key: string, inc: number) {',
'  if (!obj[key]) obj[key] = 0;',
'  obj[key] += inc;',
'}',
'',
'function normalizeMaterial(s: string) {',
'  const t = String(s || "").toLowerCase();',
'  if (t.includes("papel")) return "papel";',
'  if (t.includes("plasti")) return "plastico";',
'  if (t.includes("metal")) return "metal";',
'  if (t.includes("vidro")) return "vidro";',
'  if (t.includes("org")) return "organico";',
'  if (t.includes("reje")) return "rejeito";',
'  return "outros";',
'}',
'',
'async function computeSummary(day: string) {',
'  const { start, end } = dayRange(day);',
'  const tri = getTriagemModel();',
'',
'  const totals: any = { totalKg: 0, byMaterialKg: {}, count: 0 };',
'  const meta: any = { computedAt: new Date().toISOString(), source: [] as string[] };',
'',
'  if (tri) {',
'    meta.source.push("triagem:" + tri.key);',
'    const rows = await tri.model.findMany({ where: { createdAt: { gte: start, lte: end } } });',
'    totals.count = rows.length;',
'    for (const r of rows) {',
'      const kg = Number((r && (r.weightKg ?? r.kg ?? r.weight ?? 0)) || 0) || 0;',
'      const mat = normalizeMaterial(String((r && (r.material ?? r.kind ?? r.type ?? "")) || ""));',
'      totals.totalKg += kg;',
'      bump(totals.byMaterialKg, mat, kg);',
'    }',
'  } else {',
'    meta.source.push("triagem:missing");',
'  }',
'',
'  return { day, totals, meta, notes: [], version: "v0" };',
'}',
'',
'export async function GET(req: Request) {',
'  const { searchParams } = new URL(req.url);',
'  const qDay = searchParams.get("day");',
'  const qD = searchParams.get("d");',
'  const qDate = searchParams.get("date");',
'  const day = safeDay(qDay ?? qD ?? qDate);',
'',
'  if (!day) {',
'    return NextResponse.json(',
'      { ok: false, error: "bad_day", got: { day: qDay, d: qD, date: qDate }, hint: "use ?day=YYYY-MM-DD" },',
'      { status: 400 }',
'    );',
'  }',
'',
'  try {',
'    const summary = await computeSummary(day);',
'    return NextResponse.json({ ok: true, summary });',
'  } catch (e) {',
'    const msg = asMsg(e);',
'    if (looksLikeMissingTable(msg)) {',
'      return NextResponse.json({ ok: false, error: "db_not_ready", detail: msg }, { status: 503 });',
'    }',
'    return NextResponse.json({ ok: false, error: "db_error", detail: msg }, { status: 500 });',
'  }',
'}',
''
)

EnsureDir (Split-Path -Parent $rt2)
[System.IO.File]::WriteAllLines($rt2, $lines2, $enc)
Write-Host "[PATCH] wrote src/app/api/eco/day-close/compute/route.ts"

$rep = Join-Path $reportDir ("eco-step-54b-day-close-debug-v0_1-" + $ts + ".md")
$repLines = @(
"# eco-step-54b-day-close-debug-v0_1",
"",
"- Time: " + $ts,
"- Backup: " + $backupDir,
"- Patched:",
"  - " + $rt1,
"  - " + $rt2,
"",
"## What changed",
"- safeDay ficou mais robusto (normaliza hífens unicode, aceita YYYY-MM-DD e prefixo YYYY-MM-DDT...).",
"- bad_day agora devolve got:{day,d,date} para a gente ver o que chegou de verdade.",
""
)
[System.IO.File]::WriteAllLines($rep, $repLines, $enc)
Write-Host ("[REPORT] " + $rep)

Write-Host ""
Write-Host "[NEXT] Reinicie o dev server e teste:"
Write-Host '  irm "http://localhost:3000/api/eco/day-close?day=2025-12-26" -Headers @{Accept="application/json"} | ConvertTo-Json -Depth 20'