param(
  [string]$Root = (Get-Location).Path
)

$ts = Get-Date -Format "yyyyMMdd-HHmmss"

# bootstrap (se existir)
$boot = Join-Path $Root "tools/_bootstrap.ps1"
if (Test-Path -LiteralPath $boot) { . $boot }

# fallbacks
if (-not (Get-Command EnsureDir -ErrorAction SilentlyContinue)) {
  function EnsureDir([string]$p) { if (-not (Test-Path -LiteralPath $p)) { New-Item -ItemType Directory -Force -Path $p | Out-Null } }
}
if (-not (Get-Command WriteUtf8NoBom -ErrorAction SilentlyContinue)) {
  function WriteUtf8NoBom([string]$p, [string]$content) {
    EnsureDir (Split-Path -Parent $p)
    $enc = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($p, $content, $enc)
  }
}
if (-not (Get-Command BackupFile -ErrorAction SilentlyContinue)) {
  function BackupFile([string]$root, [string]$p, [string]$backupDir) {
    if (Test-Path -LiteralPath $p) {
      $rel = $p.Substring($root.Length).TrimStart('\','/')
      $dest = Join-Path $backupDir ($rel -replace '[\\/]', '__')
      Copy-Item -Force -LiteralPath $p -Destination $dest
      Write-Host ("[BK] " + $rel + " -> " + (Split-Path -Leaf $dest))
    }
  }
}
function WriteLines([string]$p, [string[]]$lines) { WriteUtf8NoBom $p ($lines -join "`n") }

$backupDir = Join-Path $Root ("tools/_patch_backup/" + $ts + "-eco-step-69b-mapa-fix-quotes-v0_1")
$reportDir = Join-Path $Root "reports"
EnsureDir $backupDir
EnsureDir $reportDir

Write-Host ("== eco-step-69b-mapa-abandono-x-cuidado-fix-quotes-v0_1 == " + $ts)
Write-Host ("[DIAG] Root: " + $Root)

$src = Join-Path $Root "src"
if (-not (Test-Path -LiteralPath $src)) { throw ("[STOP] Não achei src/: " + $src) }

# Paths
$apiMap     = Join-Path $Root "src/app/api/eco/points/map/route.ts"
$apiReport  = Join-Path $Root "src/app/api/eco/points/report/route.ts"
$apiConfirm = Join-Path $Root "src/app/api/eco/points/confirm/route.ts"

$pageMapa   = Join-Path $Root "src/app/eco/mapa/page.tsx"
$clientMapa = Join-Path $Root "src/app/eco/mapa/MapaClient.tsx"

Write-Host ("[DIAG] Will write: " + $apiMap)
Write-Host ("[DIAG] Will write: " + $apiReport)
Write-Host ("[DIAG] Will write: " + $apiConfirm)
Write-Host ("[DIAG] Will write: " + $pageMapa)
Write-Host ("[DIAG] Will write: " + $clientMapa)

BackupFile $Root $apiMap $backupDir
BackupFile $Root $apiReport $backupDir
BackupFile $Root $apiConfirm $backupDir
BackupFile $Root $pageMapa $backupDir
BackupFile $Root $clientMapa $backupDir

EnsureDir (Split-Path -Parent $apiMap)
EnsureDir (Split-Path -Parent $apiReport)
EnsureDir (Split-Path -Parent $apiConfirm)
EnsureDir (Split-Path -Parent $pageMapa)
EnsureDir (Split-Path -Parent $clientMapa)

# ---------------- API: /api/eco/points/map ----------------
$LApiMap = @(
'import { NextResponse } from "next/server";',
'import { prisma } from "@/lib/prisma";',
'',
'export const runtime = "nodejs";',
'export const dynamic = "force-dynamic";',
'',
'function asMsg(e: unknown) {',
'  if (e instanceof Error) return e.message;',
'  try { return String(e); } catch { return "unknown"; }',
'}',
'function looksLikeMissingTable(msg: string) {',
'  const m = msg.toLowerCase();',
'  return m.includes("does not exist") || m.includes("no such table") || m.includes("p2021");',
'}',
'function getPointModel() {',
'  const pc: any = prisma as any;',
'  const candidates = ["ecoPoint", "ecoCriticalPoint", "criticalPoint", "ecoPonto", "ponto", "ecoPontoCritico"];',
'  for (const k of candidates) {',
'    const m = pc?.[k];',
'    if (m && typeof m.findMany === "function") return { key: k, model: m as any };',
'  }',
'  return null;',
'}',
'function normStatus(v: any) {',
'  const t = String(v || "").trim().toUpperCase();',
'  if (!t) return "UNKNOWN";',
'  if (t === "ABERTO") return "OPEN";',
'  if (t === "RESOLVIDO") return "RESOLVED";',
'  if (t === "DONE") return "RESOLVED";',
'  return t;',
'}',
'function pickStr(r: any, keys: string[]) {',
'  for (const k of keys) {',
'    const v = (r as any)?.[k];',
'    if (typeof v === "string" && v.trim()) return v.trim();',
'  }',
'  return "";',
'}',
'function pickNum(r: any, keys: string[]) {',
'  for (const k of keys) {',
'    const v = (r as any)?.[k];',
'    const n = Number(v);',
'    if (!Number.isNaN(n) && Number.isFinite(n)) return n;',
'  }',
'  return null;',
'}',
'function normalizeRow(r: any) {',
'  const lat = pickNum(r, ["lat","latitude","geoLat","locationLat"]);',
'  const lng = pickNum(r, ["lng","lon","longitude","geoLng","locationLng"]);',
'  const id = String((r as any)?.id || "");',
'  const status = normStatus((r as any)?.status);',
'  const category = pickStr(r, ["category","kind","type","categoria"]);',
'  const bairro = pickStr(r, ["bairro","neighborhood","area","regiao","region"]);',
'  const title = pickStr(r, ["title","name","titulo"]);',
'  const description = pickStr(r, ["description","desc","details","detalhes","note","notes","obs","observacao"]);',
'  const evidenceUrl = pickStr(r, ["evidenceUrl","photoUrl","imageUrl","url","beforeUrl","afterUrl"]);',
'  const createdAt = (r as any)?.createdAt ? new Date((r as any).createdAt).toISOString() : null;',
'  const updatedAt = (r as any)?.updatedAt ? new Date((r as any).updatedAt).toISOString() : null;',
'  const confirmations = pickNum(r, ["confirmations","confirmCount","votes","upvotes","confirmationsCount"]);',
'  return { id, status, category, bairro, title, description, evidenceUrl, lat, lng, createdAt, updatedAt, confirmations: confirmations ?? 0 };',
'}',
'',
'export async function GET(req: Request) {',
'  const { searchParams } = new URL(req.url);',
'  const status = String(searchParams.get("status") || "ALL").trim().toUpperCase();',
'  const days = Math.max(1, Math.min(365, Number(searchParams.get("days") || 30) || 30));',
'  const q = String(searchParams.get("q") || "").trim().toLowerCase();',
'  const bairro = String(searchParams.get("bairro") || "").trim();',
'  const category = String(searchParams.get("category") || "").trim();',
'',
'  const bbox = String(searchParams.get("bbox") || "").trim();',
'  let bb: any = null;',
'  if (bbox) {',
'    const parts = bbox.split(",").map((x) => Number(x.trim()));',
'    if (parts.length === 4 && parts.every((n) => Number.isFinite(n))) {',
'      bb = { minLat: parts[0], minLng: parts[1], maxLat: parts[2], maxLng: parts[3] };',
'    }',
'  }',
'',
'  const pm = getPointModel();',
'  if (!pm?.model) return NextResponse.json({ ok: false, error: "model_not_ready" }, { status: 503 });',
'',
'  const end = new Date();',
'  const start = new Date(end.getTime() - days * 24 * 60 * 60 * 1000);',
'',
'  try {',
'    let rows: any[] = [];',
'    try {',
'      const where: any = {};',
'      where.AND = [];',
'      where.AND.push({ createdAt: { gte: start, lte: end } });',
'      if (status !== "ALL") where.AND.push({ status });',
'      if (bairro) where.AND.push({ bairro });',
'      if (category) where.AND.push({ category });',
'      if (bb) {',
'        where.AND.push({ lat: { gte: bb.minLat, lte: bb.maxLat } });',
'        where.AND.push({ lng: { gte: bb.minLng, lte: bb.maxLng } });',
'      }',
'      rows = await pm.model.findMany({ where, take: 5000, orderBy: { createdAt: "desc" } });',
'    } catch {',
'      rows = await pm.model.findMany({ take: 5000 }).catch(() => []);',
'    }',
'',
'    const out: any[] = [];',
'    for (const r of rows) {',
'      const st = normStatus((r as any)?.status);',
'      const ca = (r as any)?.createdAt ? new Date((r as any).createdAt) : null;',
'      const ua = (r as any)?.updatedAt ? new Date((r as any).updatedAt) : null;',
'      const inWindow = (ca && ca >= start && ca <= end) || (ua && ua >= start && ua <= end) || (!ca && !ua);',
'      if (!inWindow) continue;',
'      if (status !== "ALL" && st !== status) continue;',
'',
'      const b = pickStr(r, ["bairro","neighborhood","area","regiao","region"]);',
'      if (bairro && (!b || b.toLowerCase() !== bairro.toLowerCase())) continue;',
'',
'      const c = pickStr(r, ["category","kind","type","categoria"]);',
'      if (category && (!c || c.toLowerCase() !== category.toLowerCase())) continue;',
'',
'      const item = normalizeRow(r);',
'      if (bb && item.lat != null && item.lng != null) {',
'        if (item.lat < bb.minLat || item.lat > bb.maxLat || item.lng < bb.minLng || item.lng > bb.maxLng) continue;',
'      }',
'',
'      if (q) {',
'        const hay = (item.category + " " + item.bairro + " " + item.title + " " + item.description).toLowerCase();',
'        if (!hay.includes(q)) continue;',
'      }',
'',
'      out.push(item);',
'    }',
'',
'    out.sort((a: any, b: any) => {',
'      const sa = String(a.status || "");',
'      const sb = String(b.status || "");',
'      if (sa === sb) {',
'        const ta = a.updatedAt || a.createdAt || "";',
'        const tb = b.updatedAt || b.createdAt || "";',
'        return tb.localeCompare(ta);',
'      }',
'      if (sa === "OPEN") return -1;',
'      if (sb === "OPEN") return 1;',
'      return sa.localeCompare(sb);',
'    });',
'',
'    return NextResponse.json({ ok: true, items: out, meta: { pointModel: pm.key, days } });',
'  } catch (e) {',
'    const msg = asMsg(e);',
'    if (looksLikeMissingTable(msg)) return NextResponse.json({ ok: false, error: "db_not_ready", detail: msg }, { status: 503 });',
'    return NextResponse.json({ ok: false, error: "db_error", detail: msg }, { status: 500 });',
'  }',
'}',
''
)
WriteLines $apiMap $LApiMap
Write-Host "[PATCH] wrote /api/eco/points/map"

# ---------------- API: /api/eco/points/confirm ----------------
$LApiConfirm = @(
'import { NextResponse } from "next/server";',
'import { prisma } from "@/lib/prisma";',
'',
'export const runtime = "nodejs";',
'export const dynamic = "force-dynamic";',
'',
'function asMsg(e: unknown) {',
'  if (e instanceof Error) return e.message;',
'  try { return String(e); } catch { return "unknown"; }',
'}',
'function looksLikeMissingTable(msg: string) {',
'  const m = msg.toLowerCase();',
'  return m.includes("does not exist") || m.includes("no such table") || m.includes("p2021");',
'}',
'function getPointModel() {',
'  const pc: any = prisma as any;',
'  const candidates = ["ecoPoint", "ecoCriticalPoint", "criticalPoint", "ecoPonto", "ponto", "ecoPontoCritico"];',
'  for (const k of candidates) {',
'    const m = pc?.[k];',
'    if (m && typeof m.update === "function" && typeof m.findUnique === "function") return { key: k, model: m as any };',
'  }',
'  return null;',
'}',
'',
'async function tryInc(model: any, id: string, field: string) {',
'  try {',
'    const data: any = {};',
'    data[field] = { increment: 1 };',
'    const item = await model.update({ where: { id }, data });',
'    return { ok: true, mode: "inc:" + field, item };',
'  } catch {',
'    return { ok: false };',
'  }',
'}',
'',
'export async function POST(req: Request) {',
'  const body = (await req.json().catch(() => null)) as any;',
'  const id = String(body?.id || body?.pointId || "").trim();',
'  if (!id) return NextResponse.json({ ok: false, error: "bad_id" }, { status: 400 });',
'',
'  const pm = getPointModel();',
'  if (!pm?.model) return NextResponse.json({ ok: false, error: "model_not_ready" }, { status: 503 });',
'',
'  try {',
'    const fields = ["confirmations","confirmCount","votes","upvotes","confirmationsCount"];',
'    for (const f of fields) {',
'      const r = await tryInc(pm.model, id, f);',
'      if (r.ok) return NextResponse.json({ ok: true, item: r.item, meta: { pointModel: pm.key, mode: r.mode } });',
'    }',
'',
'    try {',
'      const cur = await pm.model.findUnique({ where: { id } });',
'      const meta = (cur as any)?.meta;',
'      const next = (meta && typeof meta === "object") ? meta : {};',
'      const n = Number((next as any).confirmations || 0) || 0;',
'      (next as any).confirmations = n + 1;',
'      (next as any).lastConfirmAt = new Date().toISOString();',
'      const item = await pm.model.update({ where: { id }, data: { meta: next } });',
'      return NextResponse.json({ ok: true, item, meta: { pointModel: pm.key, mode: "meta.confirmations" } });',
'    } catch { }',
'',
'    return NextResponse.json({ ok: true, meta: { pointModel: pm.key, mode: "noop" } });',
'  } catch (e) {',
'    const msg = asMsg(e);',
'    if (looksLikeMissingTable(msg)) return NextResponse.json({ ok: false, error: "db_not_ready", detail: msg }, { status: 503 });',
'    return NextResponse.json({ ok: false, error: "db_error", detail: msg }, { status: 500 });',
'  }',
'}',
''
)
WriteLines $apiConfirm $LApiConfirm
Write-Host "[PATCH] wrote /api/eco/points/confirm"

# ---------------- API: /api/eco/points/report (dedupe) ----------------
$LApiReport = @(
'import { NextResponse } from "next/server";',
'import { prisma } from "@/lib/prisma";',
'',
'export const runtime = "nodejs";',
'export const dynamic = "force-dynamic";',
'',
'function asMsg(e: unknown) {',
'  if (e instanceof Error) return e.message;',
'  try { return String(e); } catch { return "unknown"; }',
'}',
'function looksLikeMissingTable(msg: string) {',
'  const m = msg.toLowerCase();',
'  return m.includes("does not exist") || m.includes("no such table") || m.includes("p2021");',
'}',
'function getPointModel() {',
'  const pc: any = prisma as any;',
'  const candidates = ["ecoPoint", "ecoCriticalPoint", "criticalPoint", "ecoPonto", "ponto", "ecoPontoCritico"];',
'  for (const k of candidates) {',
'    const m = pc?.[k];',
'    if (m && typeof m.create === "function" && typeof m.findMany === "function") return { key: k, model: m as any };',
'  }',
'  return null;',
'}',
'function safeStr(v: any, maxLen: number) {',
'  const s = String(v || "").trim();',
'  if (!s) return "";',
'  return s.length > maxLen ? s.slice(0, maxLen) : s;',
'}',
'function safeNum(v: any) {',
'  const n = Number(v);',
'  if (!Number.isFinite(n)) return null;',
'  return n;',
'}',
'function clamp(n: number, a: number, b: number) { return Math.max(a, Math.min(b, n)); }',
'function toRad(x: number) { return (x * Math.PI) / 180; }',
'function haversineMeters(aLat: number, aLng: number, bLat: number, bLng: number) {',
'  const R = 6371000;',
'  const dLat = toRad(bLat - aLat);',
'  const dLng = toRad(bLng - aLng);',
'  const s1 = Math.sin(dLat / 2);',
'  const s2 = Math.sin(dLng / 2);',
'  const aa = s1 * s1 + Math.cos(toRad(aLat)) * Math.cos(toRad(bLat)) * s2 * s2;',
'  const c = 2 * Math.atan2(Math.sqrt(aa), Math.sqrt(1 - aa));',
'  return R * c;',
'}',
'',
'export async function POST(req: Request) {',
'  const body = (await req.json().catch(() => null)) as any;',
'  const category = safeStr(body?.category || body?.kind || body?.type || "", 60);',
'  const bairro = safeStr(body?.bairro || body?.neighborhood || "", 80);',
'  const description = safeStr(body?.description || body?.note || body?.details || "", 500);',
'  const title = safeStr(body?.title || body?.name || "", 120);',
'  const evidenceUrl = safeStr(body?.evidenceUrl || body?.photoUrl || "", 400);',
'',
'  const lat0 = safeNum(body?.lat ?? body?.latitude);',
'  const lng0 = safeNum(body?.lng ?? body?.lon ?? body?.longitude);',
'  const radiusM = clamp(Number(body?.radiusM || 80) || 80, 20, 300);',
'  const windowHours = clamp(Number(body?.windowHours || 24) || 24, 1, 168);',
'',
'  if (!category) return NextResponse.json({ ok: false, error: "bad_category" }, { status: 400 });',
'  if (lat0 == null || lng0 == null) return NextResponse.json({ ok: false, error: "bad_geo", hint: "Envie lat/lng." }, { status: 400 });',
'  if (lat0 < -90 || lat0 > 90 || lng0 < -180 || lng0 > 180) return NextResponse.json({ ok: false, error: "bad_geo_range" }, { status: 400 });',
'  if (!description && !title) return NextResponse.json({ ok: false, error: "missing_text", hint: "Envie description ou title." }, { status: 400 });',
'',
'  const pm = getPointModel();',
'  if (!pm?.model) return NextResponse.json({ ok: false, error: "model_not_ready" }, { status: 503 });',
'',
'  const now = new Date();',
'  const start = new Date(now.getTime() - windowHours * 60 * 60 * 1000);',
'',
'  const dLat = radiusM / 111320;',
'  const dLng = radiusM / (111320 * Math.max(0.2, Math.cos(toRad(lat0))));',
'  const minLat = lat0 - dLat;',
'  const maxLat = lat0 + dLat;',
'  const minLng = lng0 - dLng;',
'  const maxLng = lng0 + dLng;',
'',
'  try {',
'    let candidates: any[] = [];',
'    try {',
'      candidates = await pm.model.findMany({',
'        where: {',
'          AND: [',
'            { createdAt: { gte: start, lte: now } },',
'            { lat: { gte: minLat, lte: maxLat } },',
'            { lng: { gte: minLng, lte: maxLng } },',
'          ],',
'        },',
'        take: 200,',
'        orderBy: { createdAt: "desc" },',
'      });',
'    } catch {',
'      candidates = await pm.model.findMany({ take: 500 }).catch(() => []);',
'    }',
'',
'    let best: any = null;',
'    let bestDist = 1e18;',
'    for (const r of candidates) {',
'      const lat = Number((r as any)?.lat ?? (r as any)?.latitude);',
'      const lng = Number((r as any)?.lng ?? (r as any)?.lon ?? (r as any)?.longitude);',
'      if (!Number.isFinite(lat) || !Number.isFinite(lng)) continue;',
'      const ca = (r as any)?.createdAt ? new Date((r as any).createdAt) : null;',
'      if (ca && (ca < start || ca > now)) continue;',
'      const dist = haversineMeters(lat0, lng0, lat, lng);',
'      if (dist <= radiusM && dist < bestDist) { best = r; bestDist = dist; }',
'    }',
'',
'    if (best) {',
'      try {',
'        await fetch(new URL("/api/eco/points/confirm", req.url).toString(), {',
'          method: "POST",',
'          headers: { "Content-Type": "application/json" },',
'          body: JSON.stringify({ id: String((best as any).id || "") }),',
'        });',
'      } catch { }',
'      return NextResponse.json({ ok: true, deduped: true, radiusM, windowHours, item: best, meta: { pointModel: pm.key, distanceM: Math.round(bestDist) } });',
'    }',
'',
'    const baseData: any = {',
'      status: "OPEN",',
'      category,',
'      bairro: bairro || undefined,',
'      title: title || undefined,',
'      description: description || undefined,',
'      evidenceUrl: evidenceUrl || undefined,',
'      lat: lat0,',
'      lng: lng0,',
'    };',
'',
'    try {',
'      const item = await pm.model.create({ data: baseData });',
'      return NextResponse.json({ ok: true, deduped: false, item, meta: { pointModel: pm.key, mode: "baseData" } });',
'    } catch {',
'      try {',
'        const data2: any = { status: "OPEN", category, bairro: bairro || undefined, description: description || undefined, lat: lat0, lng: lng0 };',
'        const item = await pm.model.create({ data: data2 });',
'        return NextResponse.json({ ok: true, deduped: false, item, meta: { pointModel: pm.key, mode: "fallback2" } });',
'      } catch {',
'        const data3: any = { status: "OPEN", category, lat: lat0, lng: lng0 };',
'        const item = await pm.model.create({ data: data3 });',
'        return NextResponse.json({ ok: true, deduped: false, item, meta: { pointModel: pm.key, mode: "fallback3" } });',
'      }',
'    }',
'  } catch (e) {',
'    const msg = asMsg(e);',
'    if (looksLikeMissingTable(msg)) return NextResponse.json({ ok: false, error: "db_not_ready", detail: msg }, { status: 503 });',
'    return NextResponse.json({ ok: false, error: "db_error", detail: msg }, { status: 500 });',
'  }',
'}',
''
)
WriteLines $apiReport $LApiReport
Write-Host "[PATCH] wrote /api/eco/points/report"

# ---------------- UI: /eco/mapa ----------------
$LPage = @(
'import MapaClient from "./MapaClient";',
'',
'export default async function Page() {',
'  return (',
'    <main style={{ padding: 16, maxWidth: 1100, margin: "0 auto" }}>',
'      <h1 style={{ margin: "0 0 8px 0" }}>Mapa do Abandono x Mapa do Cuidado</h1>',
'      <p style={{ margin: "0 0 14px 0", opacity: 0.85 }}>',
'        Abandono = pontos abertos. Cuidado = resolucoes e confirmacao comunitaria. Recibo e lei.',
'      </p>',
'      <MapaClient />',
'    </main>',
'  );',
'}',
''
)
WriteLines $pageMapa $LPage
Write-Host "[PATCH] wrote /eco/mapa/page.tsx"

$LClient = @(
'"use client";',
'',
'import { useEffect, useMemo, useState } from "react";',
'',
'type Item = {',
'  id: string;',
'  status: string;',
'  category: string;',
'  bairro: string;',
'  title: string;',
'  description: string;',
'  evidenceUrl: string;',
'  lat: number | null;',
'  lng: number | null;',
'  createdAt: string | null;',
'  updatedAt: string | null;',
'  confirmations: number;',
'};',
'',
'function fmtDate(s: string | null) {',
'  if (!s) return "";',
'  try {',
'    const d = new Date(s);',
'    return d.toLocaleString();',
'  } catch {',
'    return s;',
'  }',
'}',
'',
'export default function MapaClient() {',
'  const [items, setItems] = useState<Item[]>([]);',
'  const [loading, setLoading] = useState(false);',
'  const [err, setErr] = useState<string | null>(null);',
'',
'  const [days, setDays] = useState<number>(30);',
'  const [status, setStatus] = useState<string>("ALL");',
'  const [q, setQ] = useState<string>("");',
'  const [bairro, setBairro] = useState<string>("");',
'  const [category, setCategory] = useState<string>("");',
'',
'  const [repCategory, setRepCategory] = useState<string>("Lixo acumulado");',
'  const [repBairro, setRepBairro] = useState<string>("");',
'  const [repText, setRepText] = useState<string>("");',
'  const [repLat, setRepLat] = useState<string>("");',
'  const [repLng, setRepLng] = useState<string>("");',
'  const [repMsg, setRepMsg] = useState<string>("");',
'',
'  async function load() {',
'    setLoading(true);',
'    setErr(null);',
'    try {',
'      const qs = new URLSearchParams();',
'      qs.set("days", String(days));',
'      qs.set("status", status);',
'      if (q.trim()) qs.set("q", q.trim());',
'      if (bairro.trim()) qs.set("bairro", bairro.trim());',
'      if (category.trim()) qs.set("category", category.trim());',
'      const res = await fetch("/api/eco/points/map?" + qs.toString(), { cache: "no-store" } as any);',
'      const j = await res.json().catch(() => null);',
'      if (!res.ok || !j?.ok) throw new Error(j?.detail || j?.error || ("HTTP " + res.status));',
'      setItems((j.items || []) as Item[]);',
'    } catch (e: any) {',
'      setErr(e?.message || String(e));',
'    } finally {',
'      setLoading(false);',
'    }',
'  }',
'',
'  useEffect(() => { void load(); }, []);',
'',
'  async function confirm(id: string) {',
'    setErr(null);',
'    try {',
'      const res = await fetch("/api/eco/points/confirm", {',
'        method: "POST",',
'        headers: { "Content-Type": "application/json" },',
'        body: JSON.stringify({ id }),',
'      });',
'      const j = await res.json().catch(() => null);',
'      if (!res.ok || !j?.ok) throw new Error(j?.detail || j?.error || ("HTTP " + res.status));',
'      await load();',
'    } catch (e: any) {',
'      setErr(e?.message || String(e));',
'    }',
'  }',
'',
'  async function useMyLocation() {',
'    setRepMsg("");',
'    try {',
'      if (!navigator.geolocation) throw new Error("Geolocation nao disponivel no navegador.");',
'      navigator.geolocation.getCurrentPosition(',
'        (pos) => {',
'          const lat = String(pos.coords.latitude);',
'          const lng = String(pos.coords.longitude);',
'          setRepLat(lat);',
'          setRepLng(lng);',
'          setRepMsg("Localizacao preenchida.");',
'        },',
'        (e) => {',
'          setRepMsg("Falha ao obter localizacao: " + String((e as any).message || e));',
'        },',
'        { enableHighAccuracy: true, timeout: 12000 }',
'      );',
'    } catch (e: any) {',
'      setRepMsg(e?.message || String(e));',
'    }',
'  }',
'',
'  async function report() {',
'    setErr(null);',
'    setRepMsg("");',
'    try {',
'      const lat = Number(repLat);',
'      const lng = Number(repLng);',
'      if (!Number.isFinite(lat) || !Number.isFinite(lng)) throw new Error("Preencha lat/lng (ou use Minha localizacao).");',
'      if (!repCategory.trim()) throw new Error("Selecione a categoria.");',
'      if (!repText.trim() || repText.trim().length < 6) throw new Error("Descreva melhor (>= 6 caracteres).");',
'',
'      const res = await fetch("/api/eco/points/report", {',
'        method: "POST",',
'        headers: { "Content-Type": "application/json" },',
'        body: JSON.stringify({',
'          category: repCategory,',
'          bairro: repBairro.trim() || undefined,',
'          description: repText.trim(),',
'          lat,',
'          lng,',
'          radiusM: 80,',
'          windowHours: 24,',
'        }),',
'      });',
'      const j = await res.json().catch(() => null);',
'      if (!res.ok || !j?.ok) throw new Error(j?.detail || j?.error || ("HTTP " + res.status));',
'',
'      if (j.deduped) {',
'        setRepMsg("Ja existe um ponto parecido aqui (dedupe). Contou como confirmacao.");',
'      } else {',
'        setRepMsg("Ponto criado. Obrigado por registrar com prova.");',
'      }',
'',
'      setRepText("");',
'      await load();',
'    } catch (e: any) {',
'      setErr(e?.message || String(e));',
'    }',
'  }',
'',
'  const stats = useMemo(() => {',
'    let open = 0;',
'    let resolved = 0;',
'    for (const it of items) {',
'      const st = String(it.status || "");',
'      if (st === "OPEN") open += 1;',
'      if (st === "RESOLVED") resolved += 1;',
'    }',
'    return { open, resolved, total: items.length };',
'  }, [items]);',
'',
'  return (',
'    <section style={{ display: "grid", gap: 14 }}>',
'      <div style={{ padding: 12, border: "1px solid #e5e5e5", borderRadius: 12, background: "#fff" }}>',
'        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", gap: 10, flexWrap: "wrap" }}>',
'          <div style={{ fontWeight: 900 }}>Filtros</div>',
'          <button onClick={() => void load()} disabled={loading} style={{ padding: "6px 10px", borderRadius: 10, border: "1px solid #ccc", background: "#fff" }}>',
'            Atualizar',
'          </button>',
'        </div>',
'',
'        <div style={{ marginTop: 10, display: "grid", gridTemplateColumns: "repeat(4, minmax(0, 1fr))", gap: 10 }}>',
'          <label style={{ display: "grid", gap: 6 }}>',
'            <span>Dias</span>',
'            <input value={String(days)} onChange={(e) => setDays(Number((e.target as any).value) || 30)} style={{ padding: 10, borderRadius: 10, border: "1px solid #ccc" }} />',
'          </label>',
'          <label style={{ display: "grid", gap: 6 }}>',
'            <span>Status</span>',
'            <select value={status} onChange={(e) => setStatus((e.target as any).value)} style={{ padding: 10, borderRadius: 10, border: "1px solid #ccc" }}>',
'              <option value="ALL">Todos</option>',
'              <option value="OPEN">Abertos (Abandono)</option>',
'              <option value="RESOLVED">Resolvidos (Cuidado)</option>',
'            </select>',
'          </label>',
'          <label style={{ display: "grid", gap: 6 }}>',
'            <span>Bairro</span>',
'            <input value={bairro} onChange={(e) => setBairro((e.target as any).value)} placeholder="ex: Aterrado" style={{ padding: 10, borderRadius: 10, border: "1px solid #ccc" }} />',
'          </label>',
'          <label style={{ display: "grid", gap: 6 }}>',
'            <span>Categoria</span>',
'            <input value={category} onChange={(e) => setCategory((e.target as any).value)} placeholder="ex: Entulho" style={{ padding: 10, borderRadius: 10, border: "1px solid #ccc" }} />',
'          </label>',
'        </div>',
'',
'        <div style={{ marginTop: 10, display: "flex", gap: 10, alignItems: "center", flexWrap: "wrap" }}>',
'          <input value={q} onChange={(e) => setQ((e.target as any).value)} placeholder="buscar (texto livre)" style={{ flex: "1 1 220px", padding: 10, borderRadius: 10, border: "1px solid #ccc" }} />',
'          <button onClick={() => void load()} disabled={loading} style={{ padding: "10px 12px", borderRadius: 12, border: "1px solid #111", background: "#111", color: "#fff" }}>',
'            Aplicar',
'          </button>',
'          <div style={{ opacity: 0.75, fontSize: 12 }}>',
'            {stats.total} itens - abertos {stats.open} - resolvidos {stats.resolved}',
'          </div>',
'        </div>',
'',
'        {err ? <div style={{ marginTop: 10, color: "#b00020" }}>{err}</div> : null}',
'      </div>',
'',
'      <div style={{ padding: 12, border: "1px solid #e5e5e5", borderRadius: 12, background: "#fff" }}>',
'        <div style={{ fontWeight: 900, marginBottom: 8 }}>Registrar ponto (dedupe anti-caos)</div>',
'        <div style={{ opacity: 0.8, fontSize: 12, marginBottom: 10 }}>',
'          Se ja existir um ponto no mesmo lugar nas ultimas 24h (raio 80m), evita duplicar e conta como confirmacao.',
'        </div>',
'',
'        <div style={{ display: "grid", gridTemplateColumns: "repeat(2, minmax(0, 1fr))", gap: 10 }}>',
'          <label style={{ display: "grid", gap: 6 }}>',
'            <span>Categoria</span>',
'            <select value={repCategory} onChange={(e) => setRepCategory((e.target as any).value)} style={{ padding: 10, borderRadius: 10, border: "1px solid #ccc" }}>',
'              <option>Lixo acumulado</option>',
'              <option>Entulho/volumoso</option>',
'              <option>Queimada/fumaca</option>',
'              <option>Esgoto/vazamento</option>',
'              <option>Oleo/quimico</option>',
'              <option>Sensivel/industrial</option>',
'            </select>',
'          </label>',
'          <label style={{ display: "grid", gap: 6 }}>',
'            <span>Bairro (opcional)</span>',
'            <input value={repBairro} onChange={(e) => setRepBairro((e.target as any).value)} placeholder="ex: Retiro" style={{ padding: 10, borderRadius: 10, border: "1px solid #ccc" }} />',
'          </label>',
'        </div>',
'',
'        <label style={{ display: "grid", gap: 6, marginTop: 10 }}>',
'          <span>Descricao (o que esta acontecendo)</span>',
'          <textarea value={repText} onChange={(e) => setRepText((e.target as any).value)} rows={3} placeholder="Descreva o ponto e o risco" style={{ padding: 10, borderRadius: 10, border: "1px solid #ccc" }} />',
'        </label>',
'',
'        <div style={{ marginTop: 10, display: "grid", gridTemplateColumns: "repeat(3, minmax(0, 1fr))", gap: 10, alignItems: "end" }}>',
'          <label style={{ display: "grid", gap: 6 }}>',
'            <span>Lat</span>',
'            <input value={repLat} onChange={(e) => setRepLat((e.target as any).value)} placeholder="-22.5..." style={{ padding: 10, borderRadius: 10, border: "1px solid #ccc" }} />',
'          </label>',
'          <label style={{ display: "grid", gap: 6 }}>',
'            <span>Lng</span>',
'            <input value={repLng} onChange={(e) => setRepLng((e.target as any).value)} placeholder="-44.1..." style={{ padding: 10, borderRadius: 10, border: "1px solid #ccc" }} />',
'          </label>',
'          <div style={{ display: "flex", gap: 10, flexWrap: "wrap" }}>',
'            <button onClick={() => void useMyLocation()} style={{ padding: "10px 12px", borderRadius: 12, border: "1px solid #111", background: "#fff", color: "#111" }}>',
'              Minha localizacao',
'            </button>',
'            <button onClick={() => void report()} style={{ padding: "10px 12px", borderRadius: 12, border: "1px solid #111", background: "#111", color: "#fff" }}>',
'              Registrar',
'            </button>',
'          </div>',
'        </div>',
'',
'        {repMsg ? <div style={{ marginTop: 10, opacity: 0.85 }}>{repMsg}</div> : null}',
'      </div>',
'',
'      <div style={{ padding: 12, border: "1px solid #e5e5e5", borderRadius: 12, background: "#fff" }}>',
'        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", gap: 10, flexWrap: "wrap" }}>',
'          <div style={{ fontWeight: 900 }}>Lista (v0)</div>',
'          <div style={{ opacity: 0.7, fontSize: 12 }}>Dica: use Abrir no mapa para navegar e provar local.</div>',
'        </div>',
'',
'        {loading ? <div style={{ marginTop: 10, opacity: 0.75 }}>Carregando...</div> : null}',
'',
'        <div style={{ marginTop: 10, display: "grid", gap: 10 }}>',
'          {items.map((it) => {',
'            const isOpen = String(it.status || "") === "OPEN";',
'            const mapsHref = (it.lat != null && it.lng != null) ? ("https://www.google.com/maps?q=" + String(it.lat) + "," + String(it.lng)) : "#";',
'            const detailHref = "/eco/pontos/" + it.id;',
'            return (',
'              <div key={it.id} style={{ border: "1px solid #111", borderRadius: 12, padding: 10 }}>',
'                <div style={{ display: "flex", justifyContent: "space-between", gap: 10, flexWrap: "wrap", alignItems: "center" }}>',
'                  <div style={{ fontWeight: 900 }}>{isOpen ? "ABANDONO" : "CUIDADO"} - {it.category || "-"} {it.bairro ? ("- " + it.bairro) : ""}</div>',
'                  <div style={{ fontSize: 12, opacity: 0.75 }}>{fmtDate(it.updatedAt || it.createdAt)}</div>',
'                </div>',
'                <div style={{ marginTop: 6, opacity: 0.95 }}>{it.title ? it.title : it.description}</div>',
'                {it.title && it.description ? <div style={{ marginTop: 4, opacity: 0.85 }}>{it.description}</div> : null}',
'',
'                <div style={{ marginTop: 8, display: "flex", gap: 10, flexWrap: "wrap" }}>',
'                  <button onClick={() => void confirm(it.id)} style={{ padding: "8px 10px", borderRadius: 10, border: "1px solid #111", background: "#fff" }}>',
'                    Eu vi tambem ({Number(it.confirmations || 0)})',
'                  </button>',
'                  <a href={mapsHref} target="_blank" rel="noreferrer" style={{ textDecoration: "none", padding: "8px 10px", borderRadius: 10, border: "1px solid #111", color: "#111" }}>',
'                    Abrir no mapa',
'                  </a>',
'                  <a href={detailHref} style={{ textDecoration: "none", padding: "8px 10px", borderRadius: 10, border: "1px solid #111", color: "#111" }}>',
'                    Ver detalhe',
'                  </a>',
'                </div>',
'              </div>',
'            );',
'          })}',
'          {items.length === 0 ? <div style={{ opacity: 0.75 }}>Nenhum ponto no filtro.</div> : null}',
'        </div>',
'      </div>',
'    </section>',
'  );',
'}',
''
)
WriteLines $clientMapa $LClient
Write-Host "[PATCH] wrote /eco/mapa/MapaClient.tsx"

# REPORT
$rep = Join-Path $reportDir ("eco-step-69b-mapa-fix-quotes-v0_1-" + $ts + ".md")
$repLines = @(
"# eco-step-69b-mapa-abandono-x-cuidado-fix-quotes-v0_1",
"",
"- Time: " + $ts,
"- Backup: " + $backupDir,
"- UI: /eco/mapa",
"- API: /api/eco/points/map",
"- API: /api/eco/points/report",
"- API: /api/eco/points/confirm",
"",
"## Verify",
"1) Ctrl+C -> npm run dev",
"2) GET /api/eco/points/map?days=30&status=ALL",
"3) Abra /eco/mapa e registre um ponto com Minha localizacao"
)
WriteUtf8NoBom $rep ($repLines -join "`n")
Write-Host ("[REPORT] " + $rep)

Write-Host ""
Write-Host "[VERIFY] Ctrl+C -> npm run dev"
Write-Host "[VERIFY] Abra http://localhost:3000/eco/mapa"
Write-Host "[VERIFY] irm `"http://localhost:3000/api/eco/points/map?days=30&status=ALL`" -Headers @{Accept=`"application/json`"}"