param([string]$Root = (Get-Location).Path)

$ts = Get-Date -Format "yyyyMMdd-HHmmss"
Write-Host ("== eco-step-106c-fix-seed-eco-pragma-string-v0_2 == " + $ts)
Write-Host ("[DIAG] Root: " + $Root)

$boot = Join-Path $Root "tools/_bootstrap.ps1"
if (Test-Path -LiteralPath $boot) { . $boot }

if (-not (Get-Command EnsureDir -ErrorAction SilentlyContinue)) {
  function EnsureDir([string]$p) { if (-not (Test-Path -LiteralPath $p)) { New-Item -ItemType Directory -Force -Path $p | Out-Null } }
}
if (-not (Get-Command WriteUtf8NoBom -ErrorAction SilentlyContinue)) {
  function WriteUtf8NoBom([string]$p, [string]$content) {
    EnsureDir (Split-Path -Parent $p)
    $enc = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($p, $content, $enc)
  }
}
if (-not (Get-Command BackupFile -ErrorAction SilentlyContinue)) {
  function BackupFile([string]$root, [string]$p, [string]$backupDir) {
    if (Test-Path -LiteralPath $p) {
      $rel = $p.Substring($root.Length).TrimStart('\','/')
      $dest = Join-Path $backupDir ($rel -replace '[\\/]', '__')
      Copy-Item -Force -LiteralPath $p -Destination $dest
      Write-Host ('[BK] ' + $rel + ' -> ' + (Split-Path -Leaf $dest))
    }
  }
}

$backupDir = Join-Path $Root ("tools/_patch_backup/" + $ts + "-eco-step-106c-fix-seed-eco-pragma-string-v0_2")
$reportDir = Join-Path $Root "reports"
EnsureDir $backupDir
EnsureDir $reportDir

$target = Join-Path $Root "src/app/api/dev/seed-eco/route.ts"
if (-not (Test-Path -LiteralPath $target)) { throw "[STOP] Nao achei: src/app/api/dev/seed-eco/route.ts" }

BackupFile $Root $target $backupDir

# Write route.ts (NO \" escapes; PRAGMA uses table_info("TABLE") with TS single quotes)
$lines = @(
'import { NextResponse } from "next/server";',
'import { prisma } from "@/lib/prisma";',
'',
'export const runtime = "nodejs";',
'export const dynamic = "force-dynamic";',
'',
'type TI = { cid: number; name: string; type: string; notnull: number; dflt_value: any; pk: number };',
'',
'function escSql(v: string): string {',
'  // SQLite string literal escape for single quotes',
'  return String(v || "").replace(/''/g, "''''");',
'}',
'',
'function toTableName(accessor: string): string {',
'  if (!accessor) return accessor;',
'  return accessor.charAt(0).toUpperCase() + accessor.slice(1);',
'}',
'',
'function pickModel(pc: any, prefer: string, candidates: string[]) {',
'  const names = [prefer, ...(candidates || [])].filter(Boolean);',
'  for (const n of names) {',
'    const m = pc?.[n];',
'    if (m) return { name: n, model: m };',
'  }',
'  for (const n of names) {',
'    const p = toTableName(n);',
'    const m = pc?.[p];',
'    if (m) return { name: p, model: m };',
'  }',
'  return null;',
'}',
'',
'async function findExistingTable(candidates: string[]): Promise<string | null> {',
'  for (const t of candidates.filter(Boolean)) {',
'    try {',
'      const q = "SELECT name FROM sqlite_master WHERE type=''table'' AND name=''" + escSql(t) + "'' LIMIT 1";',
'      const rows = await prisma.$queryRawUnsafe<any[]>(q);',
'      if (Array.isArray(rows) && rows.length > 0 && rows[0]?.name) return String(rows[0].name);',
'    } catch {',
'      // ignore',
'    }',
'  }',
'  return null;',
'}',
'',
'async function tableInfo(table: string): Promise<TI[]> {',
'  // IMPORTANT: avoid any \\" escaping in TS source',
'  const q = ''PRAGMA table_info("'' + escSql(table) + ''")'';',
'  const rows = await prisma.$queryRawUnsafe<any[]>(q);',
'  return (Array.isArray(rows) ? rows : []) as TI[];',
'}',
'',
'function has(cols: TI[], n: string): boolean {',
'  return cols.some(c => c.name === n);',
'}',
'',
'function setIf(o: any, cols: TI[], n: string, v: any) {',
'  if (has(cols, n) && typeof o[n] === "undefined") o[n] = v;',
'}',
'',
'function makeId(prefix: string) {',
'  return prefix + "-" + Date.now().toString(36) + "-" + Math.random().toString(36).slice(2, 8);',
'}',
'',
'function fillRequired(o: any, cols: TI[]) {',
'  for (const c of cols) {',
'    const name = c.name;',
'    if (c.pk === 1) continue;',
'    if (c.notnull !== 1) continue;',
'    if (c.dflt_value !== null && typeof c.dflt_value !== "undefined") continue;',
'    if (typeof o[name] !== "undefined") continue;',
'    const t = String(c.type || "").toUpperCase();',
'    if (t.includes("INT")) o[name] = 0;',
'    else if (t.includes("REAL") || t.includes("FLOA") || t.includes("DOUB")) o[name] = 0;',
'    else o[name] = "";',
'  }',
'}',
'',
'function makePointData(cols: TI[], idx: number) {',
'  const now = new Date();',
'  const o: any = {};',
'  setIf(o, cols, "id", makeId("p"));',
'  setIf(o, cols, "createdAt", now);',
'  setIf(o, cols, "updatedAt", now);',
'  setIf(o, cols, "created_at", now);',
'  setIf(o, cols, "updated_at", now);',
'',
'  const title = "Ponto critico " + (idx + 1);',
'  setIf(o, cols, "title", title);',
'  setIf(o, cols, "name", title);',
'  setIf(o, cols, "label", title);',
'',
'  const desc = "Seed dev: descarte irregular / lixo acumulado (teste).";',
'  setIf(o, cols, "description", desc);',
'  setIf(o, cols, "desc", desc);',
'  setIf(o, cols, "text", desc);',
'',
'  setIf(o, cols, "bairro", "Centro");',
'  setIf(o, cols, "neighborhood", "Centro");',
'  setIf(o, cols, "city", "Volta Redonda");',
'  setIf(o, cols, "municipio", "Volta Redonda");',
'',
'  setIf(o, cols, "lat", -22.520);',
'  setIf(o, cols, "lng", -44.104);',
'  setIf(o, cols, "latitude", -22.520);',
'  setIf(o, cols, "longitude", -44.104);',
'',
'  if (has(cols, "status")) o["status"] = "OPEN";',
'  else if (has(cols, "state")) o["state"] = "OPEN";',
'  else if (has(cols, "situacao")) o["situacao"] = "OPEN";',
'',
'  fillRequired(o, cols);',
'  return o;',
'}',
'',
'function pickFk(cols: TI[]) {',
'  const prefer = ["pointId", "criticalPointId", "ecoCriticalPointId", "pontoId"];',
'  for (const k of prefer) if (has(cols, k)) return k;',
'  for (const c of cols) {',
'    if (/pointid$/i.test(c.name)) return c.name;',
'  }',
'  return null;',
'}',
'',
'function makeActionData(cols: TI[], fk: string, pointId: string, kind: string) {',
'  const now = new Date();',
'  const o: any = {};',
'  setIf(o, cols, "id", makeId(kind));',
'  setIf(o, cols, "createdAt", now);',
'  setIf(o, cols, "updatedAt", now);',
'  setIf(o, cols, "created_at", now);',
'  setIf(o, cols, "updated_at", now);',
'  o[fk] = pointId;',
'  setIf(o, cols, "kind", kind.toUpperCase());',
'  setIf(o, cols, "type", kind.toUpperCase());',
'  setIf(o, cols, "value", 1);',
'  setIf(o, cols, "note", "seed dev");',
'  fillRequired(o, cols);',
'  return o;',
'}',
'',
'export async function GET(req: Request) {',
'  try {',
'    const url = new URL(req.url);',
'    const n = Math.max(0, Math.min(50, Number(url.searchParams.get("n") || "3")));',
'    const confirmEach = Math.max(0, Math.min(5, Number(url.searchParams.get("confirm") || "1")));',
'    const supportEach = Math.max(0, Math.min(5, Number(url.searchParams.get("support") || "1")));',
'    const replicarEach = Math.max(0, Math.min(5, Number(url.searchParams.get("replicar") || "0")));',
'',
'    const pc: any = prisma as any;',
'    const pointPick = pickModel(pc, "ecoCriticalPoint", ["criticalPoint", "ecoPoint", "point"]);',
'    const confirmPick = pickModel(pc, "ecoCriticalPointConfirm", ["ecoPointConfirm", "criticalPointConfirm", "pointConfirm"]);',
'    const supportPick = pickModel(pc, "ecoPointSupport", ["pointSupport"]);',
'    const replicarPick = pickModel(pc, "ecoPointReplicate", ["ecoPointReplicar", "pointReplicate", "pointReplicar"]);',
'',
'    if (!pointPick) {',
'      return NextResponse.json({ ok: false, error: "point_model_not_found" }, { status: 500 });',
'    }',
'',
'    const pointTable = (await findExistingTable([toTableName(pointPick.name), "EcoCriticalPoint", pointPick.name])) || toTableName(pointPick.name);',
'    const pointCols = await tableInfo(pointTable);',
'',
'    let confirmCols: TI[] = [];',
'    let supportCols: TI[] = [];',
'    let replicarCols: TI[] = [];',
'    let confirmFk: string | null = null;',
'    let supportFk: string | null = null;',
'    let replicarFk: string | null = null;',
'',
'    if (confirmPick) {',
'      const t = (await findExistingTable([toTableName(confirmPick.name), "EcoCriticalPointConfirm", confirmPick.name])) || toTableName(confirmPick.name);',
'      confirmCols = await tableInfo(t);',
'      confirmFk = pickFk(confirmCols);',
'    }',
'    if (supportPick) {',
'      const t = (await findExistingTable([toTableName(supportPick.name), "EcoPointSupport", supportPick.name])) || toTableName(supportPick.name);',
'      supportCols = await tableInfo(t);',
'      supportFk = pickFk(supportCols);',
'    }',
'    if (replicarPick) {',
'      const t = (await findExistingTable([toTableName(replicarPick.name), "EcoPointReplicate", "EcoPointReplicar", replicarPick.name])) || toTableName(replicarPick.name);',
'      replicarCols = await tableInfo(t);',
'      replicarFk = pickFk(replicarCols);',
'    }',
'',
'    const ids: string[] = [];',
'    let createdConfirm = 0;',
'    let createdSupport = 0;',
'    let createdReplicar = 0;',
'',
'    for (let i = 0; i < n; i++) {',
'      const data = makePointData(pointCols, i);',
'      const p = await pointPick.model.create({ data });',
'      const pid = String((p as any)?.id || (p as any)?.pointId || (p as any)?.criticalPointId || "");',
'      if (!pid) continue;',
'      ids.push(pid);',
'',
'      if (confirmPick && confirmFk && confirmEach > 0) {',
'        for (let k = 0; k < confirmEach; k++) {',
'          await confirmPick.model.create({ data: makeActionData(confirmCols, confirmFk, pid, "confirm") });',
'          createdConfirm++;',
'        }',
'      }',
'      if (supportPick && supportFk && supportEach > 0) {',
'        for (let k = 0; k < supportEach; k++) {',
'          await supportPick.model.create({ data: makeActionData(supportCols, supportFk, pid, "support") });',
'          createdSupport++;',
'        }',
'      }',
'      if (replicarPick && replicarFk && replicarEach > 0) {',
'        for (let k = 0; k < replicarEach; k++) {',
'          await replicarPick.model.create({ data: makeActionData(replicarCols, replicarFk, pid, "replicar") });',
'          createdReplicar++;',
'        }',
'      }',
'    }',
'',
'    return NextResponse.json({',
'      ok: true,',
'      created: { points: ids.length, confirm: createdConfirm, support: createdSupport, replicar: createdReplicar },',
'      ids: ids.slice(0, 20),',
'      meta: {',
'        pointModel: pointPick.name,',
'        confirmModel: confirmPick?.name || null,',
'        supportModel: supportPick?.name || null,',
'        replicarModel: replicarPick?.name || null,',
'      }',
'    });',
'  } catch (e: any) {',
'    return NextResponse.json({ ok: false, error: "seed_failed", message: String(e?.message || e) }, { status: 500 });',
'  }',
'}'
)

$content = ($lines -join "`n") + "`n"
WriteUtf8NoBom $target $content
Write-Host ("[PATCH] rewrote " + $target)

$rep = Join-Path $reportDir ("eco-step-106c-fix-seed-eco-pragma-string-v0_2-" + $ts + ".md")
$repText = @(
"# eco-step-106c-fix-seed-eco-pragma-string-v0_2",
"",
"- Time: " + $ts,
"- Backup: " + $backupDir,
"- Patched: src/app/api/dev/seed-eco/route.ts",
"",
"## Why",
"- Fix TS parse error caused by bad escaping in PRAGMA string.",
"- Uses PRAGMA table_info(""TABLE"") built with TS single-quoted string (no backslash-quote escapes).",
"",
"## Verify",
"1) Ctrl+C (stop dev) and run: npm run dev",
"2) irm 'http://localhost:3000/api/dev/seed-eco?n=3&confirm=1&support=1' | ConvertTo-Json -Depth 60",
"3) irm 'http://localhost:3000/api/eco/points?limit=5' | ConvertTo-Json -Depth 80",
"4) Open /eco/mural and /eco/mural/confirmados"
) -join "`n"
WriteUtf8NoBom $rep $repText
Write-Host ("[REPORT] " + $rep)

Write-Host ""
Write-Host "[VERIFY] Ctrl+C -> npm run dev"
Write-Host "[VERIFY] irm 'http://localhost:3000/api/dev/seed-eco?n=3&confirm=1&support=1' | ConvertTo-Json -Depth 60"
Write-Host "[VERIFY] irm 'http://localhost:3000/api/eco/points?limit=5' | ConvertTo-Json -Depth 80"