param(
  [string]$Root = (Get-Location).Path
)

$ErrorActionPreference = "Stop"

function EnsureDir([string]$p) {
  if (-not $p) { return }
  New-Item -ItemType Directory -Force -Path $p | Out-Null
}

function WriteUtf8NoBom([string]$file, [string]$content) {
  $enc = New-Object System.Text.UTF8Encoding($false)
  [System.IO.File]::WriteAllText($file, $content, $enc)
}

function BackupFile([string]$file, [string]$backupDir, [string]$root) {
  if (-not (Test-Path $file)) { return }
  $rel = $file
  if ($root -and $file.StartsWith($root)) {
    $rel = $file.Substring($root.Length).TrimStart("\","/")
  }
  $dest = Join-Path $backupDir $rel
  EnsureDir (Split-Path -Parent $dest)
  Copy-Item -Force $file $dest
}

$stamp = Get-Date -Format "yyyyMMdd-HHmmss"
$me = "eco-step-107g-fix-points-list-alias-and-front-safe-v0_1"
Write-Host ("== " + $me + " == " + $stamp)

$backupDir = Join-Path $Root ("tools\_patch_backup\" + $stamp + "-" + $me)
EnsureDir $backupDir

# --- DIAG: achar chamadas antigas no front
Write-Host "[DIAG] scanning src for '/api/eco/points/list'..."
$hits = @()
$srcRoot = Join-Path $Root "src"
if (Test-Path $srcRoot) {
  $files = Get-ChildItem -Recurse -File $srcRoot -ErrorAction SilentlyContinue
  foreach ($f in $files) {
    $raw = Get-Content -Raw -ErrorAction SilentlyContinue $f.FullName
    if ($raw -and $raw.Contains("/api/eco/points/list")) {
      $hits += $f.FullName
    }
  }
}
Write-Host ("[DIAG] hits=" + $hits.Count)
if ($hits.Count -gt 0) { $hits | % { Write-Host ("  - " + $_) } }

# --- PATCH 1: /api/eco/points/list vira alias de list2
$targetList  = Join-Path $Root "src\app\api\eco\points\list\route.ts"
$targetList2 = Join-Path $Root "src\app\api\eco\points\list2\route.ts"

if (-not (Test-Path $targetList2)) {
  throw ("[STOP] Não achei list2 em: " + $targetList2)
}

EnsureDir (Split-Path -Parent $targetList)
BackupFile $targetList $backupDir $Root

$aliasLines = @(
'// AUTO-GENERATED by tools/eco-step-107g-fix-points-list-alias-and-front-safe-v0_1.ps1',
'// Fix: /api/eco/points/list estava retornando 503 (model_not_ready).',
'// Agora vira alias do list2 (fonte de verdade).',
'',
'import { GET as GET_LIST2 } from "../list2/route";',
'',
'export const runtime = "nodejs";',
'export const dynamic = "force-dynamic";',
'',
'export async function GET(req: Request) {',
'  return GET_LIST2(req);',
'}',
''
)

WriteUtf8NoBom $targetList ($aliasLines -join "`n")
Write-Host ("[PATCH] aliased -> " + $targetList)

# --- PATCH 2: trocar no front "/api/eco/points/list" -> "/api/eco/points"
$changed = @()
foreach ($p in $hits) {
  $raw = Get-Content -Raw -ErrorAction Stop $p
  if (-not $raw) { continue }
  $new = $raw.Replace("/api/eco/points/list", "/api/eco/points")
  if ($new -ne $raw) {
    BackupFile $p $backupDir $Root
    WriteUtf8NoBom $p $new
    $changed += $p
    Write-Host ("[PATCH] updated -> " + $p)
  }
}

# --- REPORT
$reportDir = Join-Path $Root "reports"
EnsureDir $reportDir
$reportPath = Join-Path $reportDir ($me + "-" + $stamp + ".md")

$report = @()
$report += "# $me"
$report += ""
$report += "- Time: $stamp"
$report += "- Backup: $backupDir"
$report += ""
$report += "## What/Why"
$report += "- /api/eco/points/list estava quebrado (model_not_ready -> 503)."
$report += "- Agora /list é ALIAS de /list2 (fonte única)."
$report += "- E o front foi varrido pra trocar chamadas antigas de /list por /api/eco/points (compat)."
$report += ""
$report += "## Patched"
$report += "- src/app/api/eco/points/list/route.ts (alias para list2)"
if ($changed.Count -gt 0) {
  $report += "- Front files updated:"
  foreach ($c in $changed) { $report += "  - $c" }
} else {
  $report += "- Front files updated: (none found)"
}
$report += ""
$report += "## Verify"
$report += "1) Ctrl+C -> npm run dev"
$report += "2) irm 'http://localhost:3000/api/eco/points/list?limit=20' | ConvertTo-Json -Depth 40"
$report += "3) abrir /eco/mural e /eco/mural/confirmados (não pode aparecer 503 do list)"
$report += ""

WriteUtf8NoBom $reportPath ($report -join "`n")
Write-Host ("[REPORT] " + $reportPath)

Write-Host ""
Write-Host "[VERIFY] rode:"
Write-Host "  Ctrl+C -> npm run dev"
Write-Host "  irm 'http://localhost:3000/api/eco/points/list?limit=20' | ConvertTo-Json -Depth 40"
Write-Host "  abrir /eco/mural e /eco/mural/confirmados"