param(
  [string]$Root = (Get-Location).Path
)

function EnsureDir([string]$p) { if (-not (Test-Path $p)) { New-Item -ItemType Directory -Force -Path $p | Out-Null } }
function BackupFile([string]$p, [string]$backupDir) {
  if (Test-Path $p) {
    $rel = $p.Substring($Root.Length).TrimStart('\','/')
    $dest = Join-Path $backupDir ($rel -replace '[\\/]', '__')
    Copy-Item -Force -LiteralPath $p -Destination $dest
    Write-Host ("[BK] " + $rel + " -> " + (Split-Path -Leaf $dest))
  }
}

$ts = Get-Date -Format "yyyyMMdd-HHmmss"
$backupDir = Join-Path $Root ("tools/_patch_backup/" + $ts + "-eco-step-57-month-close-transparencia-v0_1")
$reportDir = Join-Path $Root "reports"
EnsureDir $backupDir
EnsureDir $reportDir

# Files
$apiClose = Join-Path $Root "src/app/api/eco/month-close/route.ts"
$apiList  = Join-Path $Root "src/app/api/eco/month-close/list/route.ts"
$apiCard  = Join-Path $Root "src/app/api/eco/month-close/card/route.tsx"
$uiPage   = Join-Path $Root "src/app/eco/transparencia/page.tsx"
$uiClient = Join-Path $Root "src/app/eco/transparencia/TransparenciaClient.tsx"

Write-Host ("[DIAG] Root: " + $Root)
Write-Host ("[DIAG] Will write: " + $apiClose)
Write-Host ("[DIAG] Will write: " + $apiList)
Write-Host ("[DIAG] Will write: " + $apiCard)
Write-Host ("[DIAG] Will write: " + $uiPage)
Write-Host ("[DIAG] Will write: " + $uiClient)

BackupFile $apiClose $backupDir
BackupFile $apiList $backupDir
BackupFile $apiCard $backupDir
BackupFile $uiPage $backupDir
BackupFile $uiClient $backupDir

$enc = New-Object System.Text.UTF8Encoding($false)

# ---------- Helpers we will embed in routes ----------
# We'll rely on prisma as any to avoid schema coupling.

# ---------------- month-close route ----------------
$L1 = @(
'// ECO — month-close (sum of day-close) — step 57',
'',
'import { NextResponse } from "next/server";',
'import { prisma } from "@/lib/prisma";',
'',
'export const runtime = "nodejs";',
'export const dynamic = "force-dynamic";',
'',
'function asMsg(e: unknown) {',
'  if (e instanceof Error) return e.message;',
'  try { return String(e); } catch { return "unknown"; }',
'}',
'',
'function looksLikeMissingTable(msg: string) {',
'  const m = msg.toLowerCase();',
'  return m.includes("does not exist") || m.includes("no such table") || m.includes("p2021");',
'}',
'',
'function getDayCloseModel() {',
'  const pc: any = prisma as any;',
'  return pc?.ecoDayClose;',
'}',
'',
'function getMonthCloseModel() {',
'  const pc: any = prisma as any;',
'  return pc?.ecoMonthClose;',
'}',
'',
'function safeMonth(input: string | null): string | null {',
'  const raw = String(input ?? "").trim();',
'  if (!raw) return null;',
'  const norm = raw.replace(/[‐-‒–—―]/g, "-").replace(/\//g, "-");',
'  const m = norm.match(/^(\d{4})-(\d{2})$/);',
'  if (!m) return null;',
'  const mo = Number(m[2]);',
'  if (mo < 1 || mo > 12) return null;',
'  return m[1] + "-" + m[2];',
'}',
'',
'function bump(obj: any, key: string, inc: number) {',
'  if (!obj[key]) obj[key] = 0;',
'  obj[key] += inc;',
'}',
'',
'function monthDayRange(month: string) {',
'  // month = YYYY-MM',
'  const start = new Date(month + "-01T00:00:00-03:00");',
'  const y = Number(month.slice(0,4));',
'  const m = Number(month.slice(5,7));',
'  const nextMonth = m === 12 ? (String(y + 1) + "-01") : (String(y) + "-" + String(m + 1).padStart(2,"0"));',
'  const end = new Date(nextMonth + "-01T00:00:00-03:00");',
'  return { start, endExclusive: end };',
'}',
'',
'async function computeMonthSummary(month: string) {',
'  const dayModel = getDayCloseModel();',
'  const { start, endExclusive } = monthDayRange(month);',
'',
'  const totals: any = { totalKg: 0, byMaterialKg: {}, days: 0 };',
'  const meta: any = { computedAt: new Date().toISOString(), source: [] as string[] };',
'',
'  if (!dayModel?.findMany) {',
'    meta.source.push("dayClose:missing");',
'    return { month, totals, meta, notes: [], version: "v0" };',
'  }',
'',
'  meta.source.push("dayClose:ecoDayClose");',
'  const rows = await dayModel.findMany({',
'    where: {',
'      // day é string YYYY-MM-DD -> filtra por prefixo',
'      day: { startsWith: month + "-" }',
'    },',
'    orderBy: { day: "asc" }',
'  });',
'',
'  totals.days = rows.length;',
'  for (const r of rows) {',
'    const s = (r as any)?.summary || {};',
'    const t = s?.totals || {};',
'    const kg = Number(t?.totalKg || 0) || 0;',
'    totals.totalKg += kg;',
'    const by = t?.byMaterialKg || {};',
'    if (by && typeof by === "object") {',
'      for (const k of Object.keys(by)) {',
'        bump(totals.byMaterialKg, k, Number(by[k] || 0) || 0);',
'      }',
'    }',
'  }',
'',
'  return { month, totals, meta, notes: [], version: "v0" };',
'}',
'',
'export async function GET(req: Request) {',
'  const { searchParams } = new URL(req.url);',
'  const month = safeMonth(searchParams.get("month") ?? searchParams.get("m"));',
'  const fresh = String(searchParams.get("fresh") || "").trim() === "1";',
'  if (!month) return NextResponse.json({ ok: false, error: "bad_month" }, { status: 400 });',
'',
'  const monthModel = getMonthCloseModel();',
'  if (!monthModel?.findUnique) {',
'    return NextResponse.json({ ok: false, error: "model_not_ready", hint: "missing ecoMonthClose model" }, { status: 503 });',
'  }',
'',
'  try {',
'    if (!fresh) {',
'      const row = await monthModel.findUnique({ where: { month } });',
'      if (row) return NextResponse.json({ ok: true, item: row, cached: true });',
'    }',
'    const summary = await computeMonthSummary(month);',
'    const item = await monthModel.upsert({',
'      where: { month },',
'      update: { summary },',
'      create: { month, summary },',
'    });',
'    return NextResponse.json({ ok: true, item, cached: false });',
'  } catch (e) {',
'    const msg = asMsg(e);',
'    if (looksLikeMissingTable(msg)) {',
'      return NextResponse.json({ ok: false, error: "db_not_ready", detail: msg }, { status: 503 });',
'    }',
'    return NextResponse.json({ ok: false, error: "db_error", detail: msg }, { status: 500 });',
'  }',
'}',
'',
'export async function POST(req: Request) {',
'  const body = (await req.json().catch(() => null)) as any;',
'  const month = safeMonth(body?.month ?? null);',
'  if (!month) return NextResponse.json({ ok: false, error: "bad_month" }, { status: 400 });',
'',
'  const monthModel = getMonthCloseModel();',
'  if (!monthModel?.upsert) {',
'    return NextResponse.json({ ok: false, error: "model_not_ready", hint: "missing ecoMonthClose model" }, { status: 503 });',
'  }',
'',
'  try {',
'    const summary = body?.summary ?? (await computeMonthSummary(month));',
'    const item = await monthModel.upsert({',
'      where: { month },',
'      update: { summary },',
'      create: { month, summary },',
'    });',
'    return NextResponse.json({ ok: true, item });',
'  } catch (e) {',
'    const msg = asMsg(e);',
'    if (looksLikeMissingTable(msg)) {',
'      return NextResponse.json({ ok: false, error: "db_not_ready", detail: msg }, { status: 503 });',
'    }',
'    return NextResponse.json({ ok: false, error: "db_error", detail: msg }, { status: 500 });',
'  }',
'}',
''
)

EnsureDir (Split-Path -Parent $apiClose)
[System.IO.File]::WriteAllLines($apiClose, $L1, $enc)
Write-Host "[PATCH] wrote src/app/api/eco/month-close/route.ts"

# ---------------- month-close/list route ----------------
$L2 = @(
'// ECO — month-close/list — step 57',
'',
'import { NextResponse } from "next/server";',
'import { prisma } from "@/lib/prisma";',
'',
'export const runtime = "nodejs";',
'export const dynamic = "force-dynamic";',
'',
'function asMsg(e: unknown) {',
'  if (e instanceof Error) return e.message;',
'  try { return String(e); } catch { return "unknown"; }',
'}',
'',
'function looksLikeMissingTable(msg: string) {',
'  const m = msg.toLowerCase();',
'  return m.includes("does not exist") || m.includes("no such table") || m.includes("p2021");',
'}',
'',
'function getMonthCloseModel() {',
'  const pc: any = prisma as any;',
'  return pc?.ecoMonthClose;',
'}',
'',
'function clamp(n: number, a: number, b: number) {',
'  return Math.max(a, Math.min(b, n));',
'}',
'',
'export async function GET(req: Request) {',
'  const { searchParams } = new URL(req.url);',
'  const raw = String(searchParams.get("limit") ?? "24").trim();',
'  const limit = clamp(Number(raw) || 24, 1, 200);',
'',
'  const model = getMonthCloseModel();',
'  if (!model?.findMany) {',
'    return NextResponse.json({ ok: false, error: "model_not_ready", hint: "missing ecoMonthClose model" }, { status: 503 });',
'  }',
'',
'  try {',
'    const items = await model.findMany({',
'      orderBy: { month: "desc" },',
'      take: limit,',
'    });',
'    return NextResponse.json({ ok: true, items, limit });',
'  } catch (e) {',
'    const msg = asMsg(e);',
'    if (looksLikeMissingTable(msg)) {',
'      return NextResponse.json({ ok: false, error: "db_not_ready", detail: msg }, { status: 503 });',
'    }',
'    return NextResponse.json({ ok: false, error: "db_error", detail: msg }, { status: 500 });',
'  }',
'}',
''
)

EnsureDir (Split-Path -Parent $apiList)
[System.IO.File]::WriteAllLines($apiList, $L2, $enc)
Write-Host "[PATCH] wrote src/app/api/eco/month-close/list/route.ts"

# ---------------- month card route (next/og) ----------------
$L3 = @(
'// ECO — month-close/card (PNG) — step 57',
'',
'import { ImageResponse } from "next/og";',
'',
'export const runtime = "edge";',
'export const dynamic = "force-dynamic";',
'',
'function safeMonth(input: string | null): string | null {',
'  const raw = String(input ?? "").trim();',
'  if (!raw) return null;',
'  const norm = raw.replace(/[‐-‒–—―]/g, "-").replace(/\//g, "-");',
'  const m = norm.match(/^(\d{4})-(\d{2})$/);',
'  if (!m) return null;',
'  const mo = Number(m[2]);',
'  if (mo < 1 || mo > 12) return null;',
'  return m[1] + "-" + m[2];',
'}',
'',
'function fmtKg(n: any): string {',
'  const v = Number(n || 0) || 0;',
'  const s = Math.round(v * 10) / 10;',
'  return String(s).replace(".", ",") + " kg";',
'}',
'',
'function pickFormat(input: string | null): { w: number; h: number; label: string } {',
'  const f = String(input ?? "").trim().toLowerCase();',
'  if (f === "1x1" || f === "square") return { w: 1080, h: 1080, label: "1:1" };',
'  return { w: 1080, h: 1350, label: "3:4" };',
'}',
'',
'function topMaterials(by: any): Array<{ k: string; v: number }> {',
'  const out: Array<{ k: string; v: number }> = [];',
'  if (by && typeof by === "object") {',
'    for (const k of Object.keys(by)) out.push({ k, v: Number(by[k] || 0) || 0 });',
'  }',
'  out.sort((a, b) => b.v - a.v);',
'  return out.slice(0, 6);',
'}',
'',
'export async function GET(req: Request) {',
'  const { searchParams } = new URL(req.url);',
'  const month = safeMonth(searchParams.get("month") ?? searchParams.get("m"));',
'  const fmt = pickFormat(searchParams.get("format"));',
'  if (!month) return new Response("bad_month", { status: 400 });',
'',
'  const origin = new URL(req.url).origin;',
'  const apiUrl = origin + "/api/eco/month-close?month=" + encodeURIComponent(month);',
'',
'  let totalKg = 0;',
'  let days = 0;',
'  let mats: Array<{ k: string; v: number }> = [];',
'  let statusText = "OK";',
'',
'  try {',
'    const res = await fetch(apiUrl, { headers: { Accept: "application/json" }, cache: "no-store" });',
'    const data: any = await res.json().catch(() => ({}));',
'    if (!res.ok || !data?.ok) {',
'      statusText = "ERRO";',
'    } else {',
'      const summary = data?.item?.summary || {};',
'      const totals = summary?.totals || {};',
'      totalKg = Number(totals.totalKg || 0) || 0;',
'      days = Number(totals.days || 0) || 0;',
'      mats = topMaterials(totals.byMaterialKg || {});',
'    }',
'  } catch {',
'    statusText = "ERRO";',
'  }',
'',
'  const bg = "linear-gradient(180deg, #0B0B0B 0%, #0F0F0F 35%, #0B0B0B 100%)";',
'  const yellow = "#F7D500";',
'  const red = "#E53935";',
'  const gray = "#BDBDBD";',
'',
'  return new ImageResponse(',
'    (',
'      <div style={{ width: fmt.w, height: fmt.h, display: "flex", flexDirection: "column", backgroundImage: bg, color: "white", padding: 72, fontFamily: "system-ui, -apple-system, Segoe UI, Roboto, Arial" }}>',
'        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>',
'          <div style={{ display: "flex", flexDirection: "column" }}>',
'            <div style={{ display: "flex", fontSize: 28, letterSpacing: 2, color: yellow, fontWeight: 900 }}>ECO</div>',
'            <div style={{ display: "flex", fontSize: 18, opacity: 0.85 }}>Transparência Mensal</div>',
'          </div>',
'          <div style={{ display: "flex", gap: 10, alignItems: "center" }}>',
'            <div style={{ display: "flex", fontSize: 16, opacity: 0.8 }}>formato {fmt.label}</div>',
'            <div style={{ display: "flex", width: 14, height: 14, borderRadius: 999, background: statusText === "OK" ? yellow : red }} />',
'          </div>',
'        </div>',
'',
'        <div style={{ display: "flex", height: 28 }} />',
'',
'        <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>',
'          <div style={{ display: "flex", fontSize: 44, fontWeight: 900, letterSpacing: 1 }}>{month}</div>',
'          <div style={{ display: "flex", gap: 12, alignItems: "baseline" }}>',
'            <div style={{ display: "flex", fontSize: 86, fontWeight: 900, color: yellow }}>{fmtKg(totalKg)}</div>',
'            <div style={{ display: "flex", fontSize: 18, opacity: 0.85 }}>{days} dias fechados</div>',
'          </div>',
'        </div>',
'',
'        <div style={{ display: "flex", height: 26 }} />',
'',
'        <div style={{ display: "flex", flexDirection: "column", gap: 12, flex: 1 }}>',
'          <div style={{ display: "flex", fontSize: 20, opacity: 0.9, letterSpacing: 1 }}>POR MATERIAL (SOMA DO MÊS)</div>',
'          <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>',
'            {mats.length ? (',
'              mats.map((m) => (',
'                <div key={m.k} style={{ display: "flex", justifyContent: "space-between", alignItems: "center", padding: "12px 14px", borderRadius: 14, border: "1px solid rgba(255,255,255,0.12)", background: "rgba(255,255,255,0.04)" }}>',
'                  <div style={{ display: "flex", gap: 10, alignItems: "center" }}>',
'                    <div style={{ display: "flex", width: 10, height: 10, borderRadius: 999, background: yellow }} />',
'                    <div style={{ display: "flex", fontSize: 22, fontWeight: 800, textTransform: "uppercase", letterSpacing: 1 }}>{m.k}</div>',
'                  </div>',
'                  <div style={{ display: "flex", fontSize: 24, fontWeight: 900, color: gray }}>{fmtKg(m.v)}</div>',
'                </div>',
'              ))',
'            ) : (',
'              <div style={{ display: "flex", fontSize: 20, opacity: 0.8 }}>Sem dados (feche dias do mês primeiro).</div>',
'            )}',
'          </div>',
'        </div>',
'',
'        <div style={{ display: "flex", height: 18 }} />',
'',
'        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-end" }}>',
'          <div style={{ display: "flex", flexDirection: "column", gap: 6, maxWidth: 760 }}>',
'            <div style={{ display: "flex", fontSize: 16, opacity: 0.9 }}>Recibo é lei. Cuidado é coletivo. Trabalho digno é o centro.</div>',
'            <div style={{ display: "flex", fontSize: 14, opacity: 0.7 }}>#ECO — Escutar • Cuidar • Organizar</div>',
'          </div>',
'          <div style={{ display: "flex", flexDirection: "column", alignItems: "flex-end", gap: 6 }}>',
'            <div style={{ display: "flex", fontSize: 14, opacity: 0.75 }}>Transparência v0</div>',
'            <div style={{ display: "flex", fontSize: 18, fontWeight: 900, color: yellow }}>VOLTA REDONDA</div>',
'          </div>',
'        </div>',
'      </div>',
'    ),',
'    { width: fmt.w, height: fmt.h }',
'  );',
'}',
''
)

EnsureDir (Split-Path -Parent $apiCard)
[System.IO.File]::WriteAllLines($apiCard, $L3, $enc)
Write-Host "[PATCH] wrote src/app/api/eco/month-close/card/route.tsx"

# ---------------- UI page ----------------
$L4 = @(
'// ECO — Transparência Mensal (UI) — step 57',
'',
'import TransparenciaClient from "./TransparenciaClient";',
'',
'export const dynamic = "force-dynamic";',
'',
'export default function Page() {',
'  return (',
'    <main style={{ padding: 16, fontFamily: "system-ui, -apple-system, Segoe UI, Roboto, Arial" }}>',
'      <h1 style={{ margin: "0 0 8px 0" }}>ECO — Transparência Mensal</h1>',
'      <p style={{ margin: "0 0 16px 0", opacity: 0.85 }}>',
'        Fecha o mês somando os fechamentos diários e gera um card compartilhável.',
'      </p>',
'      <TransparenciaClient />',
'    </main>',
'  );',
'}',
''
)

EnsureDir (Split-Path -Parent $uiPage)
[System.IO.File]::WriteAllLines($uiPage, $L4, $enc)
Write-Host "[PATCH] wrote src/app/eco/transparencia/page.tsx"

# ---------------- UI client ----------------
$L5 = @(
'"use client";',
'',
'import { useEffect, useMemo, useState } from "react";',
'',
'type AnyObj = Record<string, any>;',
'',
'function brMonthNow(): string {',
'  try {',
'    const parts = new Intl.DateTimeFormat("en-CA", { timeZone: "America/Sao_Paulo", year: "numeric", month: "2-digit" }).formatToParts(new Date());',
'    const y = parts.find(p => p.type === "year")?.value || "";',
'    const m = parts.find(p => p.type === "month")?.value || "";',
'    if (y && m) return y + "-" + m;',
'  } catch {}',
'  const dt = new Date();',
'  const y = String(dt.getFullYear());',
'  const m = String(dt.getMonth() + 1).padStart(2, "0");',
'  return y + "-" + m;',
'}',
'',
'async function jget(url: string): Promise<AnyObj> {',
'  const res = await fetch(url, { headers: { Accept: "application/json" }, cache: "no-store" });',
'  const data = await res.json().catch(() => ({}));',
'  if (!res.ok) return { ok: false, status: res.status, ...data };',
'  return data;',
'}',
'',
'export default function TransparenciaClient() {',
'  const [month, setMonth] = useState<string>(brMonthNow());',
'  const [busy, setBusy] = useState(false);',
'  const [result, setResult] = useState<AnyObj | null>(null);',
'  const [history, setHistory] = useState<AnyObj | null>(null);',
'',
'  const closeUrl = useMemo(() => "/api/eco/month-close?month=" + encodeURIComponent(month), [month]);',
'  const card34 = useMemo(() => "/api/eco/month-close/card?format=3x4&month=" + encodeURIComponent(month), [month]);',
'  const card11 = useMemo(() => "/api/eco/month-close/card?format=1x1&month=" + encodeURIComponent(month), [month]);',
'',
'  async function loadHistory() {',
'    const data = await jget("/api/eco/month-close/list?limit=24");',
'    setHistory(data);',
'  }',
'',
'  async function doClose(fresh: boolean) {',
'    setBusy(true);',
'    try {',
'      const url = closeUrl + (fresh ? "&fresh=1" : "");',
'      const data = await jget(url);',
'      setResult(data);',
'      await loadHistory();',
'    } finally {',
'      setBusy(false);',
'    }',
'  }',
'',
'  useEffect(() => {',
'    loadHistory();',
'    // eslint-disable-next-line react-hooks/exhaustive-deps',
'  }, []);',
'',
'  return (',
'    <section style={{ display: "grid", gap: 12, maxWidth: 980 }}>',
'      <div style={{ display: "flex", gap: 10, alignItems: "center", flexWrap: "wrap" }}>',
'        <label style={{ display: "flex", gap: 8, alignItems: "center" }}>',
'          <span>Mês:</span>',
'          <input',
'            value={month}',
'            onChange={(e) => setMonth(e.target.value)}',
'            placeholder="YYYY-MM"',
'            style={{ padding: "6px 8px", border: "1px solid #ccc", borderRadius: 6, minWidth: 140 }}',
'          />',
'        </label>',
'',
'        <button',
'          onClick={() => doClose(false)}',
'          disabled={busy}',
'          style={{ padding: "8px 10px", borderRadius: 8, border: "1px solid #111", cursor: busy ? "not-allowed" : "pointer" }}',
'        >',
'          Fechar / Buscar cache',
'        </button>',
'',
'        <button',
'          onClick={() => doClose(true)}',
'          disabled={busy}',
'          style={{ padding: "8px 10px", borderRadius: 8, border: "1px solid #111", cursor: busy ? "not-allowed" : "pointer" }}',
'        >',
'          Recalcular (fresh=1)',
'        </button>',
'',
'        <button',
'          onClick={() => loadHistory()}',
'          disabled={busy}',
'          style={{ padding: "8px 10px", borderRadius: 8, border: "1px solid #111", cursor: busy ? "not-allowed" : "pointer" }}',
'        >',
'          Atualizar histórico',
'        </button>',
'',
'        <a',
'          href={card34}',
'          target="_blank"',
'          rel="noreferrer"',
'          style={{ padding: "8px 10px", borderRadius: 8, border: "1px solid #111", textDecoration: "none", color: "#111", background: "#F7D500", fontWeight: 800 }}',
'        >',
'          Abrir Card 3:4',
'        </a>',
'',
'        <a',
'          href={card11}',
'          target="_blank"',
'          rel="noreferrer"',
'          style={{ padding: "8px 10px", borderRadius: 8, border: "1px solid #111", textDecoration: "none", color: "#111", background: "#F7D500", fontWeight: 800 }}',
'        >',
'          Abrir Card 1:1',
'        </a>',
'      </div>',
'',
'      <div style={{ display: "grid", gap: 12, gridTemplateColumns: "1fr 1fr" }}>',
'        <div>',
'          <h2 style={{ margin: "0 0 8px 0" }}>Resultado</h2>',
'          <pre style={{ whiteSpace: "pre-wrap", wordBreak: "break-word", padding: 12, border: "1px solid #ddd", borderRadius: 10, minHeight: 160 }}>',
'            {result ? JSON.stringify(result, null, 2) : "—"}',
'          </pre>',
'        </div>',
'        <div>',
'          <h2 style={{ margin: "0 0 8px 0" }}>Histórico (últimos 24)</h2>',
'          <pre style={{ whiteSpace: "pre-wrap", wordBreak: "break-word", padding: 12, border: "1px solid #ddd", borderRadius: 10, minHeight: 160 }}>',
'            {history ? JSON.stringify(history, null, 2) : "—"}',
'          </pre>',
'        </div>',
'      </div>',
'    </section>',
'  );',
'}',
''
)

EnsureDir (Split-Path -Parent $uiClient)
[System.IO.File]::WriteAllLines($uiClient, $L5, $enc)
Write-Host "[PATCH] wrote src/app/eco/transparencia/TransparenciaClient.tsx"

# ---------------- report ----------------
$rep = Join-Path $reportDir ("eco-step-57-month-close-transparencia-v0_1-" + $ts + ".md")
$repLines = @(
"# eco-step-57-month-close-transparencia-v0_1",
"",
"- Time: " + $ts,
"- Backup: " + $backupDir,
"",
"## Added",
"- API: /api/eco/month-close?month=YYYY-MM (GET/POST, fresh=1)",
"- API: /api/eco/month-close/list?limit=24",
"- Card: /api/eco/month-close/card?month=YYYY-MM&format=3x4|1x1",
"- UI: /eco/transparencia",
"",
"## Notes",
"- Este tijolo assume existência do modelo Prisma ecoMonthClose. Se der model_not_ready, faremos o STEP 57b (Prisma model + migrate).",
""
)
[System.IO.File]::WriteAllLines($rep, $repLines, $enc)
Write-Host ("[REPORT] " + $rep)

Write-Host ""
Write-Host "[VERIFY] 1) reinicie dev server (Ctrl+C, npm run dev)"
Write-Host "[VERIFY] 2) abra: http://localhost:3000/eco/transparencia"
Write-Host "[VERIFY] 3) teste: irm ''http://localhost:3000/api/eco/month-close?month=2025-12'' | ConvertTo-Json -Depth 20"