$ErrorActionPreference = "Stop"

function EnsureDir([string]$p){
  if($p -and !(Test-Path -LiteralPath $p)){ New-Item -ItemType Directory -Force -Path $p | Out-Null }
}
function WriteUtf8NoBom([string]$path, [string]$content){
  $dir = Split-Path -Parent $path
  if($dir){ EnsureDir $dir }
  $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
  [System.IO.File]::WriteAllText($path, $content, $utf8NoBom)
}
function BackupFile([string]$path){
  if(!(Test-Path -LiteralPath $path)){ return $null }
  EnsureDir "tools/_patch_backup"
  $ts = Get-Date -Format "yyyyMMdd-HHmmss"
  $safe = ($path -replace '[\\/:*?"<>|]', '_')
  $dst = "tools/_patch_backup/$ts-$safe"
  Copy-Item -Force -LiteralPath $path $dst
  return $dst
}
function NewReport([string]$name){
  EnsureDir "reports"
  $ts = Get-Date -Format "yyyyMMdd-HHmmss"
  return "reports/$ts-$name.md"
}
function DecodeB64([string]$b64){
  $bytes = [Convert]::FromBase64String($b64)
  return [System.Text.Encoding]::UTF8.GetString($bytes)
}

$rep = NewReport "eco-step-07-pedidos-fechar-ui"
$log = @()
$log += "# ECO — STEP 07 — Pedidos: tela /pedidos + fechar/emitir recibo"
$log += ""
$log += ("Data: {0}" -f (Get-Date -Format "yyyy-MM-dd HH:mm:ss"))
$log += ("PWD : {0}" -f (Get-Location).Path)
$log += ""

$log += "## DIAG"
$targets = @(
  "src/app/pedidos/page.tsx",
  "src/app/pedidos/fechar/[id]/page.tsx",
  "src/app/pedidos/fechar/[id]/close-client.tsx",
  "tools/eco-smoke.ps1"
)
foreach($t in $targets){
  $log += ("- {0} => {1}" -f $t, (Test-Path -LiteralPath $t))
}
$log += ""

# ===== PATCH =====
$log += "## PATCH"

# 1) /pedidos page (garantia)
$pedidosPath = "src/app/pedidos/page.tsx"
$pedidosWritten = $false
$pedidosBak = $null

$b64Pedidos = "aW1wb3J0IExpbmsgZnJvbSAibmV4dC9saW5rIjsKaW1wb3J0IHsgaGVhZGVycyB9IGZyb20gIm5leHQvaGVhZGVycyI7CmltcG9ydCBFY29OYXYgZnJvbSAiQC9jb21wb25lbnRzL0Vjb05hdiI7CgpleHBvcnQgY29uc3QgcnVudGltZSA9ICJub2RlanMiOwoKdHlwZSBBbnlSZWNlaXB0ID0gewogIGlkPzogc3RyaW5nOwogIGNvZGU/OiBzdHJpbmcgfCBudWxsOwogIHNoYXJlQ29kZT86IHN0cmluZyB8IG51bGw7Cn07Cgp0eXBlIFBpY2t1cEl0ZW0gPSB7CiAgaWQ6IHN0cmluZzsKICBuYW1lPzogc3RyaW5nIHwgbnVsbDsKICBwaG9uZT86IHN0cmluZyB8IG51bGw7CiAgYWRkcmVzcz86IHN0cmluZyB8IG51bGw7CiAgc3RhdHVzPzogc3RyaW5nIHwgbnVsbDsKICBjcmVhdGVkQXQ/OiBzdHJpbmcgfCBudWxsOwogIHJlY2VpcHQ/OiBBbnlSZWNlaXB0IHwgbnVsbDsKICBlY29SZWNlaXB0PzogQW55UmVjZWlwdCB8IG51bGw7Cn07CgpmdW5jdGlvbiBvcmlnaW5Gcm9tSGVhZGVycygpIHsKICBjb25zdCBoID0gaGVhZGVycygpOwogIGNvbnN0IHByb3RvID0gaC5nZXQoIngtZm9yd2FyZGVkLXByb3RvIikgPz8gImh0dHAiOwogIGNvbnN0IGhvc3QgPSBoLmdldCgieC1mb3J3YXJkZWQtaG9zdCIpID8/IGguZ2V0KCJob3N0IikgPz8gImxvY2FsaG9zdDozMDAwIjsKICByZXR1cm4gYCR7cHJvdG99Oi8vJHtob3N0fWA7Cn0KCmZ1bmN0aW9uIHBpY2tDb2RlKGl0OiBQaWNrdXBJdGVtKTogc3RyaW5nIHwgbnVsbCB7CiAgY29uc3Qgcj0gaXQuZWNvUmVjZWlwdCA/PyBpdC5yZWNlaXB0OwogIGlmICghcikgcmV0dXJuIG51bGw7CiAgcmV0dXJuIChyLnNoYXJlQ29kZSA/PyByLmNvZGUgPz8gbnVsbCkgYXMgc3RyaW5nIHwgbnVsbDsKfQoKZnVuY3Rpb24gZm10RGF0ZShzPzogc3RyaW5nIHwgbnVsbCkgewogIGlmICghcykgcmV0dXJuICIiOwogIGNvbnN0IGQgPSBuZXcgRGF0ZShzKTsKICBpZiAoTnVtYmVyLmlzTmFOKGQuZ2V0VGltZSgpKSkgcmV0dXJuIHM7CiAgcmV0dXJuIGQudG9Mb2NhbGVTdHJpbmcoInB0LUJSIiwgeyBkYXRlU3R5bGU6ICJzaG9ydCIsIHRpbWVTdHlsZTogInNob3J0IiB9KTsKfQoKZXhwb3J0IGRlZmF1bHQgYXN5bmMgZnVuY3Rpb24gUGFnZSgpIHsKICBjb25zdCBvcmlnaW4gPSBvcmlnaW5Gcm9tSGVhZGVycygpOwoKICBsZXQgaXRlbXM6IFBpY2t1cEl0ZW1bXSA9IFtdOwogIGxldCBlcnJvcjogc3RyaW5nIHwgbnVsbCA9IG51bGw7CgogIHRyeSB7CiAgICBjb25zdCByZXMgPSBhd2FpdCBmZXRjaChgJHtvcmlnaW59L2FwaS9waWNrdXAtcmVxdWVzdHNgLCB7IGNhY2hlOiAibm8tc3RvcmUiIH0pOwogICAgY29uc3QganNvbiA9IGF3YWl0IHJlcy5qc29uKCkuY2F0Y2goKCkgPT4gKHt9KSk7CgogICAgLy8gc3Vwb3J0YSBmb3JtYXRvcyBkaWZlcmVudGVzIHNlbSBxdWVicmFyCiAgICBjb25zdCBhcnIgPSAoanNvbi5pdGVtcyA/PyBqc29uLnJlcXVlc3RzID8/IGpzb24uZGF0YSA/PyBqc29uKSBhcyBhbnk7CiAgICBpdGVtcyA9IEFycmF5LmlzQXJyYXkoYXJyKSA/IChhcnIgYXMgUGlja3VwSXRlbVtdKSA6IFtdOwogIH0gY2F0Y2ggKGUpIHsKICAgIGVycm9yID0gZSBpbnN0YW5jZW9mIEVycm9yID8gZS5tZXNzYWdlIDogU3RyaW5nKGUpOwogIH0KCiAgLy8gb3JkZW5hIHBvciBjcmVhdGVkQXQgZGVzYyBzZSBleGlzdGlyCiAgaXRlbXMgPSBbLi4uaXRlbXNdLnNvcnQoKGEsIGIpID0+IHsKICAgIGNvbnN0IHRhID0gYS5jcmVhdGVkQXQgPyBuZXcgRGF0ZShhLmNyZWF0ZWRBdCkuZ2V0VGltZSgpIDogMDsKICAgIGNvbnN0IHRiID0gYi5jcmVhdGVkQXQgPyBuZXcgRGF0ZShiLmNyZWF0ZWRBdCkuZ2V0VGltZSgpIDogMDsKICAgIHJldHVybiB0YiAtIHRhOwogIH0pOwoKICByZXR1cm4gKAogICAgPG1haW4gY2xhc3NOYW1lPSJtaW4taC1zY3JlZW4iPgogICAgICA8RWNvTmF2IC8+CiAgICAgIDxkaXYgY2xhc3NOYW1lPSJteC1hdXRvIG1heC13LTV4bCBwLTQiPgogICAgICAgIDxkaXYgY2xhc3NOYW1lPSJmbGV4IGl0ZW1zLWNlbnRlciBqdXN0aWZ5LWJldHdlZW4gZ2FwLTMiPgogICAgICAgICAgPGgxIGNsYXNzTmFtZT0idGV4dC0yeGwgZm9udC1ib2xkIj5QZWRpZG9zIChGaWxhKTwvaDE+CiAgICAgICAgICA8ZGl2IGNsYXNzTmFtZT0iZmxleCBnYXAtMiI+CiAgICAgICAgICAgIDxMaW5rCiAgICAgICAgICAgICAgaHJlZj0iL2NoYW1hci1jb2xldGEvbm92byIKICAgICAgICAgICAgICBjbGFzc05hbWU9InJvdW5kZWQgYmctYmxhY2sgcHgtMyBweS0yIHRleHQtc20gZm9udC1zZW1pYm9sZCB0ZXh0LXdoaXRlIgogICAgICAgICAgICA+CiAgICAgICAgICAgICAgKyBDaGFtYXIgY29sZXRhCiAgICAgICAgICAgIDwvTGluaz4KICAgICAgICAgICAgPExpbmsKICAgICAgICAgICAgICBocmVmPSIvcmVjaWJvcyIKICAgICAgICAgICAgICBjbGFzc05hbWU9InJvdW5kZWQgYm9yZGVyIGJvcmRlci1ibGFjayBweC0zIHB5LTIgdGV4dC1zbSBmb250LXNlbWlib2xkIgogICAgICAgICAgICA+CiAgICAgICAgICAgICAgVmVyIHJlY2lib3MKICAgICAgICAgICAgPC9MaW5rPgogICAgICAgICAgPC9kaXY+CiAgICAgICAgPC9kaXY+CgogICAgICAgIHtlcnJvciA/ICgKICAgICAgICAgIDxkaXYgY2xhc3NOYW1lPSJtdC00IHJvdW5kZWQgYm9yZGVyIGJvcmRlci1yZWQtMzAwIGJnLXJlZC01MCBwLTMgdGV4dC1zbSI+CiAgICAgICAgICAgIDxkaXYgY2xhc3NOYW1lPSJmb250LXNlbWlib2xkIj5GYWxoYSBhbyBjYXJyZWdhciAvYXBpL3BpY2t1cC1yZXF1ZXN0czwvZGl2PgogICAgICAgICAgICA8ZGl2IGNsYXNzTmFtZT0ibXQtMSBicmVhay13b3JkcyI+e2Vycm9yfTwvZGl2PgogICAgICAgICAgPC9kaXY+CiAgICAgICAgKSA6IG51bGx9CgogICAgICAgIDxkaXYgY2xhc3NOYW1lPSJtdC00IG92ZXJmbG93LXgtYXV0byByb3VuZGVkIGJvcmRlciI+CiAgICAgICAgICA8dGFibGUgY2xhc3NOYW1lPSJ3LWZ1bGwgdGV4dC1sZWZ0IHRleHQtc20iPgogICAgICAgICAgICA8dGhlYWQgY2xhc3NOYW1lPSJiZy1ncmF5LTUwIj4KICAgICAgICAgICAgICA8dHI+CiAgICAgICAgICAgICAgICA8dGggY2xhc3NOYW1lPSJwLTMiPkRhdGE8L3RoPgogICAgICAgICAgICAgICAgPHRoIGNsYXNzTmFtZT0icC0zIj5Ob21lPC90aD4KICAgICAgICAgICAgICAgIDx0aCBjbGFzc05hbWU9InAtMyI+RW5kZXJlY288L3RoPgogICAgICAgICAgICAgICAgPHRoIGNsYXNzTmFtZT0icC0zIj5TdGF0dXM8L3RoPgogICAgICAgICAgICAgICAgPHRoIGNsYXNzTmFtZT0icC0zIj5Bx6fDtWVzPC90aD4KICAgICAgICAgICAgICA8L3RyPgogICAgICAgICAgICA8L3RoZWFkPgogICAgICAgICAgICA8dGJvZHk+CiAgICAgICAgICAgICAg{aXRlbXMubGVuZ3RoID09PSAwID8gKAogICAgICAgICAgICAgICAgPHRyPgogICAgICAgICAgICAgICAgICA8dGQgY2xhc3NOYW1lPSJwLTMgdGV4dC1ncmF5LTYwMCIgY29sU3Bhbj17NX0+CiAgICAgICAgICAgICAgICAgICAgTmVuaHVtIHBlZGlkbyBlbmNvbnRyYWRvLgogICAgICAgICAgICAgICAgICA8L3RkPgogICAgICAgICAgICAgICAgPC90cj4KICAgICAgICAgICAgICApIDogKAogICAgICAgICAgICAgICAgaXRlbXMubWFwKChpdCkgPT4gewogICAgICAgICAgICAgICAgICBjb25zdCBjb2RlID0gcGlja0NvZGUoaXQpOwogICAgICAgICAgICAgICAgICByZXR1cm4gKAogICAgICAgICAgICAgICAgICAgIDx0ciBrZXk9e2l0LmlkfSBjbGFzc05hbWU9ImJvcmRlci10Ij4KICAgICAgICAgICAgICAgICAgICAgIDx0ZCBjbGFzc05hbWU9InAtMyB3aGl0ZXNwYWNlLW5vd3JhcCI+e2ZtdERhdGUoaXQuY3JlYXRlZEF0KX08L3RkPgogICAgICAgICAgICAgICAgICAgICAgPHRkIGNsYXNzTmFtZT0icC0zIj57aXQubmFtZSA/PyAiLSJ9PC90ZD4KICAgICAgICAgICAgICAgICAgICAgIDx0ZCBjbGFzc05hbWU9InAtMyI+e2l0LmFkZHJlc3MgPz8gIi0ifTwvdGQ+CiAgICAgICAgICAgICAgICAgICAgICA8dGQgY2xhc3NOYW1lPSJwLTMgd2hpdGVzcGFjZS1ub3dyYXAiPntpdC5zdGF0dXMgPz8gIi0ifTwvdGQ+CiAgICAgICAgICAgICAgICAgICAgICA8dGQgY2xhc3NOYW1lPSJwLTMgd2hpdGVzcGFjZS1ub3dyYXAiPgogICAgICAgICAgICAgICAgICAgICAgICA8ZGl2IGNsYXNzTmFtZT0iZmxleCBmbGV4LXdyYXAgZ2FwLTIiPgogICAgICAgICAgICAgICAgICAgICAgICAgIDxMaW5rCiAgICAgICAgICAgICAgICAgICAgICAgICAgICBocmVmPXsgYC9wZWRpZG9zL2ZlY2hhci8ke2l0LmlkfWAgfQogICAgICAgICAgICAgICAgICAgICAgICAgICAgY2xhc3NOYW1lPSJyb3VuZGVkIGJnLWJsYWNrIHB4LTMgcHktMiB0ZXh0LXhzIGZvbnQtc2VtaWJvbGQgdGV4dC13aGl0ZSIKICAgICAgICAgICAgICAgICAgICAgICAgICAgID4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgRmVjaGFyIC8gRW1pdGlyIHJlY2libwogICAgICAgICAgICAgICAgICAgICAgICAgIDwvTGluaz4KICAgICAgICAgICAgICAgICAgICAgICAgICAgIHtjb2RlID8gKAogICAgICAgICAgICAgICAgICAgICAgICAgICAgPExpbmsKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBocmVmPXsgYC9yZWNpYm8vJHtjb2RlfWAgfQogICAgICAgICAgICAgICAgICAgICAgICAgICAgICBjbGFzc05hbWU9InJvdW5kZWQgYm9yZGVyIGJvcmRlci1ibGFjayBweC0zIHB5LTIgdGV4dC14cyBmb250LXNlbWlib2xkIgogICAgICAgICAgICAgICAgICAgICAgICAgICAgPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICBWZXIgcmVjaWJvCiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8L0xpbms+CiAgICAgICAgICAgICAgICAgICAgICAgICAgKSA6IG51bGx9CiAgICAgICAgICAgICAgICAgICAgICAgIDwvZGl2PgogICAgICAgICAgICAgICAgICAgICAgPC90ZD4KICAgICAgICAgICAgICAgICAgICA8L3RyPgogICAgICAgICAgICAgICAgICApOwogICAgICAgICAgICAgICAgfSkKICAgICAgICAgICAgICApfQogICAgICAgICAgICA8L3Rib2R5PgogICAgICAgICAgPC90YWJsZT4KICAgICAgICA8L2Rpdj4KCiAgICAgICAgPGRpdiBjbGFzc05hbWU9Im10LTQgdGV4dC14cyB0ZXh0LWdyYXktNjAwIj4KICAgICAgICAgIERpY2E6IHNlIHVtIHBlZGlkbyBqw6EgdGl2ZXIgcmVjaWJvLCBvIGJvdMOjbyDigJxWZXIgcmVjaWJv4oCdIGFwYXJlY2UgYXV0b21hdGljYW1lbnRlLgogICAgICAgIDwvZGl2PgogICAgICA8L2Rpdj4KICAgIDwvbWFpbj4KICApOwp9Cg=="
$desiredPedidos = DecodeB64 $b64Pedidos

$needPedidos = $true
if(Test-Path -LiteralPath $pedidosPath){
  $cur = Get-Content -LiteralPath $pedidosPath -Raw
  if(($cur -match "Pedidos \(Fila\)") -and ($cur -match "Fechar / Emitir recibo")){
    $needPedidos = $false
  }
}

if($needPedidos){
  $pedidosBak = BackupFile $pedidosPath
  WriteUtf8NoBom $pedidosPath $desiredPedidos
  $pedidosWritten = $true
  $log += ("- OK: /pedidos atualizado -> {0}" -f $pedidosPath)
  if($pedidosBak){ $log += ("  - backup: {0}" -f $pedidosBak) }
} else {
  $log += "- OK: /pedidos já estava no formato esperado (sem alteração)"
}
$log += ""

# 2) /pedidos/fechar/[id]
$closePagePath = "src/app/pedidos/fechar/[id]/page.tsx"
$closeClientPath = "src/app/pedidos/fechar/[id]/close-client.tsx"

$b64ClosePage = "aW1wb3J0IEVjb05hdiBmcm9tICJAL2NvbXBvbmVudHMvRWNvTmF2IjsKaW1wb3J0IENsb3NlUGVkaWRvQ2xpZW50IGZyb20gIi4vY2xvc2UtY2xpZW50IjsKaW1wb3J0IHsgaGVhZGVycyB9IGZyb20gIm5leHQvaGVhZGVycyI7CgpleHBvcnQgY29uc3QgcnVudGltZSA9ICJub2RlanMiOwoKZnVuY3Rpb24gb3JpZ2luRnJvbUhlYWRlcnMoKSB7CiAgY29uc3QgaCA9IGhlYWRlcnMoKTsKICBjb25zdCBwcm90byA9IGguZ2V0KCJ4LWZvcndhcmRlZC1wcm90byIpID8/ICJodHRwIjsKICBjb25zdCBob3N0ID0gaC5nZXQoIngtZm9yd2FyZGVkLWhvc3QiKSA/PyBoLmdldCgiaG9zdCIpID8/ICJsb2NhbGhvc3Q6MzAwMCI7CiAgcmV0dXJuIGAke3Byb3RvfTovLyR7aG9zdH1gOwp9CgpleHBvcnQgZGVmYXVsdCBhc3luYyBmdW5jdGlvbiBQYWdlKHsgcGFyYW1zIH06IHsgcGFyYW1zOiBQcm9taXNlPHsgaWQ6IHN0cmluZyB9PiB9KSB7CiAgY29uc3QgeyBpZCB9ID0gYXdhaXQgcGFyYW1zOwogIGNvbnN0IG9yaWdpbiA9IG9yaWdpbkZyb21IZWFkZXJzKCk7CiAgcmV0dXJuICgKICAgIDxtYWluIGNsYXNzTmFtZT0ibWluLWgtc2NyZWVuIj4KICAgICAgPEVjb05hdiAvPgogICAgICA8ZGl2IGNsYXNzTmFtZT0ibXgtYXV0byBtYXgtdy0zeGwgcC00Ij4KICAgICAgICA8aDEgY2xhc3NOYW1lPSJ0ZXh0LTJ4bCBmb250LWJvbGQiPkZlY2hhciBwZWRpZG88L2gxPgogICAgICAgIDxwIGNsYXNzTmFtZT0ibXQtMSB0ZXh0LXNtIHRleHQtZ3JheS02MDAiPgogICAgICAgICAgUGVkaWRvOiA8c3BhbiBjbGFzc05hbWU9ImZvbnQtbW9ubyI+e2lkfTwvc3Bhbj4KICAgICAgICA8L3A+CgogICAgICAgIDxkaXYgY2xhc3NOYW1lPSJtdC00Ij4KICAgICAgICAgIDxDbG9zZVBlZGlkb0NsaWVudCBvcmlnaW49e29yaWdpbn0gcmVxdWVzdElkPXtpZH0gLz4KICAgICAgICA8L2Rpdj4KICAgICAgPC9kaXY+CiAgICA8L21haW4+CiAgKTsKfQo="
$b64CloseClient = "InVzZSBjbGllbnQiOwoKaW1wb3J0IExpbmsgZnJvbSAibmV4dC9saW5rIjsKaW1wb3J0IHsgdXNlRWZmZWN0LCB1c2VNZW1vLCB1c2VTdGF0ZSB9IGZyb20gInJlYWN0IjsKaW1wb3J0IHsgdXNlUm91dGVyIH0gZnJvbSAibmV4dC9uYXZpZ2F0aW9uIjsKCnR5cGUgQW55UmVjZWlwdCA9IHsKICBpZD86IHN0cmluZzsKICBjb2RlPzogc3RyaW5nIHwgbnVsbDsKICBzaGFyZUNvZGU/OiBzdHJpbmcgfCBudWxsOwp9OwoKdHlwZSBQaWNrdXBSZXF1ZXN0ID0gewogIGlkOiBzdHJpbmc7CiAgbmFtZT86IHN0cmluZyB8IG51bGw7CiAgcGhvbmU/OiBzdHJpbmcgfCBudWxsOwogIGFkZHJlc3M/OiBzdHJpbmcgfCBudWxsOwogIG5vdGVzPzogc3RyaW5nIHwgbnVsbDsKICBzdGF0dXM/OiBzdHJpbmcgfCBudWxsOwogIGNyZWF0ZWRBdD86IHN0cmluZyB8IG51bGw7CiAgcmVjZWlwdD86IEFueVJlY2VpcHQgfCBudWxsOwogIGVjb1JlY2VpcHQ/OiBBbnlSZWNlaXB0IHwgbnVsbDsKfTsKCnR5cGUgUHJvcHMgPSB7CiAgb3JpZ2luOiBzdHJpbmc7CiAgcmVxdWVzdElkOiBzdHJpbmc7Cn07CgpmdW5jdGlvbiBwaWNrQ29kZShyZXE/OiBQaWNrdXBSZXF1ZXN0IHwgbnVsbCk6IHN0cmluZyB8IG51bGwgewogIGlmICghcmVxKSByZXR1cm4gbnVsbDsKICBjb25zdCByID0gcmVxLmVjb1JlY2VpcHQgPz8gcmVxLnJlY2VpcHQ7CiAgaWYgKCFyKSByZXR1cm4gbnVsbDsKICByZXR1cm4gKHIuc2hhcmVDb2RlID8/IHIuY29kZSA/PyBudWxsKSBhcyBzdHJpbmcgfCBudWxsOwp9CgpleHBvcnQgZGVmYXVsdCBmdW5jdGlvbiBDbG9zZVBlZGlkb0NsaWVudCh7IG9yaWdpbiwgcmVxdWVzdElkIH06IFByb3BzKSB7CiAgY29uc3Qgcm91dGVyID0gdXNlUm91dGVyKCk7CiAgY29uc3QgW2xvYWRpbmcsIHNldExvYWRpbmddID0gdXNlU3RhdGUodHJ1ZSk7CiAgY29uc3QgW3JlcUl0ZW0sIHNldFJlcUl0ZW1dID0gdXNlU3RhdGU8UGlja3VwUmVxdWVzdCB8IG51bGw+KG51bGwpOwogIGNvbnN0IFtlcnJvciwgc2V0RXJyb3JdID0gdXNlU3RhdGU8c3RyaW5nIHwgbnVsbD4obnVsbCk7CgogIGNvbnN0IFtzdW1tYXJ5LCBzZXRTdW1tYXJ5XSA9IHVzZVN0YXRlKCIiKTsKICBjb25zdCBbaXRlbXMsIHNldEl0ZW1zXSA9IHVzZVN0YXRlKCIiKTsKICBjb25zdCBbb3BlcmF0b3IsIHNldE9wZXJhdG9yXSA9IHVzZVN0YXRlKCIiKTsKICBjb25zdCBbaXNQdWJsaWMsIHNldElzUHVibGljXSA9IHVzZVN0YXRlKGZhbHNlKTsKCiAgY29uc3QgZXhpc3RpbmdDb2RlID0gdXNlTWVtbygoKSA9PiBwaWNrQ29kZShyZXFJdGVtKSwgW3JlcUl0ZW1dKTsKCiAgdXNlRWZmZWN0KCgpID0+IHsKICAgIGxldCBjYW5jZWxsZWQgPSBmYWxzZTsKICAgIGFzeW5jIGZ1bmN0aW9uIHJ1bigpIHsKICAgICAgc2V0TG9hZGluZyh0cnVlKTsKICAgICAgc2V0RXJyb3IobnVsbCk7CiAgICAgIHRyeSB7CiAgICAgICAgY29uc3QgcmVzID0gYXdhaXQgZmV0Y2goYCR7b3JpZ2lufS9hcGkvcGlja3VwLXJlcXVlc3RzLyR7cmVxdWVzdElkfWAsIHsgY2FjaGU6ICJuby1zdG9yZSIgfSk7CiAgICAgICAgY29uc3QganNvbiA9IGF3YWl0IHJlcy5qc29uKCkuY2F0Y2goKCkgPT4gKHt9KSk7CiAgICAgICAgY29uc3QgZGF0YSA9IChqc29uLml0ZW0gPz8ganNvbi5yZXF1ZXN0ID8/IGpzb24uZGF0YSA/PyBqc29uKSBhcyBhbnk7CiAgICAgICAgY29uc3Qgbm9ybWFsaXplZDogUGlja3VwUmVxdWVzdCB8IG51bGwgPSBkYXRhICYmIGRhdGEuaWQgPyAoZGF0YSBhcyBQaWNrdXBSZXF1ZXN0KSA6IG51bGw7CiAgICAgICAgaWYgKCFjYW5jZWxsZWQpIHNldFJlcUl0ZW0obm9ybWFsaXplZCk7CiAgICAgIH0gY2F0Y2ggKGUpIHsKICAgICAgICBpZiAoIWNhbmNlbGxlZCkgc2V0RXJyb3IoZSBpbnN0YW5jZW9mIEVycm9yID8gZS5tZXNzYWdlIDogU3RyaW5nKGUpKTsKICAgICAgfSBmaW5hbGx5IHsKICAgICAgICBpZiAoIWNhbmNlbGxlZCkgc2V0TG9hZGluZyhmYWxzZSk7CiAgICAgIH0KICAgIH0KICAgIHJ1bigpOwogICAgcmV0dXJuICgpID0+IHsKICAgICAgY2FuY2VsbGVkID0gdHJ1ZTsKICAgIH07CiAgfSwgW29yaWdpbiwgcmVxdWVzdElkXSk7CgogIGFzeW5jIGZ1bmN0aW9uIGVtaXRpcigpIHsKICAgIHNldEVycm9yKG51bGwpOwogICAgdHJ5IHsKICAgICAgY29uc3QgcmVzID0gYXdhaXQgZmV0Y2goYCR7b3JpZ2lufS9hcGkvcmVjZWlwdHNgLCB7CiAgICAgICAgbWV0aG9kOiAiUE9TVCIsCiAgICAgICAgaGVhZGVyczogeyAiY29udGVudC10eXBlIjogImFwcGxpY2F0aW9uL2pzb24iIH0sCiAgICAgICAgYm9keTogSlNPTi5zdHJpbmdpZnkoewogICAgICAgICAgcmVxdWVzdElkLAogICAgICAgICAgc3VtbWFyeTogc3VtbWFyeS50cmltKCkgfHwgbnVsbCwKICAgICAgICAgIGl0ZW1zOiBpdGVtcy50cmltKCkgfHwgbnVsbCwKICAgICAgICAgIG9wZXJhdG9yOiBvcGVyYXRvci50cmltKCkgfHwgbnVsbCwKICAgICAgICAgIHB1YmxpYzogaXNQdWJsaWMsCiAgICAgICAgfSksCiAgICAgIH0pOwogICAgICBjb25zdCBqc29uID0gYXdhaXQgcmVzLmpzb24oKS5jYXRjaCgoKSA9PiAoe30pKTsKICAgICAgaWYgKCFyZXMub2sgfHwgIWpzb24ub2spIHsKICAgICAgICB0aHJvdyBuZXcgRXJyb3IoanNvbi5kZXRhaWwgfHwgandvbi5lcnJvciB8fCBgSFRUUCAke3Jlcy5zdGF0dXN9YCk7CiAgICAgIH0KICAgICAgY29uc3QgcmVjZWlwdCA9IChqc29uLnJlY2VpcHQgPz8gbnVsbCkgYXMgQW55UmVjZWlwdCB8IG51bGw7CiAgICAgIGNvbnN0IGNvZGUgPSAocmVjZWlwdD8uc2hhcmVDb2RlID8/IHJlY2VpcHQ/LmNvZGUgPz8gbnVsbCkgYXMgc3RyaW5nIHwgbnVsbDsKCiAgICAgIGlmIChjb2RlKSB7CiAgICAgICAgcm91dGVyLnB1c2goYC9yZWNpYm8vJHtjb2RlfWApOwogICAgICAgIHJldHVybjsKICAgICAgfQoKICAgICAgLy8gZmFsbGJhY2s6IHZvbHRhIHBhcmEgYSBsaXN0YSBkZSByZWNpYm9zCiAgICAgIHJvdXRlci5wdXNoKCIvcmVjaWJvcyIpOwogICAgfSBjYXRjaCAoZSkgewogICAgICBzZXRFcnJvcihlIGluc3RhbmNlb2YgRXJyb3IgPyBlLm1lc3NhZ2UgOiBTdHJpbmcoZSkpOwogICAgfQogIH0KCiAgcmV0dXJuICgKICAgIDxkaXYgY2xhc3NOYW1lPSJyb3VuZGVkIGJvcmRlciBwLTQiPgogICAgICA8ZGl2IGNsYXNzTmFtZT0iZmxleCBmbGV4LXdyYXAgaXRlbXMtY2VudGVyIGp1c3RpZnktYmV0d2VlbiBnYXAtMiI+CiAgICAgICAgPGRpdiBjbGFzc05hbWU9InRleHQtc20gdGV4dC1ncmF5LTYwMCI+CiAgICAgICAgICB7bG9hZGluZyA/ICJDYXJyZWdhbmRvIHBlZGlkby4uLiIgOiByZXFJdGVtID8gIlBlZGlkbyBjYXJyZWdhZG8uIiA6ICJQZWRpZG8gbsOjbyBlbmNvbnRyYWRvLiJ9CiAgICAgICAgPC9kaXY+CgogICAgICAgIDxkaXYgY2xhc3NOYW1lPSJmbGV4IGdhcC0yIj4KICAgICAgICAgIDxMaW5rIGhyZWY9Ii9wZWRpZG9zIiBjbGFzc05hbWU9InJvdW5kZWQgYm9yZGVyIGJvcmRlci1ibGFjayBweC0zIHB5LTIgdGV4dC14cyBmb250LXNlbWlib2xkIj4KICAgICAgICAgICAgVm9sdGFyCiAgICAgICAgICA8L0xpbms+CiAgICAgICAgICB7ZXhpc3RpbmdDb2RlID8gKAogICAgICAgICAgICA8TGluayBocmVmPXsgYC9yZWNpYm8vJHtleGlzdGluZ0NvZGV9YCB9IGNsYXNzTmFtZT0icm91bmRlZCBiZy1ibGFjayBweC0zIHB5LTIgdGV4dC14cyBmb250LXNlbWlib2xkIHRleHQtd2hpdGUiPgogICAgICAgICAgICAgIFZlciByZWNpYm8gYXR1YWwKICAgICAgICAgICAgPC9MaW5rPgogICAgICAgICAgKSA6IG51bGx9CiAgICAgICAgPC9kaXY+CiAgICAgIDwvZGl2PgoKICAgICAge2Vycm9yID8gKAogICAgICAgIDxkaXYgY2xhc3NOYW1lPSJtdC0zIHJvdW5kZWQgYm9yZGVyIGJvcmRlci1yZWQtMzAwIGJnLXJlZC01MCBwLTMgdGV4dC1zbSI+CiAgICAgICAgICA8ZGl2IGNsYXNzTmFtZT0iZm9udC1zZW1pYm9sZCI+RXJybzwvZGl2PgogICAgICAgICAgPGRpdiBjbGFzc05hbWU9Im10LTEgYnJlYWstd29yZHMiPntlcnJvcn08L2Rpdj4KICAgICAgICA8L2Rpdj4KICAgICAgKSA6IG51bGx9CgogICAgICB7cmVxSXRlbSA/ICgKICAgICAgICA8ZGl2IGNsYXNzTmFtZT0ibXQtNCBncmlkIGdhcC0zIj4KICAgICAgICAgIDxkaXYgY2xhc3NOYW1lPSJyb3VuZGVkIGJnLWdyYXktNTAgcC0zIHRleHQtc20iPgogICAgICAgICAgICA8ZGl2PjxzcGFuIGNsYXNzTmFtZT0iZm9udC1zZW1pYm9sZCI+Tm9tZTo8L3NwYW4+IHtyZXFJdGVtLm5hbWUgPz8gIi0ifTwvZGl2PgogICAgICAgICAgICA8ZGl2PjxzcGFuIGNsYXNzTmFtZT0iZm9udC1zZW1pYm9sZCI+VGVsZWZvbmU6PC9zcGFuPiB7cmVxSXRlbS5waG9uZSA/PyAiLSJ9PC9kaXY+CiAgICAgICAgICAgIDxkaXY+PHNwYW4gY2xhc3NOYW1lPSJmb250LXNlbWlib2xkIj5FbmRlcmXDp286PC9zcGFuPiB7cmVxSXRlbS5hZGRyZXNzID8/ICItIn08L2Rpdj4KICAgICAgICAgICAgPGRpdiA+PHNwYW4gY2xhc3NOYW1lPSJmb250LXNlbWlib2xkIj5TdGF0dXM6PC9zcGFuPiB7cmVxSXRlbS5zdGF0dXMgPz8gIi0ifTwvZGl2PgogICAgICAgICAgPC9kaXY+CgogICAgICAgICAgPGRpdiBjbGFzc05hbWU9ImdyaWQgZ2FwLTIiPgogICAgICAgICAgICA8bGFiZWwgY2xhc3NOYW1lPSJ0ZXh0LXNtIGZvbnQtc2VtaWJvbGQiPlJlc3VtbyBkbyByZWNpYm88L2xhYmVsPgogICAgICAgICAgICA8dGV4dGFyZWEKICAgICAgICAgICAgICBjbGFzc05hbWU9InctZnVsbCByb3VuZGVkIGJvcmRlciBwLTIgdGV4dC1zbSIKICAgICAgICAgICAgICByb3dzPXszfQogICAgICAgICAgICAgIHZhbHVlPXtzdW1tYXJ5fQogICAgICAgICAgICAgIG9uQ2hhbmdlPXsoZSkgPT4gc2V0U3VtbWFyeShlLnRhcmdldC52YWx1ZSl9CiAgICAgICAgICAgICAgcGxhY2Vob2xkZXI9IkV4LjogQ29sZXRhIHJlc2lkZW5jaWFsIOKAlCBzYWNvICsgY2FpeGEg4oCTIHRyaWFnZW0gbm8gZ2FscMOjby4uLiIKICAgICAgICAgICAgLz4KICAgICAgICAgIDwvZGl2PgoKICAgICAgICAgIDxkaXYgY2xhc3NOYW1lPSJncmlkIGdhcC0yIj4KICAgICAgICAgICAgPGxhYmVsIGNsYXNzTmFtZT0idGV4dC1zbSBmb250LXNlbWlib2xkIj5JdGVucyAvIG9ic2VydmHDp8O1ZXM8L2xhYmVsPgogICAgICAgICAgICA8dGV4dGFyZWEKICAgICAgICAgICAgICBjbGFzc05hbWU9InctZnVsbCByb3VuZGVkIGJvcmRlciBwLTIgdGV4dC1zbSIKICAgICAgICAgICAgICByb3dzPXs0fQogICAgICAgICAgICAgIHZhbHVlPXtpdGVtc30KICAgICAgICAgICAgICBvbkNoYW5nZT17KGUpID0+IHNldEl0ZW1zKGUudGFyZ2V0LnZhbHVlKX0KICAgICAgICAgICAgICBwbGFjZWhvbGRlcj0iRXguOiAxIHNhY28gcGzDoXN0aWNvIG1pc3RvOyAxIGNhaXhhIHBhcGVsw6NvOyAxTCDDs2xlby4uLiIKICAgICAgICAgICAgLz4KICAgICAgICAgIDwvZGl2PgoKICAgICAgICAgIDxkaXYgY2xhc3NOYW1lPSJncmlkIGdhcC0yIj4KICAgICAgICAgICAgPGxhYmVsIGNsYXNzTmFtZT0idGV4dC1zbSBmb250LXNlbWlib2xkIj5PcGVyYWRvcjwvbGFiZWw+CiAgICAgICAgICAgIDxpbnB1dAogICAgICAgICAgICAgIGNsYXNzTmFtZT0idy1mdWxsIHJvdW5kZWQgYm9yZGVyIHAtMiB0ZXh0LXNtIgogICAgICAgICAgICAgIHZhbHVlPXtvcGVyYXRvcn0KICAgICAgICAgICAgICBvbkNoYW5nZT17KGUpID0+IHNldE9wZXJhdG9yKGUudGFyZ2V0LnZhbHVlKX0KICAgICAgICAgICAgICBwbGFjZWhvbGRlcj0iRXguOiBDb29wZXJhdGl2YSBFQ08gLyBGdWxhbm8iCiAgICAgICAgICAgIC8+CiAgICAgICAgICA8L2Rpdj4KCiAgICAgICAgICA8bGFiZWwgY2xhc3NOYW1lPSJmbGV4IGl0ZW1zLWNlbnRlciBnYXAtMiB0ZXh0LXNtIj4KICAgICAgICAgICAgPGlucHV0IHR5cGU9ImNoZWNrYm94IiBjaGVja2VkPXtpc1B1YmxpY30gb25DaGFuZ2U9eyhlKSA9PiBzZXRJc1B1YmxpYyhlLnRhcmdldC5jaGVja2VkKX0gLz4KICAgICAgICAgICAgUmVjaWJvIHB1YmxpY28gKG9wdC1pbikKICAgICAgICAgIDwvbGFiZWw+CgogICAgICAgICAgPGJ1dHRvbgogICAgICAgICAgICBvbkNsaWNrPXtlbWl0aXJ9CiAgICAgICAgICAgIGNsYXNzTmFtZT0icm91bmRlZCBiZy1ibGFjayBweC00IHB5LTIgdGV4dC1zbSBmb250LXNlbWlib2xkIHRleHQtd2hpdGUgZGlzYWJsZWQ6b3BhY2l0eS01MCIKICAgICAgICAgICAgZGlzYWJsZWQ9e2xvYWRpbmd9CiAgICAgICAgICA+CiAgICAgICAgICAgIEVtaXRpciByZWNpYm8KICAgICAgICAgIDwvYnV0dG9uPgoKICAgICAgICAgIDxkaXYgY2xhc3NOYW1lPSJ0ZXh0LXhzIHRleHQtZ3JheS02MDAiPgogICAgICAgICAgICBTZSBqw6EgZXhpc3RpciB1bSByZWNpYm8gcGFyYSBlc3RlIHBlZGlkbywgbyBib3TDo28gdmFpIGF0dWFsaXphciAodXBzZXJ0KSBvIG1lc21vIHJlZ2lzdHJvLgogICAgICAgICAgPC9kaXY+CiAgICAgICAgPC9kaXY+CiAgICAgICkgOiBudWxsfQogICAgPC9kaXY+CiAgKTsKfQo="

$closePageBak = BackupFile $closePagePath
$closeClientBak = BackupFile $closeClientPath

WriteUtf8NoBom $closePagePath (DecodeB64 $b64ClosePage)
WriteUtf8NoBom $closeClientPath (DecodeB64 $b64CloseClient)

$log += ("- OK: criado/atualizado -> {0}" -f $closePagePath)
if($closePageBak){ $log += ("  - backup: {0}" -f $closePageBak) }
$log += ("- OK: criado/atualizado -> {0}" -f $closeClientPath)
if($closeClientBak){ $log += ("  - backup: {0}" -f $closeClientBak) }
$log += ""

# 3) Smoke: adiciona /pedidos se não existir
$smokePath = "tools/eco-smoke.ps1"
if(Test-Path -LiteralPath $smokePath){
  $smoke = Get-Content -LiteralPath $smokePath -Raw
  if($smoke -notmatch '"/pedidos"' -and $smoke -notmatch "'/pedidos'"){
    $smokeBak = BackupFile $smokePath
    if($smoke -match '"/recibos"'){
      $smoke = $smoke -replace '"/recibos"','"/recibos",`n  "/pedidos"'
    } elseif($smoke -match "'/recibos'") {
      $smoke = $smoke -replace "'/recibos'","'/recibos',`n  '/pedidos'"
    } elseif($smoke -match '@\(') {
      $smoke = $smoke -replace '@\(', '@(`n  "/pedidos",'
    } else {
      $smoke += "`n# auto-add`n"
      $smoke += "`n"
    }
    WriteUtf8NoBom $smokePath $smoke
    $log += "- OK: eco-smoke atualizado (inclui /pedidos)"
    if($smokeBak){ $log += ("  - backup: {0}" -f $smokeBak) }
  } else {
    $log += "- OK: eco-smoke já inclui /pedidos (sem alteração)"
  }
} else {
  $log += "- WARN: tools/eco-smoke.ps1 não encontrado (pulei patch no smoke)"
}
$log += ""

# ===== VERIFY =====
$log += "## VERIFY"
try {
  $out = pwsh -NoProfile -ExecutionPolicy Bypass -File .\tools\eco-smoke.ps1 2>&1
  $log += "### eco-smoke output"
  $log += '```'
  $log += ($out | Out-String).TrimEnd()
  $log += '```'
} catch {
  $log += "### eco-smoke output"
  $log += '```'
  $log += ($_ | Out-String).TrimEnd()
  $log += '```'
  WriteUtf8NoBom $rep ($log -join "`n")
  throw
}

# ===== REGISTRO =====
$log += ""
$log += "## Próximos passos"
$log += "1) Reinicie o dev: npm run dev (se necessário)"
$log += "2) Abra /pedidos e clique em 'Fechar / Emitir recibo' em um pedido existente"
$log += "3) Preencha resumo/itens e clique 'Emitir recibo' (vai redirecionar para /recibo/[code])"
$log += "4) Volte em /pedidos e confira aparecer 'Ver recibo'"

WriteUtf8NoBom $rep ($log -join "`n")
Write-Host ("✅ STEP 07 aplicado. Report -> {0}" -f $rep) -ForegroundColor Green
Write-Host "PRÓXIMOS PASSOS:" -ForegroundColor Yellow
Write-Host "1) Abra /pedidos e clique em 'Fechar / Emitir recibo'" -ForegroundColor Yellow
Write-Host "2) Depois de emitir, volte em /pedidos e veja o botão 'Ver recibo'" -ForegroundColor Yellow