param(
  [string]$Root = (Get-Location).Path
)

$ts = Get-Date -Format "yyyyMMdd-HHmmss"

$boot = Join-Path $Root "tools/_bootstrap.ps1"
if (Test-Path -LiteralPath $boot) { . $boot }

if (-not (Get-Command EnsureDir -ErrorAction SilentlyContinue)) {
  function EnsureDir([string]$p) { if (-not (Test-Path -LiteralPath $p)) { New-Item -ItemType Directory -Force -Path $p | Out-Null } }
}
if (-not (Get-Command WriteUtf8NoBom -ErrorAction SilentlyContinue)) {
  function WriteUtf8NoBom([string]$p, [string]$content) {
    EnsureDir (Split-Path -Parent $p)
    $enc = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($p, $content, $enc)
  }
}
if (-not (Get-Command BackupFile -ErrorAction SilentlyContinue)) {
  function BackupFile([string]$root, [string]$p, [string]$backupDir) {
    if (Test-Path -LiteralPath $p) {
      $rel = $p.Substring($root.Length).TrimStart('\','/')
      $dest = Join-Path $backupDir ($rel -replace '[\\/]', '__')
      Copy-Item -Force -LiteralPath $p -Destination $dest
      Write-Host ('[BK] ' + $rel + ' -> ' + (Split-Path -Leaf $dest))
    }
  }
}

Write-Host ('== eco-step-89-mural-topbar-transparencia-v0_1 == ' + $ts)
Write-Host ('[DIAG] Root: ' + $Root)

$clientComp = Join-Path $Root 'src/app/eco/mural/_components/MuralTopBarClient.tsx'
if (-not (Test-Path -LiteralPath $clientComp)) { throw "[STOP] Nao achei: src/app/eco/mural/_components/MuralTopBarClient.tsx" }

$backupDir = Join-Path $Root ('tools/_patch_backup/' + $ts + '-eco-step-89-mural-topbar-transparencia-v0_1')
$reportDir = Join-Path $Root 'reports'
EnsureDir $backupDir
EnsureDir $reportDir
BackupFile $Root $clientComp $backupDir

Write-Host ('[DIAG] Will rewrite: ' + $clientComp)

$L = New-Object System.Collections.Generic.List[string]

$L.Add('"use client";')
$L.Add('')
$L.Add('import Link from "next/link";')
$L.Add('import { useEffect, useMemo, useState } from "react";')
$L.Add('')
$L.Add('type AnyRow = any;')
$L.Add('')
$L.Add('function num(v: any) {')
$L.Add('  const n = Number(v);')
$L.Add('  return Number.isFinite(n) ? n : 0;')
$L.Add('}')
$L.Add('')
$L.Add('function pickCount(p: any, keys: string[]) {')
$L.Add('  for (const k of keys) {')
$L.Add('    const v = p?.[k] ?? p?.counts?.[k] ?? p?.actions?.[k] ?? p?.stats?.[k];')
$L.Add('    const n = num(v);')
$L.Add('    if (n) return n;')
$L.Add('  }')
$L.Add('  return 0;')
$L.Add('}')
$L.Add('')
$L.Add('function localDay(d = new Date()) {')
$L.Add('  const y = d.getFullYear();')
$L.Add('  const m = String(d.getMonth() + 1).padStart(2, "0");')
$L.Add('  const dd = String(d.getDate()).padStart(2, "0");')
$L.Add('  return String(y) + "-" + m + "-" + dd;')
$L.Add('}')
$L.Add('')
$L.Add('function localMonth(d = new Date()) {')
$L.Add('  const y = d.getFullYear();')
$L.Add('  const m = String(d.getMonth() + 1).padStart(2, "0");')
$L.Add('  return String(y) + "-" + m;')
$L.Add('}')
$L.Add('')
$L.Add('async function tryJson(url: string) {')
$L.Add('  const res = await fetch(url, { cache: "no-store" });')
$L.Add('  if (!res.ok) throw new Error("fetch_failed:" + res.status);')
$L.Add('  return await res.json();')
$L.Add('}')
$L.Add('')
$L.Add('async function loadList(tries: string[]) {')
$L.Add('  for (const t of tries) {')
$L.Add('    try {')
$L.Add('      const j = await tryJson(t);')
$L.Add('      const items = j?.items ?? j?.data ?? j?.list ?? j?.rows ?? j?.points ?? j?.mutiroes ?? j?.criticalPoints;')
$L.Add('      if (Array.isArray(items)) return { ok: true as const, items, src: t };')
$L.Add('    } catch {}')
$L.Add('  }')
$L.Add('  return { ok: false as const, items: [] as AnyRow[], src: "none" };')
$L.Add('}')
$L.Add('')
$L.Add('async function loadDayCloseList() {')
$L.Add('  const tries = [')
$L.Add('    "/api/eco/day-close/list?limit=60",')
$L.Add('    "/api/eco/day-close/list?limit=45",')
$L.Add('    "/api/eco/day-close/list?limit=30",')
$L.Add('  ];')
$L.Add('  for (const t of tries) {')
$L.Add('    try {')
$L.Add('      const j = await tryJson(t);')
$L.Add('      const items = j?.items ?? j?.data ?? j?.list ?? j?.rows;')
$L.Add('      if (Array.isArray(items)) return { ok: true as const, items, src: t };')
$L.Add('    } catch {}')
$L.Add('  }')
$L.Add('  return { ok: false as const, items: [] as AnyRow[], src: "none" };')
$L.Add('}')
$L.Add('')
$L.Add('function sumKgFromDayCloseItems(items: AnyRow[]) {')
$L.Add('  let total = 0;')
$L.Add('  const byMat: Record<string, number> = {};')
$L.Add('  for (const it of items || []) {')
$L.Add('    const s = it?.summary ?? it?.data?.summary ?? it?.item?.summary ?? it?.payload?.summary;')
$L.Add('    const totals = s?.totals ?? s?.summary?.totals ?? {};')
$L.Add('    const kg = num(totals?.totalKg ?? totals?.kg ?? totals?.total ?? 0);')
$L.Add('    total += kg;')
$L.Add('    const bm = totals?.byMaterialKg ?? totals?.byMaterial ?? {};')
$L.Add('    if (bm && typeof bm === "object") {')
$L.Add('      for (const k of Object.keys(bm)) {')
$L.Add('        const v = num((bm as any)[k]);')
$L.Add('        byMat[k] = (byMat[k] || 0) + v;')
$L.Add('      }')
$L.Add('    }')
$L.Add('  }')
$L.Add('  return { totalKg: total, byMat };')
$L.Add('}')
$L.Add('')
$L.Add('function fmtKg(v: number) {')
$L.Add('  const n = Math.round((v || 0) * 10) / 10;')
$L.Add('  return String(n).replace(".", ",") + " kg";')
$L.Add('}')
$L.Add('')
$L.Add('function matLabel(k: string) {')
$L.Add('  const t = String(k || "").toLowerCase();')
$L.Add('  if (t.includes("papel")) return "Papel";')
$L.Add('  if (t.includes("plast")) return "Plástico";')
$L.Add('  if (t.includes("metal")) return "Metal";')
$L.Add('  if (t.includes("vidro")) return "Vidro";')
$L.Add('  if (t.includes("oleo")) return "Óleo";')
$L.Add('  if (t.includes("e-lixo") || t.includes("elixo")) return "E-lixo";')
$L.Add('  if (t.includes("reje")) return "Rejeito";')
$L.Add('  if (t.includes("org")) return "Orgânico";')
$L.Add('  return "Outros";')
$L.Add('}')
$L.Add('')
$L.Add('export default function MuralTopBarClient() {')
$L.Add('  const [pointsRes, setPointsRes] = useState<{ ok: boolean; items: AnyRow[]; src: string }>({ ok: false, items: [], src: "loading" });')
$L.Add('  const [mutRes, setMutRes] = useState<{ ok: boolean; items: AnyRow[]; src: string }>({ ok: false, items: [], src: "loading" });')
$L.Add('  const [dayCloseRes, setDayCloseRes] = useState<{ ok: boolean; items: AnyRow[]; src: string }>({ ok: false, items: [], src: "loading" });')
$L.Add('')
$L.Add('  useEffect(() => {')
$L.Add('    let alive = true;')
$L.Add('    ;(async () => {')
$L.Add('      const p = await loadList([')
$L.Add('        "/api/eco/points/list?limit=200",')
$L.Add('        "/api/eco/points?limit=200",')
$L.Add('        "/api/eco/critical/list?limit=200",')
$L.Add('        "/api/eco/critical?limit=200",')
$L.Add('      ]);')
$L.Add('      const m = await loadList([')
$L.Add('        "/api/eco/mutirao/list?limit=20",')
$L.Add('        "/api/eco/mutiroes/list?limit=20",')
$L.Add('        "/api/eco/mutirao?limit=20",')
$L.Add('      ]);')
$L.Add('      const dc = await loadDayCloseList();')
$L.Add('      if (!alive) return;')
$L.Add('      setPointsRes(p as any);')
$L.Add('      setMutRes(m as any);')
$L.Add('      setDayCloseRes(dc as any);')
$L.Add('    })();')
$L.Add('    return () => { alive = false; };')
$L.Add('  }, []);')
$L.Add('')
$L.Add('  const computed = useMemo(() => {')
$L.Add('    const points = pointsRes.items || [];')
$L.Add('    const chamados = points')
$L.Add('      .filter((p: any) => String(p?.status || p?.state || "").toUpperCase() === "OPEN")')
$L.Add('      .map((p: any) => ({')
$L.Add('        p,')
$L.Add('        called: pickCount(p, ["call", "callCount", "chamado", "chamados", "CALL", "CALLED"]),')
$L.Add('        confirm: pickCount(p, ["confirm", "confirmCount", "confirmar", "seen", "ok", "OK"]),')
$L.Add('      }))')
$L.Add('      .sort((a: any, b: any) => (b.called - a.called) || (b.confirm - a.confirm))')
$L.Add('      .slice(0, 6);')
$L.Add('')
$L.Add('    const confirmados = points')
$L.Add('      .map((p: any) => ({')
$L.Add('        p,')
$L.Add('        confirm: pickCount(p, ["confirm", "confirmCount", "confirmar", "seen", "ok", "OK"]),')
$L.Add('        called: pickCount(p, ["call", "callCount", "chamado", "chamados", "CALL", "CALLED"]),')
$L.Add('      }))')
$L.Add('      .sort((a: any, b: any) => (b.confirm - a.confirm) || (b.called - a.called))')
$L.Add('      .slice(0, 6);')
$L.Add('')
$L.Add('    const mutiroes = (mutRes.items || []).slice(0, 6);')
$L.Add('')
$L.Add('    // Transparência (day-close)')
$L.Add('    const raw = (dayCloseRes.items || []).slice();')
$L.Add('    raw.sort((a: any, b: any) => String(b?.day || "").localeCompare(String(a?.day || "")));')
$L.Add('    const last7 = raw.slice(0, 7);')
$L.Add('    const mo = localMonth(new Date());')
$L.Add('    const monthItems = raw.filter((x: any) => String(x?.day || "").startsWith(mo + "-"));')
$L.Add('')
$L.Add('    const s7 = sumKgFromDayCloseItems(last7);')
$L.Add('    const sm = sumKgFromDayCloseItems(monthItems);')
$L.Add('')
$L.Add('    const lastDay = String(last7?.[0]?.day || localDay(new Date()));')
$L.Add('    const mats = Object.keys(sm.byMat || {})')
$L.Add('      .map((k) => ({ k, v: num((sm.byMat as any)[k]) }))')
$L.Add('      .sort((a, b) => b.v - a.v)')
$L.Add('      .slice(0, 3);')
$L.Add('')
$L.Add('    return { chamados, confirmados, mutiroes, last7, monthItems, s7, sm, mo, lastDay, mats };')
$L.Add('  }, [pointsRes, mutRes, dayCloseRes]);')
$L.Add('')
$L.Add('  const box: any = { border: "1px solid #111", borderRadius: 14, padding: 12, background: "#fff" };')
$L.Add('  const h: any = { margin: "0 0 6px 0", fontSize: 12, fontWeight: 950, letterSpacing: 0.2, opacity: 0.9 };')
$L.Add('  const a: any = { textDecoration: "none", color: "#111" };')
$L.Add('  const row: any = { display: "flex", justifyContent: "space-between", gap: 10, fontSize: 12, padding: "6px 0", borderTop: "1px dashed rgba(0,0,0,0.15)" };')
$L.Add('')
$L.Add('  return (')
$L.Add('    <section')
$L.Add('      style={{')
$L.Add('        position: "sticky",')
$L.Add('        top: 0,')
$L.Add('        zIndex: 50,')
$L.Add('        background: "rgba(245,245,245,0.92)",')
$L.Add('        backdropFilter: "blur(6px)",')
$L.Add('        padding: "10px 0 12px 0",')
$L.Add('        borderBottom: "1px solid rgba(0,0,0,0.15)",')
$L.Add('      }}')
$L.Add('    >')
$L.Add('      <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))", gap: 10 }}>')
$L.Add('        <div style={box}>')
$L.Add('          <div style={h}>📣 Chamados ativos</div>')
$L.Add('          <div style={{ fontSize: 12, opacity: 0.75, marginBottom: 6 }}>Pontos OPEN com chamado</div>')
$L.Add('          <div>')
$L.Add('            {computed.chamados.length === 0 ? (')
$L.Add('              <div style={{ fontSize: 12, opacity: 0.75 }}>Nenhum chamado encontrado.</div>')
$L.Add('            ) : (')
$L.Add('              computed.chamados.map((x: any, idx: number) => (')
$L.Add('                <div key={idx} style={row}>')
$L.Add('                  <Link href={"/eco/pontos/" + String(x.p?.id || "")} style={a}>')
$L.Add('                    {String(x.p?.title || x.p?.name || x.p?.bairro || "Ponto")}') 
$L.Add('                  </Link>')
$L.Add('                  <span style={{ fontWeight: 950 }}>📣 {x.called || 0}</span>')
$L.Add('                </div>')
$L.Add('              ))')
$L.Add('            )}')
$L.Add('          </div>')
$L.Add('          <div style={{ marginTop: 8, fontSize: 11, opacity: 0.6 }}>src: {pointsRes.src}</div>')
$L.Add('        </div>')
$L.Add('')
$L.Add('        <div style={box}>')
$L.Add('          <div style={h}>✅ Mais confirmados</div>')
$L.Add('          <div style={{ fontSize: 12, opacity: 0.75, marginBottom: 6 }}>Onde mais gente disse “eu vi também”</div>')
$L.Add('          <div>')
$L.Add('            {computed.confirmados.length === 0 ? (')
$L.Add('              <div style={{ fontSize: 12, opacity: 0.75 }}>Sem dados ainda.</div>')
$L.Add('            ) : (')
$L.Add('              computed.confirmados.map((x: any, idx: number) => (')
$L.Add('                <div key={idx} style={row}>')
$L.Add('                  <Link href={"/eco/pontos/" + String(x.p?.id || "")} style={a}>')
$L.Add('                    {String(x.p?.title || x.p?.name || x.p?.bairro || "Ponto")}')
$L.Add('                  </Link>')
$L.Add('                  <span style={{ fontWeight: 950 }}>✅ {x.confirm || 0}</span>')
$L.Add('                </div>')
$L.Add('              ))')
$L.Add('            )}')
$L.Add('          </div>')
$L.Add('          <div style={{ marginTop: 8, fontSize: 11, opacity: 0.6 }}>src: {pointsRes.src}</div>')
$L.Add('        </div>')
$L.Add('')
$L.Add('        <div style={box}>')
$L.Add('          <div style={h}>🧹 Mutirões recentes</div>')
$L.Add('          <div style={{ fontSize: 12, opacity: 0.75, marginBottom: 6 }}>Antes/depois + prova</div>')
$L.Add('          <div>')
$L.Add('            {computed.mutiroes.length === 0 ? (')
$L.Add('              <div style={{ fontSize: 12, opacity: 0.75 }}>Sem mutirões listados.</div>')
$L.Add('            ) : (')
$L.Add('              computed.mutiroes.map((m: any, idx: number) => (')
$L.Add('                <div key={idx} style={row}>')
$L.Add('                  <Link href={"/eco/mutiroes/" + String(m?.id || "")} style={a}>')
$L.Add('                    {String(m?.title || m?.bairro || "Mutirão")}')
$L.Add('                  </Link>')
$L.Add('                  <span style={{ fontWeight: 950, opacity: 0.9 }}>→</span>')
$L.Add('                </div>')
$L.Add('              ))')
$L.Add('            )}')
$L.Add('          </div>')
$L.Add('          <div style={{ marginTop: 8, fontSize: 11, opacity: 0.6 }}>src: {mutRes.src}</div>')
$L.Add('        </div>')
$L.Add('')
$L.Add('        <div style={box}>')
$L.Add('          <div style={h}>📊 Transparência</div>')
$L.Add('          <div style={{ fontSize: 12, opacity: 0.75, marginBottom: 8 }}>Recibo é lei. 7 dias + mês atual.</div>')
$L.Add('          <div style={{ display: "grid", gap: 8 }}>')
$L.Add('            <div style={{ display: "flex", justifyContent: "space-between", gap: 10 }}>')
$L.Add('              <span style={{ fontSize: 12, opacity: 0.85 }}>Últimos 7 dias</span>')
$L.Add('              <span style={{ fontWeight: 950 }}>{fmtKg(computed.s7.totalKg)}</span>')
$L.Add('            </div>')
$L.Add('            <div style={{ display: "flex", justifyContent: "space-between", gap: 10 }}>')
$L.Add('              <span style={{ fontSize: 12, opacity: 0.85 }}>Mês {computed.mo}</span>')
$L.Add('              <span style={{ fontWeight: 950 }}>{fmtKg(computed.sm.totalKg)}</span>')
$L.Add('            </div>')
$L.Add('            {computed.mats.length > 0 ? (')
$L.Add('              <div style={{ fontSize: 12, opacity: 0.9 }}>')
$L.Add('                {computed.mats.map((x, i) => (')
$L.Add('                  <span key={i} style={{ display: "inline-block", marginRight: 8, marginTop: 4, padding: "2px 8px", border: "1px solid rgba(0,0,0,0.25)", borderRadius: 999, background: "rgba(0,0,0,0.03)" }}>')
$L.Add('                    {matLabel(x.k)}: {fmtKg(x.v)}')
$L.Add('                  </span>')
$L.Add('                ))}')
$L.Add('              </div>')
$L.Add('            ) : (')
$L.Add('              <div style={{ fontSize: 12, opacity: 0.65 }}>Ainda sem fechamento consolidado no mês.</div>')
$L.Add('            )}')
$L.Add('            <div style={{ display: "flex", gap: 8, flexWrap: "wrap", marginTop: 2 }}>')
$L.Add('              <Link href={"/eco/share/mes/" + computed.mo} style={{ textDecoration: "none", color: "#111", fontWeight: 950, padding: "7px 10px", borderRadius: 12, border: "1px solid #111", background: "#fff" }}>')
$L.Add('                Compartilhar mês')
$L.Add('              </Link>')
$L.Add('              <Link href={"/eco/share/dia/" + computed.lastDay} style={{ textDecoration: "none", color: "#111", fontWeight: 950, padding: "7px 10px", borderRadius: 12, border: "1px solid rgba(0,0,0,0.35)", background: "rgba(255,255,255,0.6)" }}>')
$L.Add('                Compartilhar dia')
$L.Add('              </Link>')
$L.Add('              <Link href={"/eco/fechamento"} style={{ textDecoration: "none", color: "#111", fontWeight: 950, padding: "7px 10px", borderRadius: 12, border: "1px dashed rgba(0,0,0,0.35)", background: "rgba(255,255,255,0.45)" }}>')
$L.Add('                Ir pro fechamento')
$L.Add('              </Link>')
$L.Add('            </div>')
$L.Add('          </div>')
$L.Add('          <div style={{ marginTop: 8, fontSize: 11, opacity: 0.6 }}>src: {dayCloseRes.src}</div>')
$L.Add('        </div>')
$L.Add('      </div>')
$L.Add('    </section>')
$L.Add('  );')
$L.Add('}')
$L.Add('')

WriteUtf8NoBom $clientComp ($L -join "`n")
Write-Host ('[PATCH] rewrote ' + $clientComp)

$rep = Join-Path $reportDir ('eco-step-89-mural-topbar-transparencia-v0_1-' + $ts + '.md')
$repLines = @(
'# eco-step-89-mural-topbar-transparencia-v0_1',
'',
'- Time: ' + $ts,
'- Backup: ' + $backupDir,
'',
'## What',
'- Reescreve MuralTopBarClient com 4 caixas: Chamados, Confirmados, Mutirões, Transparência.',
'- Transparência usa /api/eco/day-close/list e computa: últimos 7 dias + mês atual (kg).',
'- Links: /eco/share/mes/[YYYY-MM], /eco/share/dia/[YYYY-MM-DD], /eco/fechamento.',
'',
'## Verify',
'1) Ctrl+C -> npm run dev',
'2) Abrir /eco/mural',
'3) Caixa "Transparência" aparece com valores (ou 0 se sem dados)',
'4) Clicar "Compartilhar mês" e "Compartilhar dia" abre as páginas'
)
WriteUtf8NoBom $rep ($repLines -join "`n")
Write-Host ('[REPORT] ' + $rep)

Write-Host ""
Write-Host "[VERIFY] Ctrl+C -> npm run dev"
Write-Host "[VERIFY] /eco/mural -> conferir caixa Transparência + botões"