param(
  [string]$BaseUrl = "http://localhost:3000",
  [switch]$Reseed,
  [switch]$Completions,
  [string]$VolunteerId = "vol-TESTE-123"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

. (Join-Path $PSScriptRoot "_pslib.ps1")

$ts = (Get-Date).ToString("yyyyMMdd-HHmmss")
$backup = Join-Path $PSScriptRoot ("_patch_backup\" + $ts + "-seed-missoes-dev-v0_1")
EnsureDir $backup
Set-BackupDir $backup

$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$reportsDir = Join-Path $repoRoot "reports"
EnsureDir $reportsDir

$routePath = Join-Path $repoRoot "app/api/dev/seed-missoes/route.ts"
EnsureDir (Split-Path -Parent $routePath)
BackupFile $routePath

$routeLines = @(
  'import { NextResponse } from "next/server";',
  'import { prisma } from "@/lib/prisma";',
  'import { Prisma } from "@prisma/client";',
  'import { MISSOES } from "@/lib/missoes-data";',
  '',
  'export const runtime = "nodejs";',
  'export const dynamic = "force-dynamic";',
  'export const revalidate = 0;',
  '',
  'type AnyRecord = Record<string, unknown>;',
  'type Delegate = {',
  '  findFirst: (args: AnyRecord) => Promise<unknown>;',
  '  create: (args: AnyRecord) => Promise<unknown>;',
  '  deleteMany?: (args: AnyRecord) => Promise<unknown>;',
  '};',
  '',
  'function isRecord(v: unknown): v is AnyRecord {',
  '  return typeof v === "object" && v !== null;',
  '}',
  '',
  'function lowerCamel(s: string) {',
  '  return s ? s.charAt(0).toLowerCase() + s.slice(1) : s;',
  '}',
  '',
  'function modelHasField(model: Prisma.DMMF.Model, name: string) {',
  '  return model.fields.some((f) => f.name === name);',
  '}',
  '',
  'function pickModel(requiredAny: string[][]) {',
  '  const models = Prisma.dmmf.datamodel.models;',
  '  for (const m of models) {',
  '    let ok = true;',
  '    for (const group of requiredAny) {',
  '      const has = group.some((f) => modelHasField(m, f));',
  '      if (!has) { ok = false; break; }',
  '    }',
  '    if (ok) return m;',
  '  }',
  '  return null;',
  '}',
  '',
  'function hasDelegateMethods(v: unknown): v is Delegate {',
  '  if (!isRecord(v)) return false;',
  '  return typeof v["findFirst"] === "function" && typeof v["create"] === "function";',
  '}',
  '',
  'function getDelegate(prismaObj: AnyRecord, key: string): Delegate | null {',
  '  const d = prismaObj[key];',
  '  return hasDelegateMethods(d) ? d : null;',
  '}',
  '',
  'function extractMissionSeed(raw: unknown, idx: number) {',
  '  const m: AnyRecord = isRecord(raw) ? raw : {};',
  '  const key = (m["key"] ?? m["slug"] ?? m["code"] ?? m["missionSlug"] ?? ("missao-" + String(idx)));',
  '  const slug = typeof key === "string" ? key : ("missao-" + String(idx));',
  '  const t = (m["title"] ?? m["titulo"] ?? m["nome"] ?? slug);',
  '  const title = typeof t === "string" ? t : slug;',
  '  const r = (m["resumo"] ?? m["shortDescription"] ?? m["descricao"] ?? m["description"] ?? null);',
  '  const resumo = typeof r === "string" ? r : null;',
  '  const p = (m["pautaSlug"] ?? m["pauta"] ?? null);',
  '  const pautaSlug = typeof p === "string" ? p : null;',
  '  const f = (m["fase"] ?? null);',
  '  const fase = typeof f === "string" ? f : null;',
  '  const e = (m["eixo"] ?? null);',
  '  const eixo = typeof e === "string" ? e : null;',
  '  const x = (m["xpBase"] ?? m["xp"] ?? 50);',
  '  const xp = (typeof x === "number" && !Number.isNaN(x)) ? x : 50;',
  '  return { slug, title, resumo, pautaSlug, fase, eixo, xp };',
  '}',
  '',
  'function buildData(fields: string[], seed: ReturnType<typeof extractMissionSeed>) {',
  '  const data: AnyRecord = {};',
  '  const set = (names: string[], value: unknown) => {',
  '    for (const n of names) {',
  '      if (fields.includes(n) && value !== undefined) { data[n] = value; return; }',
  '    }',
  '  };',
  '  set(["slug", "code", "missionSlug", "missionCode", "key"], seed.slug);',
  '  set(["title", "titulo", "nome", "name"], seed.title);',
  '  set(["resumo", "shortDescription", "descricao", "description"], seed.resumo);',
  '  set(["pautaSlug", "pauta"], seed.pautaSlug);',
  '  set(["fase"], seed.fase);',
  '  set(["eixo"], seed.eixo);',
  '  set(["xp", "xpBase"], seed.xp);',
  '  if (fields.includes("isActive") && data["isActive"] === undefined) data["isActive"] = true;',
  '  if (fields.includes("active") && data["active"] === undefined) data["active"] = true;',
  '  return data;',
  '}',
  '',
  'async function safeFindFirst(delegate: Delegate, where: AnyRecord) {',
  '  try { return await delegate.findFirst({ where }); } catch { return null; }',
  '}',
  '',
  'async function safeCreate(delegate: Delegate, data: AnyRecord) {',
  '  try { return await delegate.create({ data }); } catch (e) {',
  '    return { __err: true, message: (e instanceof Error ? e.message : String(e)) };',
  '  }',
  '}',
  '',
  'export async function GET(req: Request) {',
  '  if (process.env.NODE_ENV !== "development") {',
  '    return NextResponse.json({ ok: false, error: "dev only" }, { status: 403 });',
  '  }',
  '',
  '  const u = new URL(req.url);',
  '  const reseed = u.searchParams.get("reseed") === "1";',
  '  const seedCompletions = u.searchParams.get("completions") === "1";',
  '  const volunteerId = u.searchParams.get("volunteerId") ?? "vol-TESTE-123";',
  '',
  '  const prismaObj = prisma as unknown as AnyRecord;',
  '',
  '  const missionModel =',
  '    Prisma.dmmf.datamodel.models.find((m) => m.name === "Mission") ??',
  '    pickModel([',
  '      ["slug", "code", "missionSlug", "missionCode", "key"],',
  '      ["title", "titulo", "nome", "name"],',
  '    ]);',
  '',
  '  const completionModel =',
  '    Prisma.dmmf.datamodel.models.find((m) => m.name === "MissionCompletion") ??',
  '    pickModel([',
  '      ["volunteerId", "personKey"],',
  '      ["missionSlug", "slug", "missionCode", "code", "missionId"],',
  '    ]);',
  '',
  '  const out: AnyRecord = {',
  '    ok: true,',
  '    nodeEnv: process.env.NODE_ENV,',
  '    reseed,',
  '    picked: {',
  '      missionModel: missionModel ? missionModel.name : null,',
  '      completionModel: completionModel ? completionModel.name : null,',
  '    },',
  '  };',
  '',
  '  if (!missionModel) {',
  '    out["missions"] = { ok: false, error: "mission model not found" };',
  '  } else {',
  '    const delegateKey = lowerCamel(missionModel.name);',
  '    const delegate = getDelegate(prismaObj, delegateKey);',
  '    if (!delegate) {',
  '      out["missions"] = { ok: false, error: "delegate not found: prisma." + delegateKey };',
  '    } else {',
  '      const fields = missionModel.fields.map((f) => f.name);',
  '      const created: string[] = [];',
  '      const existed: string[] = [];',
  '      const errors: AnyRecord[] = [];',
  '',
  '      if (reseed && typeof (delegate as AnyRecord)["deleteMany"] === "function") {',
  '        try {',
  '          const del = (delegate as unknown as { deleteMany: (args: AnyRecord) => Promise<unknown> }).deleteMany;',
  '          await del({});',
  '          out["missions_deleted"] = true;',
  '        } catch (e) {',
  '          out["missions_deleted"] = false;',
  '          out["missions_delete_error"] = (e instanceof Error ? e.message : String(e));',
  '        }',
  '      }',
  '',
  '      const list = Array.isArray(MISSOES) ? MISSOES : [];',
  '      for (let i = 0; i < list.length; i++) {',
  '        const seed = extractMissionSeed(list[i], i);',
  '        const data = buildData(fields, seed);',
  '',
  '        const whereOr: AnyRecord[] = [];',
  '        for (const f of ["slug", "code", "missionSlug", "missionCode", "key"]) {',
  '          const v = data[f];',
  '          if (typeof v === "string" && v.length > 0) whereOr.push({ [f]: v });',
  '        }',
  '        const existing = whereOr.length > 0 ? await safeFindFirst(delegate, { OR: whereOr }) : null;',
  '        if (existing) { existed.push(seed.slug); continue; }',
  '',
  '        const c = await safeCreate(delegate, data);',
  '        if (isRecord(c) && c["__err"] === true) errors.push({ slug: seed.slug, error: c["message"] });',
  '        else created.push(seed.slug);',
  '      }',
  '',
  '      out["missions"] = {',
  '        ok: errors.length === 0,',
  '        model: missionModel.name,',
  '        delegate: delegateKey,',
  '        total: list.length,',
  '        created: created.length,',
  '        existed: existed.length,',
  '        createdSlugs: created.slice(0, 20),',
  '        errors,',
  '      };',
  '    }',
  '  }',
  '',
  '  if (seedCompletions) {',
  '    if (!completionModel) {',
  '      out["completions"] = { ok: false, error: "completion model not found" };',
  '    } else {',
  '      const delegateKey = lowerCamel(completionModel.name);',
  '      const delegate = getDelegate(prismaObj, delegateKey);',
  '      if (!delegate) {',
  '        out["completions"] = { ok: false, error: "delegate not found: prisma." + delegateKey };',
  '      } else {',
  '        const fields = completionModel.fields.map((f) => f.name);',
  '        const list = Array.isArray(MISSOES) ? MISSOES : [];',
  '        const take = Math.min(4, list.length);',
  '        let created = 0;',
  '        let existed = 0;',
  '        const errors: AnyRecord[] = [];',
  '',
  '        for (let i = 0; i < take; i++) {',
  '          const seed = extractMissionSeed(list[i], i);',
  '          const data: AnyRecord = {};',
  '          const set = (names: string[], value: unknown) => {',
  '            for (const n of names) { if (fields.includes(n)) { data[n] = value; return; } }',
  '          };',
  '          set(["volunteerId", "personKey"], volunteerId);',
  '          set(["missionSlug", "slug", "missionCode", "code"], seed.slug);',
  '          if (fields.includes("code")) data["code"] = volunteerId + "--" + seed.slug;',
  '',
  '          const whereOr: AnyRecord[] = [];',
  '          if (typeof data["code"] === "string") whereOr.push({ code: data["code"] });',
  '          if (whereOr.length === 0) whereOr.push(data);',
  '',
  '          const existing = await safeFindFirst(delegate, { OR: whereOr });',
  '          if (existing) { existed++; continue; }',
  '',
  '          const c = await safeCreate(delegate, data);',
  '          if (isRecord(c) && c["__err"] === true) errors.push({ slug: seed.slug, error: c["message"] });',
  '          else created++;',
  '        }',
  '',
  '        out["completions"] = { ok: errors.length === 0, model: completionModel.name, delegate: delegateKey, volunteerId, created, existed, errors };',
  '      }',
  '    }',
  '  }',
  '',
  '  return NextResponse.json(out, { status: 200 });',
  '}'
)

WriteLines $routePath $routeLines
Write-Host "OK: escreveu app/api/dev/seed-missoes/route.ts"

Write-Host "--- VERIFY head route.ts"
Get-Content -LiteralPath $routePath -TotalCount 14 | ForEach-Object { $_ }

# smoke call
$qs = @()
if ($Reseed) { $qs += "reseed=1" }
if ($Completions) { $qs += "completions=1" }
if ($VolunteerId) { $qs += ("volunteerId=" + [Uri]::EscapeDataString($VolunteerId)) }
$q = if ($qs.Count -gt 0) { "?" + ($qs -join "&") } else { "" }

$url = $BaseUrl.TrimEnd("/") + "/api/dev/seed-missoes" + $q
Write-Host "--- GET $url"
$r = Invoke-WebRequest -Uri $url -Method GET -MaximumRedirection 0 -TimeoutSec 30
Write-Host ("HTTP " + $r.StatusCode)
$r.Content | Out-Host

$reportPath = Join-Path $reportsDir ("seed-missoes-dev-v0_1-" + $ts + ".md")
$reportLines = @(
  "# Seed Missões (dev) v0_1",
  "",
  ("ts: " + $ts),
  "",
  ("BaseUrl: " + $BaseUrl),
  ("Reseed: " + [string]$Reseed),
  ("Completions: " + [string]$Completions),
  ("VolunteerId: " + $VolunteerId),
  "",
  ("Endpoint: " + $url),
  "",
  "Obs: usa MISSOES de @/lib/missoes-data e detecta modelos via Prisma DMMF."
)
WriteLines $reportPath $reportLines
Write-Host "OK: report -> $reportPath"
Write-Host "DONE ✅ (seed missoes dev v0_1)"
